### ISSUE TITLE
Workspace sometimes crashes

### ISSUE THREAD

**Issue by akiyosi** [akiyosi/goneovim#1]
The occurrence condition that I could check is as follows.
* Immediately after starting Gonvim
* Immediately after moving :GonvimWorkspace*

**Comment by maths-lover** [comment]
I'm sorry if I got it right, but whenever I open goneovim and then create a new workspace it crashes.
and it says
`nvim:nvim_ui_attach validation: Expected width > 0 and height > 0`
while in `setting.toml` I have given
```
#setting.toml
[Editor]
Width = 800
Height = 600
# rest settings...
```

**Comment by akiyosi** [comment]
Hi :D 
What goneovim version are you using?
Please tell me the result of `:GonvimVersion`
