### ISSUE TITLE
Set 'gui_running' to 1

### ISSUE THREAD

**Issue by joereynolds** [akiyosi/goneovim#100]
With other guis, you can do `has('gui_running')` to check if you're running inside of a gui. This makes it easy to add gui specific things to your `.vimrc` or `init.vim`

**Comment by akiyosi** [comment]
Hi,
goneovim does not provide `gui_running`, but does provide `g:gonvim_running` instead. Neovim provides a GUI frontend with a different approach than Vim, so simply providing a traditional `gui_running` could have an impact. For example, Onivim provides `g:gui_oni` instead of `gui_running`.
