### ISSUE TITLE
Changing color scheme produces weird result

### ISSUE THREAD

**Issue by tssm** [akiyosi/goneovim#102]
![Screen-Recording-2020-03-01-at-0](https://user-images.githubusercontent.com/1188977/75622721-c6b88600-5ba3-11ea-9b94-e4bab5af1c78.gif)

(I don't know if it is helpful, but [VimR](https://vimr.org) had a similar issue, but I could press `Ctrl-L` to reload the screen)

**Comment by akiyosi** [comment]
Hi :D 
Thanks for this report. I have fixed this probrem in ca74a6e04.

**Comment by tssm** [comment]
Thanks!
