### ISSUE TITLE
Completion symbols

### ISSUE THREAD

**Issue by PitcherTear22** [akiyosi/goneovim#112]
Completion symbols in gnvim:
![Screenshot from 2020-04-10 19-43-28](https://user-images.githubusercontent.com/36493671/78997332-e4c7bd80-7b35-11ea-8a9b-b20cbb4a44fc.png)
![Screenshot from 2020-04-10 19-27-21](https://user-images.githubusercontent.com/36493671/78997355-f1e4ac80-7b35-11ea-8f36-3497ac57a192.png)
But in goneovim they all look the same:
![Screenshot from 2020-04-10 19-32-09](https://user-images.githubusercontent.com/36493671/78997360-f5783380-7b35-11ea-92fa-5a6b257ddac1.png)

**Comment by PitcherTear22** [comment]
I'm using coc.nvim and tried both executable lsp (clangd) and coc-clangd

**Comment by befedo** [comment]
Hi there,

You could have a look [here](https://github.com/akiyosi/goneovim/pull/73#issuecomment-551250408). Completion Items are defined by `suggest.completionItemKindLabels` from the coc.nvim side.

**Comment by PitcherTear22** [comment]
Can they not be implemented in the external popup?

**Comment by akiyosi** [comment]
@PitcherTear22 , @befedo 

Hi,
I don't know if the completion icon in your screenshot is drawn by GNVIM or by COC, but I think the external popup has room for improvement on the completion icon.
After I work on the problem I'm looking into, I'll look it up.

**Comment by PitcherTear22** [comment]
I think they were drawn by gnvim because no symbols appear in terminal
After using @befedo 's method, symbols appear in terminal and in goneovim using internal popup. External popup still has the same symbols

**Comment by PitcherTear22** [comment]
Should I test d8d73e0 ?

**Comment by akiyosi** [comment]
If you have the time and space, it would be helpful if you could give it a try.
I've made improvements to the icon display processing according to the completion kind in this commit, but there may still be cases that can't be handled.

**Comment by PitcherTear22** [comment]
It works properly now, except... there are no kind icons in terminal neovim.
(because I disabled `suggest.completionItemKindLabels` in `coc-settings.json`)

Is there a way out

**Comment by PitcherTear22** [comment]
Solved  - set custom `g:coc_config_home` and wrap it in `if(exists('g:gonvim_running`))`
