### ISSUE TITLE
goneovim doesn't run dettached.

### ISSUE THREAD

**Issue by qazip** [akiyosi/goneovim#113]
It would be cool if goneovim ran dettached from terminal, like sublime-text. Say I want to open a file to edit it. I would like to do

`goneovim file.txt`

and after that be able to use the terminal normally, without having to wait for the process to exit. It would also be cool to combine all goneovim processes into 1 window, again, like sublime. Say I have file.txt opened in goneovim and I want to open file2.txt. After doing `goneovim file2.txt`, I would like for both files to be opened in the same instance/window of goneovim.

**Comment by akiyosi** [comment]
Hi,
Thank you for the issue.

Please tell me about your environment. (Windows, WSL, Linux, MacOS, etc.)

**Comment by qazip** [comment]
> Hi,
> Thank you for the issue.
> 
> Please tell me about your environment. (Windows, WSL, Linux, MacOS, etc.)

Ah sorry, my bad!

OS: Arch Linux;
Goneovim: goneovim 0.4.3-1

It is out of date, but it's the one available in the Aur. Hopefully it gets updated soon.

**Comment by qazip** [comment]
The running detached bit can easily be "hacked" by adding the following to the bashrc.

```
goneovim() {
    goneovim "$*" &
}
```
However, I would like for all opened files to be in the same goneovim window. That is the one thing that is keeping me from using it for everything! Anyone knows of a way to "hack" it?

**Comment by akiyosi** [comment]
I would like to review your use case.

Are you envisioning a scene where you want to open an arbitrary text file in gooneovim in a desktop GUI environment, and if you already have a gooneovim session running, do you want to open the file as a new vim buffer in gooneovim that is running?

**Comment by qazip** [comment]
> I would like to review your use case.
> 
> Are you envisioning a scene where you want to open an arbitrary text file in gooneovim in a desktop GUI environment, and if you already have a gooneovim session running, do you want to open the file as a new vim buffer in gooneovim that is running?

Yes, exactly. However, I use "tabs" and not "buffers". I come from Sublime and I am used to using tabs. I like seeing what I've opened and whatnot.

**Comment by akiyosi** [comment]
To achieve the requested functionality, we probably need a new interface as a command line interface for gooneovim. I searched the WEB and found on gvim that there is an interface that is close to what you would expect. (See the link: https://vi.stackexchange.com/questions/13648/open-new-file-as-tab-on-current-vim-instance-through-double-click)

The idea is that goneovim will act as a server after starting, and then attach to the server and open with a new tab when the file is opened.

I would consider introducing this feature in v0.4.7.

**Comment by qazip** [comment]
Yes, that would be very nice. It's the one feature I am missing!

**Comment by qazip** [comment]
@akiyosi, is there a way to make plugins such as https://github.com/ap/vim-buftabline work in goneovim? I would like to show buffers in the tab bar, as if they were tabs.

**Comment by akiyosi** [comment]
@qazip 
You can enable the Plugin by appending the following line to `~/.goneovim/setting.toml`.

```
[Editor]
ExtTabline = false
```

**Comment by akiyosi** [comment]
This relates to #320, #341
