### ISSUE TITLE
Annoying horizontal line in the status bar

### ISSUE THREAD

**Issue by qazip** [akiyosi/goneovim#114]
Please see this pic: https://framapic.org/wJyMXGtAmqw4/PWMZoTNJ9INy.png

There is that annoying horizontal (white) line in the status bar. Any way to remove that? I removed lightline and it still shows.

OS: Arch linux
goneovim version 0.4.3-1

**Comment by akiyosi** [comment]
That border is the separator of the message window. You can change its color by explicitly specifying the highlight group `MsgSeparator`.
If that doesn't change, try a new version of the binary.

Also see the following issues #79

**Comment by PitcherTear22** [comment]
>You can change its color by explicitly specifying the highlight group ```MsgSeparator```

Sorry but how do you do this?

**Comment by PitcherTear22** [comment]
>  You can change its color by explicitly specifying the highlight group `MsgSeparator`.


Sorry but how do you do this?

**Comment by akiyosi** [comment]
e.g. Put the following line in your init.vim, or input directry into command line.

```
hi MsgSeparator guifg=#ff00ff
```

**Comment by PitcherTear22** [comment]
Thanks!

**Comment by qazip** [comment]
I will close this as it fixed my issue. gcolor2 is an handy tool to find out the color of your background, so you can match the line's color!

**Comment by PitcherTear22** [comment]
@qazip Or read your colorscheme duh
