### ISSUE TITLE
Can't select with mouse anymore

### ISSUE THREAD

**Issue by PitcherTear22** [akiyosi/goneovim#118]
After 74bb8d4, I can't position the cursor/select using the mouse.(first part of [video](https://imgur.com/YAqzkUt))
I can do it in latest release (second part)

**Comment by akiyosi** [comment]
Thanks for the report.  Had to grade in a previous commit 😅
I've fixed this problem with 7d8dab1ac593e84ba31622cfb1630dfea5e3c8c0.

**Comment by PitcherTear22** [comment]
Thanks
