### ISSUE TITLE
Scrolling by mouse causes some uncalled-for chars to appear

### ISSUE THREAD

**Issue by eyalk5** [akiyosi/goneovim#123]
![image](https://user-images.githubusercontent.com/23480511/81487787-b854ad80-9269-11ea-8ace-177fa93f1428.png)

The `it will save` on top doesn't exists.

To reproduce: 
scroll up several times using the mouse (fast)

To solve(maybe): do redraw on mouse scrolling (?)

I am on macos High-Sierra with 0.0.46.

**Comment by akiyosi** [comment]
Hi
How often does this problem occur?
Also, does it happen with `goneovim -u NONE`?

**Comment by eyalk5** [comment]
Couldn't reproduce it with `-u NONE`

**Comment by eyalk5** [comment]
It happens 30% percent of the time

**Comment by akiyosi** [comment]
Is 30% the incidence rate in`goneovim -u  NONE`? Or is it a situation where the occurrence rate at normal startup is 30% and does not occur in `goneovim -u NONE`?

Also, if you can't reproduce it in `goneovim -u NONE`, are there any keymaps or other settings related to scrolling in your settings, for example?

**Comment by eyalk5** [comment]
In my normal vimrc, happens 30 percent of the time. Yes, there are settings such as scrolloff and lines. I tried with them and minimal vimrc to no avail.
Btw happens also with pgdown.

**Comment by akiyosi** [comment]
I've tried to reproduce it in your vimrc, but I can't.
Does the mouse you're using have such a feature that accelerates the speed of scrolling as hardware?

**Comment by eyalk5** [comment]
no, it happens with pgdown too. It is less severe without set scrolloff=3. I open goneovim from terminal(iterm) to get the  tab key working, it is worth mention

**Comment by eyalk5** [comment]
It didn't happen in the last version you have sent.

**Comment by eyalk5** [comment]
The bug still exists. I have spent little in evaluating it previously, but now when I countinously work with it, I have noticed it again.

**Comment by eyalk5** [comment]
This is using last version(actions) , when doing scroll with the mouse. 
![vimcap3](https://user-images.githubusercontent.com/23480511/87484817-dced4d00-c63f-11ea-8466-c989c43101e8.gif)

**Comment by akiyosi** [comment]
@eyalk5 
Thanks for the detailed report!

I have perfectly identified the cause of the problem.
I will try to fix it soon.

**Comment by akiyosi** [comment]
Hi
I fixed this problem.
Would you please confirm the fix in the latest Actions binary?
https://github.com/akiyosi/goneovim/actions

**Comment by eyalk5** [comment]
Yeh, seems good! thanks. I will see how it will be in the following days, and close it probably.
