### ISSUE TITLE
Allow for a non-integer multiple of line numbers in GoNeoVim's text-area.

### ISSUE THREAD

**Issue by qazip** [akiyosi/goneovim#125]
I try to maximise my screen real-estate as much as possible, especially the vertical real-estate. It seems like goneovim has an extra line at the bottom? Please see the attached screenshots for goneovim and neovim.

![goneovim](https://user-images.githubusercontent.com/16175716/81671456-89d8fd00-9438-11ea-997b-da661e124884.png)

![nvim](https://user-images.githubusercontent.com/16175716/81671524-978e8280-9438-11ea-8702-21ef80b15c37.png)

Is that due to the fontsize or does goneovim have that extra-line regardless of font size? If so, is it possible to disable it and make it more "compact"? I am not refering to the horizontal line, I am refering to the fact that the whole bottom section is "fatter" on goneovim when compared with neovim.

**Comment by qazip** [comment]
Seems to be indeed a function of fontsize and window height..

**Comment by qazip** [comment]
This is one thing that I hate about vim, the fact that the height is an integer multiple of the line numbers. It would be amazing if it could show half-lines. There is such a big space in the bottom of the window that could be used to show 0.7 of an extra-line. This would improve looks but also increase screen-real-estate!

Could this be easily changed @akiyosi?

**Comment by akiyosi** [comment]
Hi
Sorry for the delay in replying.

It is possible, but some people may not like the behavior.
There may be an option in the future to allow such a display.

**Comment by qazip** [comment]
@akiyosi, no problem! Take all the time you need to reply. I am just happy you exist!! 

Ya, such a feature would be amazing. It drives me nuts having 1cm of unused space in the bottom of the window. My OCD goes through the roof!
