### ISSUE TITLE
Is there a way to embed a terminal?

### ISSUE THREAD

**Issue by TheBdouilleur** [akiyosi/goneovim#126]
Hello,
I really love Goneovim, thank you very much it's certainly the best Vim/Neovim GUI. I have a question:
Can I embed a terminal (ie. for running my code, etc) into Goneovim?
If no, please implement it. IMHO it's the *one* feature missing.

Thank you

**Comment by akiyosi** [comment]
Hi
Thanks for using Goneovim.

What exactly is the intended function of "embedded terminal"?
Is Neovim's Terminal feature(`:terminal`) not enough for what you're expecting?

**Comment by TheBdouilleur** [comment]
thanks for your reply ! I'm new to the Vim world, and I didn't know `:terminal` existed. It's exactly what i'm looking for though. Thank you!
