### ISSUE TITLE
About ExtCmdline function, issue of suggest display 

### ISSUE THREAD

**Issue by kask-z** [akiyosi/goneovim#130]
Hi

I found issue of Cmdline.

In setting.toml,
if it sets
```
ExtCmdline   = false
ExtPopupmenu = false
```
The display position of suggest is strange.

![goneovim-1](https://user-images.githubusercontent.com/41232865/83325838-6a502a00-a2aa-11ea-956a-88ec3f5421d0.jpg)
If it sets 
```
ExtCmdline   = false
ExtPopupmenu = true
```
This issue don't occur.
![goneovim-2](https://user-images.githubusercontent.com/41232865/83326572-0df00900-a2b0-11ea-8f84-cb0de03641b8.jpg)

So this issue is not a big deal.
If you fix this issue when you have time,I'm glad.

I always feel grateful for goneovim. 

Thank you.

**Comment by akiyosi** [comment]
Hi :)
Thanks for the issue report.

While not yet included in the release, this issue has already been fixed in the 00deb091b59799517d0f998c23e1a57a5fbe1339.
If you are Linux or MacOS user, you can get the latest binaries in the github actions.
https://github.com/akiyosi/goneovim/actions

**Comment by kask-z** [comment]
Thank you for your reply.

I'm sorry. I didn't write my enviroment.
My os is Windows10 64bit.
And I'm using Goneovim-0.4.6-win64.zip. 
In windows10, Should I wait a little longer?

**Comment by akiyosi** [comment]
Oh...
Okey, I will consider putting out the next release as soon as possible.

**Comment by kask-z** [comment]
I’m not in a hurry so you should work at your usual pace.
I'll wait slowly.
Thank you for your kindness!
