### ISSUE TITLE
Unable to paste into ExtCmdLine

### ISSUE THREAD

**Issue by ghost** [akiyosi/goneovim#135]
Hi @akiyosi ,

It's not possible to paste into the ExtCmdLine.
I'm running Manjaro Gnome and the daily build of 0.4.6.

Thanks!

**Comment by akiyosi** [comment]
Hi,
What exactly is your 'paste' action? 
I would like to know a few more details. Such as `<C-r>"`?.

**Comment by darkermatter** [comment]
```<c-v>```, ```<c-s-v>``` don't do anything.
```<c-r>"``` pastes in something, but not the last thing on the clipboard (see image).

![Screenshot from 2020-06-12 08-30-42](https://user-images.githubusercontent.com/5037324/84472483-85963e80-ac87-11ea-8381-1fa3b6941869.png)

**Comment by akiyosi** [comment]
In vim/neovim, I think those shortcuts can't paste text from the clipboard.
Do you have a mapping definition for those keys in init.vim? 
If you have it set up, please let me know what kind of mapping you are setting.

Also, did other vim environments (Terminal, MacVim, VScodeVim, etc.) provide such shortcuts by default?

**Comment by darkermatter** [comment]
Here are my mappings.

https://gist.github.com/darkermatter/427104a868d01da78e65b4909929ab65

**Comment by darkermatter** [comment]
I don't have anything which would interfere - at least I don't think so

**Comment by darkermatter** [comment]
I added my plugins to the gist.

**Comment by PitcherTear22** [comment]
> In vim/neovim, I think those shortcuts can't paste text from the clipboard.
> Do you have a mapping definition for those keys in init.vim?
> If you have it set up, please let me know what kind of mapping you are setting.
> 
> Also, did other vim environments (Terminal, MacVim, VScodeVim, etc.) provide such shortcuts by default?

Most terminals have <C-S-v>

**Comment by akiyosi** [comment]
I'd like to clarify what is critical to this problem.
I don't think ExtCmdline has any direct effect on this issue.
For example, would the following mapping solve your problem?

```
" for windows, unix like system
cnoremap <C-v> <C-r>+
" for MacOS
cnoremap <D-v> <C-r>+
```

ref: https://vim.fandom.com/wiki/Pasting_registers
