### ISSUE TITLE
The external status line disappears when Editor.Transparent is not 1.0

### ISSUE THREAD

**Issue by high-moctane** [akiyosi/goneovim#136]
Hi,
Thank you for the amazing app (｀･ω･´)！

The external statusline vanishes when Editor.Transparent in setting.toml is not the default value.

This is the screenshot when Editor.Transparent is 0.9.
<img width="800" alt="スクリーンショット 2020-06-11 4 08 48" src="https://user-images.githubusercontent.com/13066581/84308518-9ff1ee80-ab99-11ea-9ec1-9860d37d52ed.png">

## Environment

- setting.toml

```toml
[Editor]
Transparent = 0.9

[Statusline]
Visible = true
```

- No ~/.config/nvim/init.vim

- OS
  - iMac (Retina 4K, 21.5-inch, 2019)
  - macOS 10.15.5

- goneovim version
  - 0.4.6

- Neovim version
  - 0.4.3
  - Installed via Homebrew

**Comment by akiyosi** [comment]
Hi,
Thanks for the issue report.

My MacOS (10.13.6, 10.14.6) cannot reproduce this issue at this time.
Perhaps it's a problem that depends on the new MacOS and Qt relationships.
I will continue to investigate.

**Comment by J053Fabi0** [comment]
I have the same problem. I'm on Arch linux.

**Comment by FinallyFinancialFreedom** [comment]
same problem, macos bigsur

**Comment by shaunsingh** [comment]
Same problem, happens with both the external as well as regular neovim statusline
