### ISSUE TITLE
[FeatureRequest] smartTabs?

### ISSUE THREAD

**Issue by JoeSchr** [akiyosi/goneovim#142]
Hi, really awesome work with this project!

Is there a smarttab feature so the tabs are only displayed once there are more than one? I seldom use them and it takes up quite a lot of screen estate:
![image](https://user-images.githubusercontent.com/8218910/86577964-553a7b00-bf7b-11ea-90d5-13bce6bc3749.png)
I mean the "No Name" part

**Comment by JoeSchr** [comment]
I think it also would be really cool, when there is not tab displayed the filename is displayed in the titlebar (where now it says "goneovim" )

**Comment by akiyosi** [comment]
Hi,
Thanks for the feature request.
Smart tabs seem like a very good idea.
I think I'll be implementing it in the near future.

Also, for the title bar display information, we may be able to achieve the behavior we expect with `titlestring`.

**Comment by JoeSchr** [comment]
Awesome 🤗
