### ISSUE TITLE
Windows always on top?

### ISSUE THREAD

**Issue by kierun** [akiyosi/goneovim#144]
When I start `goneovim` (from package, linux pre-built latest version), the window appears to always be on top. Removing focus, focusing on a different window, or whatnot just keeps the `goneovim` on top. Now, generally this is a feature of the window manager (I use [awesome](https://awesomewm.org)) and I have not set that up at all.

Any idea what is going on?

OS is Fedora 32, running X11.

**Comment by akiyosi** [comment]
Hi.
Could you please try the latest build of Github Actions?
https://github.com/akiyosi/goneovim/actions/runs/194900944

**Comment by kierun** [comment]
Same behaviour I am afraid.

**Comment by akiyosi** [comment]
Sorry for late reacion.
I've probably found the cause and fixed it.
I would like to happy if you could check the probrem with latest goneovim.

https://github.com/akiyosi/goneovim/actions/runs/234555676

**Comment by kierun** [comment]
This build solved the issue. Thank you so much!
