### ISSUE TITLE
How to make Goneovim look more like Gonvim

### ISSUE THREAD

**Issue by Famiu** [akiyosi/goneovim#146]
So, first of all I want to say that I LOVE Goneovim, and I find the code to be quite readable as well to the point I actually wish to contribute to it in the future. I love the work you're doing and hope you keep developing this fantastic project.

With that said, a lot of things seem to have changed from Gonvim, which makes sense since this was forked from Gonvim, and change is obviously good. But, well, I like the old Gonvim UI (as seen in this screenshot) more:
![image](https://user-images.githubusercontent.com/29580810/89730535-486ce380-da61-11ea-908f-16be98b29d3a.png)
For example, the statusbar in that screenshot is dark as opposed to the light Statusbar in Goneovim and I like the overall look of the Sidebar, Tab Bar, External Messages and External Command Line more as well. Again, this is perfectly opinionated, but that's fine because I'm not asking you to change the default. All I want is a way to make it look that way, perhaps through a configuration option. Is it possible already? If not, would you consider making it possible?

**Comment by akiyosi** [comment]
hi :)
That's very nice, thank you.

The statuslines are controlled by the "StatusLine" highlight group. You may be able to change its color by defining the following in your init.vim.

``` init.vim
hi StatusLine guifg=#282c34 guifg=#abb2bf
```

if you want to make Gonovim look more like a screenshot of the Gonvim repository, Example setting is the following:

#### init.vim
```
...
Plug 'joshdick/onedark.vim'
...
hi StatusLine guifg=#282c34 guifg=#abb2bf
...
```

#### ~/.goneovim/setting.toml

```
[Editor]
Borderless = false
ExtCmdline   = true
ExtPopupmenu = true
ExtTabline   = true
ExtMessages  = true

Clipboard = true
Macmeta = true
DrawBorder = true
IndentGuide = true


[Message]

[Statusline]
Visible = true
ModeIndicatorType = "textLabel"


[Tabline]
Visible = true

[Popupmenu]

[Lint]
## Specifies whether the external linter tooltip should be displayed or not.
Visible = true

[MiniMap]
Disable = false
Visible = false

[ScrollBar]
Visible = true

[SideBar]
Visible = true
Width = 200

[Workspace]
PathStyle = "minimum"
RestoreSession = false
```

Here's the screenshot you'll get:
<img width="1498" alt="2020-08-12 23 37 30" src="https://user-images.githubusercontent.com/8478977/90031051-c21dff00-dcf7-11ea-91a6-0798bf883ee6.png">

**Comment by Famiu** [comment]
Adding the highlight group for status line did nothing :/ . I also tried changing the first "guifg" to "guibg" (cause that was obviously a typo) and also doing it as is, neither worked. Also, how do I get the thick, black borders between splits like Gonvim? Also, how do I get an icon besides the file name in the GUI tabbar like in Gonvim? And is there a way to change the underline color in the GUI tabbar to blue? Sorry if I'm asking for too much

**Comment by akiyosi** [comment]
Sorry, there seems to be some kind of glitch that keeps the colors from changing. Please try the latest build of Github Action for the time being.
https://github.com/akiyosi/goneovim/actions/runs/205706059

Also, you can't change the color of the borders at this time. I'll try to make it changeable.

You can change the tabline underline color by the "TabLineFill" highlight group. 
The tab icons cannot be displayed at the moment. I have removed it from Gonvim. (Because I preferred a simpler design. :P )

The file tree in Gonvim's left sidebar is a Vim plugin, not Gonvim's native sidebar. I think that is default filer netrw or NERDTree, for example.

**Comment by Famiu** [comment]
I will wait for the build to finish and see if that works. Also, thank you very much. I really appreciate that you're using your valuable time to help me out.

**Comment by Famiu** [comment]
@akiyosi Okay so, using the latest build _did_ change the color of the StatusLine, but some parts of the foreground are still dark. Screenshot:
![image](https://user-images.githubusercontent.com/29580810/90086258-dc79cc00-dd3b-11ea-9a3b-1574f080b428.png)
TabLineFill works as well.

However, it'd still be nice to have icons on Tab Bar (maybe make them optional?). I'll make a separate issue for that. Also I want to make a separate issue for the option to change border style, color and width.

Thanks again for all your work.

**Comment by Famiu** [comment]
By the way, how do I fix parts of the status line foreground being dark? (the icons, especially)
