### ISSUE TITLE
Manual font fallback

### ISSUE THREAD

**Issue by p00f** [akiyosi/goneovim#147]
Hi, I want fonts to fallback in the order I specify

(If the glyph is not in JetBrains Mono, then use Noto Color Emoji, then use everything else)

I can't use systemwide fontconfig because terminals have problems with wide emojis

**Comment by akiyosi** [comment]
Hi,
You can specify a list of font settings in `guifont`, but is this not what you want?

**Comment by p00f** [comment]
Like this?
`set guifont=JetBrains\ Mono,Noto\ Color\ Emoji:h11`

**Comment by akiyosi** [comment]
Yes,
like this:

```
set guifont=JetBrains\ Mono:h10,Noto\ Color\ Emoji:h11
```

If it doesn't seem to be working, there might be a bug in it.

**Comment by p00f** [comment]
Hmm I need to find out if 

![](https://github.githubassets.com/images/icons/emoji/unicode/26a0.png)
is a glyph in JetBrains Mono [comment](https://github.com/JetBrains/JetBrainsMono/issues/277#issuecomment-673001316), because it looks like 
![image](https://user-images.githubusercontent.com/36493671/90079041-674ecc80-dd24-11ea-9d0c-97aadad8f17d.png)

**Comment by p00f** [comment]
It looks like this when I set the first fonr to anything tho

**Comment by p00f** [comment]
Actually no, when I use this fontconfig
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<!--
Noto Mono + Color Emoji Font Configuration.

Currently the only Terminal Emulator I'm aware that supports colour fonts is Konsole.

Usage:
0. Ensure that the Noto fonts are installed on your machine.
1. Install this file to ~/.config/fontconfig/conf.d/99-noto-mono-color-emoji.conf
2. Run `fc-cache`
3. Set Konsole to use "Noto Mono" as the font.
4. Restart Konsole.
-->
<fontconfig>
  <match>
    <test name="family"><string>JetBrains Mono</string></test>
    <edit name="family" mode="prepend" binding="strong">
      <string>Noto Color Emoji</string>
    </edit>
  </match>
</fontconfig>
```
and `set guifont=JetBrains\ Mono:h11`, it uses the proper emoji:
![image](https://user-images.githubusercontent.com/36493671/90096528-26b97800-dd51-11ea-8169-85dfb32ff5fb.png)
so looks like `guifont` is indeed bugged
(cc @Kethku @j4qmfrost)

**Comment by akiyosi** [comment]
Character-by-character font fallback functionality has been recently implemented and will be closed
