### ISSUE TITLE
Show icons on Tab bar

### ISSUE THREAD

**Issue by Famiu** [akiyosi/goneovim#149]
I think there should be an option to show icons based on the file type on the GUI tab bar. It should be optional so if someone prefers a more minimalistic look they can disable the icons. Gonvim used to have this feature so I think it won't be too hard to add back.

**Comment by akiyosi** [comment]
I implemented this feature in v0.4.7 branch.
If you are a MacOS or Linux user, you can check out the feature in the following branches I'd appreciate your feedback.

https://github.com/akiyosi/goneovim/actions/runs/220881644

To enable the feature, add the following settings to `~/.goneovim/setting.toml`

``` toml
...
[Tabline]
Visible = true
ShowIcon = true
...
```

**Comment by akiyosi** [comment]
Merged.
