### ISSUE TITLE
found some bugs in 0.4.7

### ISSUE THREAD

**Issue by DONofDESTROY** [akiyosi/goneovim#153]
hey @akiyosi 
first of all thank you for maintaing this project
so after the latest release here is the bugs I found 
![image](https://user-images.githubusercontent.com/47606472/92258105-f4381080-eef3-11ea-87c7-dfc5e718552f.png)
that info or detail is not displaying in the right place

having this in setting.toml disables the scroolbar in the minimap
```toml
[MiniMap]
Disable = false
Visible = true
```
![image](https://user-images.githubusercontent.com/47606472/92258415-70caef00-eef4-11ea-94f2-db2bde5c3391.png)
without those lines and enabling with `:GonvimMiniMap` has scrollbar
![image](https://user-images.githubusercontent.com/47606472/92259847-ffd80700-eef4-11ea-9496-714e005a8043.png)

and finally having these in Coc-Settings.json
```json
  "suggest.completionItemKindLabels": {
    "function": "\uf794",
    "method": "\uf6a6",
    "variable": "\uf71b",
    "constant": "\uf8ff",
    "struct": "\ufb44",
    "class": "\uf0e8",
    "interface": "\ufa52",
    "text": "\ue612",
    "enum": "\uf435",
    "enumMember": "\uf02b",
    "module": "\uf668",
    "color": "\ue22b",
    "property": "\ufab6",
    "field": "\uf93d",
    "unit": "\uf475",
    "file": "\uf471",
    "value": "\uf8a3",
    "event": "\ufacd",
    "folder": "\uf115",
    "keyword": "\uf893",
    "snippet": "\uf64d",
    "operator": "\uf915",
    "reference": "\uf87a",
    "typeParameter": "\uf278",
    "default": "\uf29c"
  },
```
shows only these icons for the  types
![image](https://user-images.githubusercontent.com/47606472/92260625-d2d82400-eef5-11ea-9a0d-01f90a7e678c.png)

by commenting those it displays correctly 

![image](https://user-images.githubusercontent.com/47606472/92260533-aa502a00-eef5-11ea-882a-1c07991396cd.png)

**Comment by akiyosi** [comment]
Hi :D 
Thanks for this issue reporting.

> that info or detail is not displaying in the right place

The `info` and `detail` part will be displayed in different ways depending on the settings.toml. 
What kind of settings do you use in `~/.goneovim/setting.toml`?
(BTW, default width of `info` part is 1px )

``` toml
[Popupmenu]
# ## neovim's popupmenu is made up of word, menu and info parts.
# ## Each of these parts will display the following information.
# ##   word:   the text that will be inserted, mandatory
# ##   menu:   extra text for the popup menu, displayed after "word"
# ##   info:   more information about the item, can be displayed in a preview window
# 
# ## The following options specify whether to display a dedicated column in the popupmenu
# ## to display the long text displayed in the `info` part.
# ShowDetail = true
# 
# ## total number to display item
# Total = 20
# 
# ## width of `menu` column
# MenuWidth = 400
# 
# ## width of `info` column
# InfoWidth = 1
# 
# ## width of `detail` column
# DetailWidth = 250
```


> having this in setting.toml disables the scroolbar in the minimap
> ...
> without those lines and enabling with :GonvimMiniMap has scrollbar

I fixed this issue in https://github.com/akiyosi/goneovim/commit/257193bea95d9beaec1e7872d65d878b2db3727b


> and finally having these in Coc-Settings.json
> ...
> shows only these icons for the types

Yes, this is a known issue (See https://github.com/akiyosi/goneovim/pull/73#issuecomment-551175317),
and because Goneovim identifies the icon types from the "kind" of completion candidates, it is not able to successfully identify the icon types when these are specified on the Coc side. 
There may be a good way to improve this, but I haven't had enough time to investigate.

**Comment by DONofDESTROY** [comment]
@akiyosi 
>What kind of settings do you use in ~/.goneovim/setting.toml?
```toml
[Popupmenu]
ShowDetail = true

## total number to display item
Total = 20

## width of `menu` column
MenuWidth = 400

## width of `info` column
InfoWidth = 1
```
I use the default config for that and I may be wrong

**Comment by akiyosi** [comment]
@DONofDESTROY 
If you want to see the info part, widen its width.
Also, if you don't get any info, either there's no info from the LSP or they may have been taken down by goneovim, and if the latter, it's a bug.

**Comment by DONofDESTROY** [comment]
@akiyosi 
I am sorry I was trying to tell about this
![image](https://user-images.githubusercontent.com/47606472/92364666-03e07080-f111-11ea-8c36-67474d53db5a.png)
it has area but it is displaying on somewhere else

**Comment by akiyosi** [comment]
@DONofDESTROY 
Oh, I'm sorry, I didn't understand.

I want to make sure that
- Is your configuration capable of reproducing this event in the following repository?
  https://github.com/DONofDESTROY/NeoVim-config
- Does this happen in v0.4.6?

**Comment by DONofDESTROY** [comment]
>Is your configuration capable of reproducing this event in the following repository?
this is my config I am using currently  

it works sometimes 
I disabled all config of coc, so  this must be  default behaviour 
![image](https://user-images.githubusercontent.com/47606472/92495601-bcdba380-f214-11ea-8e05-b1d926856a75.png)
sometimes both
![image](https://user-images.githubusercontent.com/47606472/92495724-e399da00-f214-11ea-9ca0-29a8bc27ee9d.png)

and this is 0.4.6
![image](https://user-images.githubusercontent.com/47606472/92496167-6e7ad480-f215-11ea-9195-c658a0271e6a.png)

can I try with your neovim config

**Comment by akiyosi** [comment]
Hmmm, I realized.
This is a known issue if you have `ext_popupmenu` enabled.
That is, Coc uses a float window to display additional information depending on the items in the completion menu. This appears in a nice place when `ext_popupmenu` is disabled, but when it's enabled, it doesn't appear in concert with the completion UI that Goneovim displays.
If you can disable the ability to display this additional float window on the Coc side, try that.
We've reported a similar problem before. Please check it out as well. ref: https://github.com/akiyosi/goneovim/issues/95#issuecomment-583825127

**Comment by DONofDESTROY** [comment]
>We've reported a similar problem before. Please check it out as well. ref: #95 (comment)

That solves that issue
