### ISSUE TITLE
Goneovim captures audio device

### ISSUE THREAD

**Issue by cpkio** [akiyosi/goneovim#155]
Windows 10 x64: Goneovim 0.4.7 captures audio device, disabling any playback, and seemingly does not give it back after exiting. Dont know why `qtaudio_wasapi.dll` and `qtaudio_windows.dll` are bundled.

But the software is awesome, extremely happy with it's speed! Needs some font antialias tweaking, but it's OK.

**Comment by akiyosi** [comment]
Hi
Thanks for the issue reporting!

Oh, I'm lazy to have that module bundled. 
There are various modules in the artifacts that it built. But the only directory included in the directory of Goneovim that is required is the `platforms` directory.

**Comment by cpkio** [comment]
Removed unnecessary directories, runs fine. What files from this list are safe to remove?
```
Name
D3Dcompiler_47.dll
libEGL.dll
libGLESV2.dll
opengl32sw.dll
Qt5Core.dll
Qt5Gui.dll
Qt5Multimedia.dll
Qt5MultimediaQuick.dll
Qt5Network.dll
Qt5Positioning.dll
Qt5PrintSupport.dll
Qt5Qml.dll
Qt5Quick.dll
Qt5QuickControls2.dll
Qt5QuickTemplates2.dll
Qt5QuickTest.dll
Qt5QuickWidgets.dll
Qt5SerialPort.dll
Qt5Svg.dll
Qt5Test.dll
Qt5WebChannel.dll
Qt5WebEngineCore.dll
Qt5WebEngineWidgets.dll
Qt5Widgets.dll
QtWebEngineProcess.exe
```

**Comment by akiyosi** [comment]
Hmm, I don't know for sure, but one way to do it is to try to delete those files while running Goneovim. 
You can't delete the files goneovim need, and as a result, only the files you can delete will be deleted

**Comment by akiyosi** [comment]
@cpkio 
Has this problem been solved?
If it is solved, I would like to close the issue.

**Comment by cpkio** [comment]
Probably I was wrong and this was my audio interface issue. Let's close it for now.
