### ISSUE TITLE
In 'relativenumbers' mode in a line with cursor indent guides disappear

### ISSUE THREAD

**Issue by cpkio** [akiyosi/goneovim#156]
Tested with v0.4.7 and without any user configuration. Seem to be some quirks with cursorline behaviour too — indent guide not «falling» from a «function» word.
![2020-09-07_16-24-59](https://user-images.githubusercontent.com/1917113/92392639-3bf2ae00-f127-11ea-8f1c-2acf6063c9f7.gif)

**Comment by akiyosi** [comment]
Thanks for reporting the issue.
I have fixed it. (caa0c2dd89ae72723bf5dd59f0902592ecc840f5)

**Comment by akiyosi** [comment]
Closed.
