### ISSUE TITLE
Moving config files to .config folder for linux

### ISSUE THREAD

**Issue by DONofDESTROY** [akiyosi/goneovim#158]
hey @akiyosi 

This is not too important 
but Is it possible to move the config of goneovim into .config folder for Linux so it  will be easy to maintain

**Comment by akiyosi** [comment]
Hi
Thanks for the suggestion.
I also have thought about this change a few times as well.

For MacOS,Linux only, this change seems to improve the convenience.
I will consider making changes in the next release.

**Comment by akiyosi** [comment]
This suggestion was added in v0.4.8.
Could you check it out if you'd like.
