### ISSUE TITLE
transparency makes tab line gone

### ISSUE THREAD

**Issue by bon-ami** [akiyosi/goneovim#159]
Windows 10. goneovim 0.4.7. neovim 0.4.4
When I set Transparent = 0.9 in settings, the line of my tabs is gone. Is this by design? And then if I use :version, the info is transparently shown upon my current buffer and mixed up.
![screenshot](https://file.io/rylAsZN7i9sf)

**Comment by akiyosi** [comment]
Thanks for the report.
I've fixed the problem with c951539
