### ISSUE TITLE
Is it possible to create a new variable for goneovim

### ISSUE THREAD

**Issue by DONofDESTROY** [akiyosi/goneovim#161]
hey @akiyosi 
Vscode [nvim](https://github.com/asvetliakov/vscode-neovim) uses a nvim instance to do the emulation.

while using vscode nvim the user has the option to set something like this
> Important!: If you already have big & custom init.vim i'd recommend to wrap existing settings & plugins with if !exists('g:vscode') check to prevent potential breakings and problems. If you have any problems - try with empty init.vim first

which kinda separates the nvim and vscode nvim 
so is it possible to replicate this with goneovim

we have to run this code at starting of goneovim (As far as i think)

```viml
if !exists("g:goneovim")
	let g:goneovim = 1
endif
```
so now we can add custom config for goneovim like

```viml
if (g;goneovim)
 " disable the airline
 " set custom statusline 
endif
```

**P.S** If this is not how goneovim works close this issue

**Comment by akiyosi** [comment]
Hi,
Sorry for poor doc.
Your expected global variable is the `g:gonvim_running`.

e.g.
```
if exists('g:gonvim_running')
  set laststatus=0
  nnoremap <leader><leader> :GonvimWorkspaceNew<CR>
  nnoremap <leader>n :GonvimWorkspaceNext<CR>
  nnoremap <leader>p :GonvimWorkspacePrevious<CR>
endif
```
