### ISSUE TITLE
Setting ExtMessages to true should automatically set ExtCmdLine to true as well

### ISSUE THREAD

**Issue by svermeulen** [akiyosi/goneovim#162]
Currently if you set `ExtMessages` to true, but do not set `ExtCmdline` (leaving it as the default false), then the command line will be fully invisible.  I am guessing this is because neovim automatically sets `ext_cmdline` to true when passing `ext_messages` as true

**Comment by akiyosi** [comment]
Hi,
Thanks for the issue.
Yes, if Ext_messages is true, then Ext_cmdline should also be true. I'll try to fix that in the next release.

**Comment by akiyosi** [comment]
This has been fixed in v0.4.8.

**Comment by akiyosi** [comment]
Closed.
