### ISSUE TITLE
Cannot use `<cmd>+v` to paste from clipboard

### ISSUE THREAD

**Issue by pjg** [akiyosi/goneovim#163]
In normal mode pressing `<cmd>+v` goes into visual.
In insert mode pressing `<cmd>+v` outputs `<D-v>`.

Expectation: contents of the clipboard should be pasted into the buffer.

MacOS v0.4.7.

**Comment by akiyosi** [comment]
Hi
Thanks for the issue report.

Many terminals seem to support pasting from the clipboard via `<cmd>+v` or `<cmd>+<shift>+v`, but Goneovim makes this key an "open seat".
This means that if the user wishes, they can paste from the clipboard with the following mapping;

```
nnoremap <D-v> a<C-r>+<Esc>
inoremap <D-v> <C-r>+
cnoremap <D-v> <C-r>+
```

Or other users can map a different operation.

**Comment by pjg** [comment]
Thanks! This works. I recommend setting those as defaults in Mac builds. Both MacVim and VimR do that in one way or the other.

**Comment by akiyosi** [comment]
> I recommend setting those as defaults in Mac builds. Both MacVim and VimR do that in one way or the other.

Okey, I will think it.
Closed.

**Comment by simschla** [comment]
FWIW, this is how I worked around this issue in my `.vimrc`:

```
" add keymappings in goneovim only
if exists("g:goneovim")
  " set CMD+V to paste in all modes
  nnoremap <D-v> a<C-r>+<Esc>
  inoremap <D-v> <C-r>+
  cnoremap <D-v> <C-r>+
endif
```
