### ISSUE TITLE
goneovim failing to open on MacOs

### ISSUE THREAD

**Issue by harun12** [akiyosi/goneovim#165]
Hey Guys,

Ive just downloaded the prebuilt binary of goneovim and I'm running into an issue where the gui opens but whenever I type anything it crashes.

Any reason why this would happen?

I have neovim version 0.4.4
<img width="801" alt="Screen Shot 2020-09-24 at 5 19 56 PM" src="https://user-images.githubusercontent.com/14851850/94201581-3072e700-fe8a-11ea-9e3e-2716f9ede3c6.png">

**Comment by akiyosi** [comment]
Hi

Does nvim exist under `$PATH` in your terminal environment? In other words, does `nvim` start by opening a terminal and run `nvim`?

``` bash
$ nvim
```

Also, what kind of behavior and message output will occur when goneovim is started from the command line in the terminal environment?

``` bash
$ /Applications/goneovim.app/Contents/MacOS/goneovim
```

**Comment by harun12** [comment]
> Hi
> 
> Does nvim exist under `$PATH` in your terminal environment? In other words, does `nvim` start by opening a terminal and run `nvim`?
> 
> ```shell
> $ nvim
> ```
> 
> Also, what kind of behavior and message output will occur when goneovim is started from the command line in the terminal environment?
> 
> ```shell
> $ /Applications/goneovim.app/Contents/MacOS/goneovim
> ```

nvim opens just fine it exists in the path. I've been using nvim regularly without a gui so when I heard of this I thought it would be cool to try out.

Opening goneovim from command line in the terminal env using the path you provided works just fine. I noticed that the other day. Very weird :/

**Comment by akiyosi** [comment]
Like this issue https://github.com/akiyosi/goneovim/issues/164, there are differences in the exported environment variables between the terminal and desktop depending on the settings. Also check whether `nvim` can be executed with the profile of `$SHELL` you are using. 

I also want to know your init.vim settings, can I find them somewhere?

**Comment by harun12** [comment]
My init is very simple I'm just pulling in different files to keep things clean.

Hmm when I do echo ${SHELL} i get /usr/local/bin/fish but fish does not exit I removed it.. it might be lingering around and messed with my shells


<img width="801" alt="Screen Shot 2020-09-26 at 11 13 53 AM" src="https://user-images.githubusercontent.com/14851850/94343907-7a261380-ffe9-11ea-9a8a-7e63e341571c.png">

**Comment by harun12** [comment]
Okay I fixed it. It looked like it was still trying to use fish and i removed it hence why it was crashing. Now it works just fine :)

**Comment by akiyosi** [comment]
It's probably a direct result of the environment variables used to run nvim, but at any rate, good for you! :D
closed.
