### ISSUE TITLE
Cursor does not resize to respect linespace

### ISSUE THREAD

**Issue by khalidchawtany** [akiyosi/goneovim#167]
Cursor stays the same height regardless of the linespace. Also the character under cursor seems to be misplaced upwards.
This is on MacOS latest release `v 0.4.8`

![Kapture 2020-10-06 at 21 55 24](https://user-images.githubusercontent.com/1681606/95247648-cad61180-081e-11eb-9f2f-264b9c5a7244.gif)

**Comment by akiyosi** [comment]
Hi
Thanks for the issue report.
I hadn't noticed this problem because I never specified a large value for linespace. I fixed this problem in 925dd9be7.

**Comment by akiyosi** [comment]
Hi
I've made a release that fixes this problem; try it out in [0.4.8.1](https://github.com/akiyosi/goneovim/releases/tag/v0.4.8.1)
