### ISSUE TITLE
Autocomplete overlayed upon text

### ISSUE THREAD

**Issue by codic12** [akiyosi/goneovim#168]
Example (ExtPopupmenu is true, but also occurs when it is false):

![image](https://user-images.githubusercontent.com/48339289/95633949-a015d400-0a3d-11eb-88e2-12a7b7c5bc97.png)

The first line of the popup had the text "imp" under it but it gets hidden.

**Comment by akiyosi** [comment]
Hi,
Thanks for this issue report.

Hmmm, this is odd. It doesn't happen in my environment. 
If it doesn't depend on the value of `ExtPopupmenu`, it may be a problem dependent on the init.vim setting or a specific plugin.

I'd like to investigate this problem using your settings. Are you using the following settings?
https://github.com/codic12/dots/tree/master/vim

Also, does the same issue occur if there are no settings?　Check the following.

```
/path/to/goneovim -u NONE
```

In MacoS:

```
/Applications/goneovim.app/Contents/MacOS/goneovim -u NONE
```

**Comment by codic12** [comment]
Actually, no, those are old ones; I am just using SpaceVim with coc.nvim at the moment.
With that command I have no autocomplete at all, so I can't debug like that.

**Comment by akiyosi** [comment]
Umm,
I've tried working with spacevim and Coc settings, but I can't reproduce them.
<img width="719" alt="スクリーンショット 2020-10-14 22 16 23" src="https://user-images.githubusercontent.com/8478977/95994624-7b6d9200-0e6b-11eb-8f6d-875f7c00609f.png">
<img width="786" alt="スクリーンショット 2020-10-14 22 19 01" src="https://user-images.githubusercontent.com/8478977/95994671-89231780-0e6b-11eb-8453-d768af439e1c.png">

> With that command I have no autocomplete at all, so I can't debug like that.

I don't quite understand the above.

**Comment by codic12** [comment]
With the `-u NONE` I have no settings so there is no autocomplete for me to try. However strangely enough after resetting my settings, it works, so I'll close this!

~~Also noticed... neovide? rust? while showing off **go**neovim?~~

**Comment by codic12** [comment]
Ah alright, I didn't know that ,sorry
