### ISSUE TITLE
Can't open in macOS 10.15.7

### ISSUE THREAD

**Issue by TENX-S** [akiyosi/goneovim#169]
Just open it from the launchpad, then I got this:
<img width="488" alt="Screen Shot 2020-10-10 at 3 53 41 PM" src="https://user-images.githubusercontent.com/40336192/95649628-f6a01280-0b10-11eb-988c-8862c641dff7.png">

but I already have this:
<img width="780" alt="Screen Shot 2020-10-10 at 3 53 53 PM" src="https://user-images.githubusercontent.com/40336192/95649667-3d8e0800-0b11-11eb-86ce-04e6aef1c50e.png">

What should I do? Thanks!

**Comment by akiyosi** [comment]
Hi
You can open it by following these steps :)

    1. In the Mac Finder, display the application you want to open.

    2. Control-click the application icon and select "Open" from the shortcut menu.

    3. Click Open.

However, the first time you perform this step, the application will fail to start. After this step, the application will be saved as an exception to the security settings and can be opened by double-clicking it in the future, just like any registered application.
The second time around, the application will start successfully.

**Comment by TENX-S** [comment]
It works, thanks a lot! @akiyosi
