### ISSUE TITLE
ExtCmdline not respected, no statusline

### ISSUE THREAD

**Issue by badosu** [akiyosi/goneovim#171]
It keeps using the gui cmdline from goneovim and the statusline does not show up.

Config: https://gist.github.com/badosu/093cab42c783b95b020b1494403f445b
Vim version (happens with 0.4.4 too):

```
NVIM v0.5.0-754-g3566244d0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-38306432-5df3-4c68-9463-c3429c6140f1
```

**Comment by akiyosi** [comment]
Hi
Thanks for this issue.

What is the version of goneovim?
And, is this issue relevant to the next issue? https://github.com/akiyosi/goneovim/issues/162

**Comment by badosu** [comment]
Hello, version is 0.4.6.

Yes, disabling external messages fixes command line. Since I see you already fixed there, it should be fixed on master.

Still have issues with no status line though.

**Comment by badosu** [comment]
Fixed on 0.4.8. Thanks for goneovim!

**Comment by badosu** [comment]
I see some new issues, padding on bottom is too big and there's some rendering issues with the cursor:

![Screenshot from 2020-10-21 01-56-14](https://user-images.githubusercontent.com/347552/96675158-bc204c00-1340-11eb-97ab-1e733fe966a8.png)

**Comment by badosu** [comment]
Also, similar behavior to https://github.com/vhakulinen/gnvim/pull/95#issuecomment-566115116

![Screenshot from 2020-10-21 03-17-10](https://user-images.githubusercontent.com/347552/96680514-0a871800-134c-11eb-8230-1e0ffe289101.png)

**Comment by akiyosi** [comment]
@badosu 
Thank you for your comment.

Yes, this is currently a known problem and there is no effective solution at this time. @vhakulinen also points out that the plugin doesn't know where the external popup menu is located and the GUI doesn't know where the hint window that the plugin displays is located.
Thank you for your comment.
Yes, this is currently a known problem and there is no effective solution at this time. vhakulinen also points out that the plugin side doesn't know where the external UI-ified pop-up menu is located, and the GUI side doesn't know where the hint window that the plugin displays is located.

I also think that the neovim core functionality needs to provide some assistance.

**Comment by akiyosi** [comment]
> I see some new issues, padding on bottom is too big and there's some rendering issues with the cursor:

I will look into this.
What OS are you using?

**Comment by badosu** [comment]
I am using Manjaro, an Arch derivative, installed with the following script (changing 0.4.6 to 0.4.8): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=goneovim-bin

Neovim: 

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
```

Qt5: 5.15.0
Qt4: 4.8.7

Some other small issues, external tabline sometimes places elements in overlapping positions:

![Screenshot from 2020-10-21 16-22-29](https://user-images.githubusercontent.com/347552/96772669-de09e500-13b9-11eb-8a1f-4b2e8720575c.png)

This might be due to using [nvim-contabs](https://github.com/m00qek/nvim-contabs) which allows to switch cwd on a different tab.

**Comment by badosu** [comment]
Padding can be better exam,ined by making a visual block and redimensioning window:

![Screenshot from 2020-10-22 21-40-43](https://user-images.githubusercontent.com/347552/96943715-4c7c9f00-14af-11eb-97a4-d2923d97c455.png)
