### ISSUE TITLE
goneovim corrupts environment variable

### ISSUE THREAD

**Issue by onsails** [akiyosi/goneovim#172]
Steps to reproduce:
```bash
NODE_OPTIONS=--max-old-space-size=8048 /Applications/goneovim.app/Contents/MacOS/goneovim --clean
```
```vim
:!echo $NODE_OPTIONS
--max-old-space-size
```
In plain neovim:
```bash
NODE_OPTIONS=--max-old-space-size=8048 nvim --clean
```
```vim
:!echo $NODE_OPTIONS
--max-old-space-size=8048
```

Goneovim 0.4.8.1, macOS Catalina.

**Comment by akiyosi** [comment]
Hi :D 
Thank you for reporting the issue.
I have fixed this issue.
Please get the latest package on Github Action and try it out.
https://github.com/akiyosi/goneovim/actions/runs/326041331
(I recommend the Qt5.13.0 base.)

**Comment by onsails** [comment]
Now it works, thanks!
However, I had to do `chmod +x /Applications/goneovim.app/Contents/MacOS/goneovim` to make app launch.
