### ISSUE TITLE
GoNeovim’s config file on Windows 10

### ISSUE THREAD

**Issue by rafaelnp** [akiyosi/goneovim#176]
I am using GoNeovim 0.4.8 on Windows 10, and placed its configuration file in the following paths

*  `C:\Users\username\AppData\Local\goneovim\setting.toml` 
* `C:\Users\username\AppData\Roaming\goneovim\setting.toml`,
*  `C:\Users\username\goneovim\setting.toml`

 which are respectivelly `LOCALAPPDATA` , `APPDATA`, `HOMEPATH` enviroment variables used by other applications. 

In all cases it did not wok, I could not configure GoNeovim. Which would the right directory to place GoNeovim’s config file?

**Comment by akiyosi** [comment]
Hi
On Windows, the configuration file is as follows;

    - C:\Users\username\.goneovim\setting.toml

In MacOS and Linux, the configuration directory is under `$XDG_CONFIG_PATH\goneovim\`, but this directory path is not easy to handle in Windows, so `%HOME%\.goneovim\` is used.

**Comment by rafaelnp** [comment]
Thanks for the fast response, it is working now. I oversaw the `.` in the path, my bad.
