### ISSUE TITLE
Configure tabline height

### ISSUE THREAD

**Issue by badosu** [akiyosi/goneovim#181]
Is there a way to configure tabline height?

For some reason it is very big on my display (I'm on a 4k display FWIW):

![Screenshot from 2020-11-29 21-42-42](https://user-images.githubusercontent.com/347552/100558150-eba16d00-328b-11eb-83e4-4c6b32667e81.png)

**Comment by akiyosi** [comment]
hi :)
There is no direct setting, but the height can be adjusted by changing the font size in the external UI.

```
[Editor]
...
FontSize = 9
...
```

ref: https://github.com/akiyosi/goneovim/wiki/Usage

**Comment by badosu** [comment]
That's not possible in my case, thanks for the info!

**Comment by akiyosi** [comment]
Hmmm, sorry.
Do you want to reduce the margins in your case without changing the external font size?

**Comment by badosu** [comment]
Yeah, it's probably an issue with QT Scaling and my resolution.

I can send a PR later for some tabline tweaks if desired (set margin, do not show close button)

**Comment by akiyosi** [comment]
Okey, Thanks :)
