### ISSUE TITLE
Floating cursor doubles when typing

### ISSUE THREAD

**Issue by DONofDESTROY** [akiyosi/goneovim#184]
hey @akiyosi, 

This might be an known issue, but the cursor of the floating window doubles when typing and when minimizing and maximizing the goneovim again merges into a single cursor

## steps to replicate
open a floating terminal and type something there will be 2 cursor
minimize and maximize then the cursor merges

here is the 2 cursor problem
![image](https://user-images.githubusercontent.com/47606472/101642743-59eaea00-3a59-11eb-8146-76e9f643ecf2.png)

## other info
os; arch linux
goneovim version: latest release 
de: actually I am using awesome wm

**Comment by akiyosi** [comment]
Hi :D 
Thanks for the issue report.
I've made a commit that fixes this issue.
Could you please try it?

https://github.com/akiyosi/goneovim/actions/runs/413354721

**Comment by DONofDESTROY** [comment]
Yes working as expected
![image](https://user-images.githubusercontent.com/47606472/101882683-39877080-3bbc-11eb-9805-9937254322f5.png)

closing this issue and waiting for the next release, Thank you for maintaining such a great project

**Comment by GustavoKatel** [comment]
https://user-images.githubusercontent.com/1891977/124399175-1d7e2480-dcf0-11eb-90d1-1ef8bf224a80.mov

I'm having the same issue :/ not sure if it's related

MacOs BigSur M1
version: 0.4.11
neovim 0.5 stable

**Comment by akiyosi** [comment]
@GustavoKatel 
Hi, thanks for the comment.
Your video helps me understand better!

The terminal is shown in a float window, is there a terminal related plugin you are using in the video?

**Comment by GustavoKatel** [comment]
yes, I am using [floaterm](https://github.com/voldikss/vim-floaterm)

**Comment by akiyosi** [comment]
thx!
I have created a fix that improves this issue and I hope you can confirm that it works.
You can get the latest build from below.

https://github.com/akiyosi/goneovim/actions/runs/1019557206

**Comment by GustavoKatel** [comment]
Looks like it's fixed! thanks a lot @akiyosi

**Comment by GustavoKatel** [comment]
is this fix included in the v0.4.12 release?

**Comment by akiyosi** [comment]
Thanks for confirming it works!
This fix is not included in 0.4.12.
