### ISSUE TITLE
[Feature] Extend ExtPopupmenu in runtime

### ISSUE THREAD

**Issue by FelipeLema** [akiyosi/goneovim#189]
Hey, there

First things first: great project you have here.

Now, what I'm looking for is for a way to modify the items in ExtPopupmenu in runtime (without the need to re-compile goneovim). My ultimate goal is to append some text to the items that are currently being displayed. There may be more hidden candidates, but I'm targeting those that can be seen. In particular, I'm interested in showing the i-th position of each candidate so I can [select a candidate using a single keystroke (using digits)](https://github.com/nvim-lua/completion-nvim/issues/316) (visual description [here](https://oremacs.com/2017/12/27/company-numbers/))

Come to think of it, this may (or may not) require some kind of "ExtPopupmenu API" for goneovim, since I (the user modifying the items) need to do a non-trivial operation on the items (select viewable, add digit with position... do this every time there's a scroll or items update).

This is is just a proposal. Perhaps I'm overdoing things and this can just be added as a settings.toml option ("numberedItems = true")

**Comment by akiyosi** [comment]
hi :)
Thanks for the proposal.

I think it is possible for goneovim to provide some kind of user interface to the external popupmenu display items itself. I'm thinking about how to implement it now.

I think it would be good for the nvim core to provide some functionality for the ability to select the corresponding item by actually typing a key, as described in the issue you introduced.

**Comment by FelipeLema** [comment]
as reference, gnvim added a RPC for extended functionality ("show tooltip here") like so:
- [Handle an RPC from external UI (gnvim)](https://github.com/vhakulinen/gnvim/blob/284c3734a2da25663ce9a9258f8ac5e7f3ad2847/src/nvim_bridge/mod.rs#L1239)
- [Expose this RPC as a vimscript function](https://github.com/vhakulinen/gnvim/blob/284c3734a2da25663ce9a9258f8ac5e7f3ad2847/runtime/autoload/gnvim/cursor_tooltip.vim#L29)
- [Use this vimscript function from a plugin](https://github.com/vhakulinen/gnvim-lsp/blob/f137b5362dab3c1897c76f50f761e59411effc78/autoload/gnvim_lsp/hover.vim#L119)

**Comment by FelipeLema** [comment]
> I think it would be good for the nvim core to provide some functionality for the ability to select the corresponding item by actually typing a key, as described in the issue you introduced.

This can already be done with vimscript as I described [here](https://github.com/nvim-lua/completion-nvim/issues/316#issuecomment-760480628).

However, I'm missing the hardest part in this workflow: presenting candidates to the user _with an index next to them_

![company-numbers](https://user-images.githubusercontent.com/1232306/104848969-22782480-58c6-11eb-840c-948ed2e4f095.png)

(showing the index is the main reason I opened this issue)

**Comment by FelipeLema** [comment]
I've been thinking about this, and I'd say it'd be better to just implement the "use digit for selecting a candidate" fully on Go inside the ExtPopupmenu code.

I couldn't come up with an extensible way to do this API and I can't think of other use for it: it would be an overkill to have it)

I'm closing this issue and opening a new one just for "use digits for selecting candidate with ExtPopupmenu"
