### ISSUE TITLE
Underline and Strikethrough do not work in the statusline

### ISSUE THREAD

**Issue by AdamTillou** [akiyosi/goneovim#190]
Having underline and strikethrough text works fine in buffers, but does not work at all in the statusline. Bold and italic do work in the statusline though, for some reason.

**Comment by akiyosi** [comment]
hi :D 

It seems that I was explicitly skipping the drawing of text decorations for those areas :P
I fixed it with the following commit. I hope you will check it.
https://github.com/akiyosi/goneovim/actions/runs/491241098

**Comment by AdamTillou** [comment]
Thank you! That got it to work, although the underline/strikethrough is always white. Is there any way to make it match the color of the text?

**Comment by akiyosi** [comment]
Thanks for pointing that out. On this I found an implementation error.
I have Fixed it the following.

https://github.com/akiyosi/goneovim/actions/runs/493907552

**Comment by AdamTillou** [comment]
Thank you! It all works properly now.
