### ISSUE TITLE
select candidate by pressing a digit in ExtPopupmenu

### ISSUE THREAD

**Issue by FelipeLema** [akiyosi/goneovim#191]
Provide the following:

- Add a digit to the (10 first) candidates when presented in ExtPopupmenu
- Select a candidate (out of the 10 first) using a single digit keypress.

This would provide a feature in Emacs' company-mode in which the user can quickly select a candidate by pressing the digit that it's shown next to it.

![Emacs' "company" completion using digits](https://user-images.githubusercontent.com/1232306/104848969-22782480-58c6-11eb-840c-948ed2e4f095.png)

Related https://github.com/akiyosi/goneovim/issues/189

**Comment by akiyosi** [comment]
hi, 
I started by adding a simple option to display the numbers. 
Add the following to settings.toml

```
[Popupmenu]
ShowDigit = true
```

https://github.com/akiyosi/goneovim/actions/runs/505255446

**Comment by FelipeLema** [comment]
It looks great!

When executing this vimscript code, the behaviour is as expected (I can select-and-insert a candidate with a single keypress)

```vim
" map 0-9 to nth item
let s:shiftKeys = '!@#$%^&*('
for s:i in range(0, 9)
  exe printf('inoremap <expr> %d pumvisible() ? <sid>select_pum(%d) : %d ', s:i, s:i, s:i)
endfor

function! s:select_pum(index)
  let compInfo = complete_info()
  let idx = a:index == 0 ? 10 : a:index - 1
  let d = idx - compInfo.selected
  return repeat( d > 0 ? "\<c-n>" : "\<c-p>", abs(d)) . "\<C-y>"
endfunction
```

**Comment by FelipeLema** [comment]
I see the following is pending:
- should execute the code snippet above when `ShowDigit = true`
- I don't know if _I_ want this for occasions other than writing in insert mode (I see the digits when I press tab in command line)... can it be narrowed to insert mode?

**Comment by akiyosi** [comment]
> - should execute the code snippet above when ShowDigit = true
> - I don't know if I want this for occasions other than writing in insert mode (I see the digits when I press tab in command line)... can it be narrowed to insert mode?

I have added the above two implementations.
You can try them out below.

https://github.com/akiyosi/goneovim/actions/runs/523339281

**Comment by FelipeLema** [comment]
Behaviour of pressing keys looks OK ✔️
The digits are not being displayed in ex-command mode ✔️

However, I'm seeing that the ExtPopupmenu graphics are off (kinda compressed or something). 

I'm writing `vim.c` and I get this displayed:

![image](https://user-images.githubusercontent.com/1232306/106485807-c13c7d80-648f-11eb-8c06-4b907c300f0d.png)

When I type `:` (enter ex-command mode), then `e ./`, then <TAB> <TAB> (I'm standing in the build directory, so you can tell what's being displayed / what's supposed to be displayed)

![image](https://user-images.githubusercontent.com/1232306/106486313-44f66a00-6490-11eb-9157-d99b66891d5c.png)

**Comment by akiyosi** [comment]
Hi,
Could you please check if this behavior can be reproduced in the latest version?
https://github.com/akiyosi/goneovim/actions/runs/528150007

**Comment by FelipeLema** [comment]
Looks ok now.

Thank you for work on this. I'm very grateful.

**Comment by akiyosi** [comment]
Closed.
