### ISSUE TITLE
Is it possible to set window gaps?

### ISSUE THREAD

**Issue by hrqmonteiro** [akiyosi/goneovim#192]
This is on goneovim:
![2021-01-27_12-29](https://user-images.githubusercontent.com/17055027/106013561-78ae4a00-60b4-11eb-84ac-d5eeef99f1a2.png)

On my regular terminal window:
![2021-01-27_12-30](https://user-images.githubusercontent.com/17055027/106013732-a6938e80-60b4-11eb-9b9a-df463c2f78f9.png)

I mean like those you set on Linux terminals, like alacritty, kitty, termite? I used this on my regular Nvim and i wondered if this is possible here? My statusline and the other stuff are far to close to the borders of the window

Just asking.

**Comment by akiyosi** [comment]
Hi :) 
I have added an option to specify window gap. 

https://github.com/akiyosi/goneovim/actions/runs/518529762

By specifying the following option `Gap`, you can create wIndow gaps on the left and right.

~/.config/goneovim/settings.toml
```
[Editor]
Gap = 5
...
```

**Comment by hrqmonteiro** [comment]
Awesome, man! Thanks for that!

I'm actually using it as my daily driver rn, the Minimap and Markdown Preview won it for me.

The only thing that would be nice to do is that is one could set the default statusline as the external statusline (like, i have my own built statusline, and would be nice to have it fit on the entire screen like the ext statusline), but i guess if i learn Go maybe i can edit the default one to make it like my own, right? Too bad i don't know it right now lol

But awesome, anyways, as a whole.

**Comment by hrqmonteiro** [comment]
@akiyosi this may be a dumb question, but how do i download the binary from the Actions page?

I navigate through all the tabs but couldn't figure it out..

**Comment by akiyosi** [comment]
@hrqmonteiro 

> The only thing that would be nice to do is that is one could set the default statusline as the external statusline (like, i have my own built statusline, and would be nice to have it fit on the entire screen like the ext statusline), but i guess if i learn Go maybe i can edit the default one to make it like my own, right? Too bad i don't know it right now lol

Yes, I think you can customize Goneovim yourself to make the external status line even cooler.

> this may be a dumb question, but how do i download the binary from the Actions page?
> I navigate through all the tabs but couldn't figure it out..

The binaries built with Github Actions can be found at the bottom of each build page.
If you are logged in to Github, you should be able to DL them.

<img width="1183" alt="2021-01-30 15 14 38" src="https://user-images.githubusercontent.com/8478977/106349080-44ce6100-630e-11eb-8b63-dd971e6a542e.png">
