### ISSUE TITLE
How to change path to init.vim?

### ISSUE THREAD

**Issue by sprainbrains** [akiyosi/goneovim#20]
I want to use a non-standard init.vim file. How can I force govim to use another file?

**Comment by akiyosi** [comment]
Hi, 
Gonvim does not care about `init.vim`.
It is a setting on neovim side, and neovim detects `init.vim` under `$XDG_CONFIG_PATH`.

**Comment by sprainbrains** [comment]
> 
> 
> Hi,
> Gonvim does not care about `init.vim`.
> It is a setting on neovim side, and neovim detects `init.vim` under `$XDG_CONFIG_PATH`.

I know about it.  I want to get som var which will set "-u" flag with parameter for running nvim inside gonvim.

**Comment by sprainbrains** [comment]
> 
> 
> As with neovim, Gonvim can start with another vimscript file as follows.
> 
> ```
> /path/to/gonvim -u myTestInit.vim
> ```
> 
> e.g.
> 
> ```
> /Applications/gonvim.app/Contents/MacOS/gonvim -u NONE
> ```

I git it. Thanks! It helped me.

And last question. Where 
And other question: where can I find more information about all setting for gonvim status line?

**Comment by akiyosi** [comment]
Sorry, gonvim's starusline item is hard-coded now.
So now the following are all of the settings related to the status line.

```
[Statusline]
Visible = true
# textLabel / icon / background / none
ModeIndicatorType = "textLabel"
# Color setting per vim-modes, if you want to change
NormalModeColor = "#3cabeb"
CommandModeColor = "#5285b8"
InsertModeColor = "#2abcb4"
ReplaceModeColor = "#ff8c0a"
VisualModeColor = "#9932cc"
TerminalModeColor = "#778899"
```

In the future we plan to add the settings for each item.🙂
