### ISSUE TITLE
want open file with tab in macOS

### ISSUE THREAD

**Issue by alswl** [akiyosi/goneovim#203]
OS: macOS 11.2.3 (20D91)

goneovim version: v0.4.11

Current: when I using `open -a goneovim foo.md`, the foo.md wiil opened and replaced current that I'm editing(saved).

Want: when I open file, goneovim will open file with `tabe`.

**Comment by akiyosi** [comment]
Hi :D 
Added an option for this issue.
https://github.com/akiyosi/goneovim/actions/runs/679561026

You can specify the command to open the file as follows.

```
[Editor]
FileOpenCmd = ":tabe"
```

**Comment by alswl** [comment]
@akiyosi 
Awesome! it works for me.
