### ISSUE TITLE
0.4.11: no indentation lines and some display problems.

### ISSUE THREAD

**Issue by antsn** [akiyosi/goneovim#204]
1) I can't enable indent guide for `goneovim`. It's already has `IndentGuide = true` in the config file.
2) for Perl or Python scripts (etc, `goneovim` doesn't have problem with C++ or Go) black texts are displayed in black background:
![Screenshot_20210328_073506](https://user-images.githubusercontent.com/22258109/112738911-b1c24800-8f99-11eb-8f4b-8bb283636f02.png)
If I resize the window:
![Screenshot_20210328_073533](https://user-images.githubusercontent.com/22258109/112738917-c8689f00-8f99-11eb-857b-49ed58786cae.png)
Here how `neovim-qt` render the same file:
![Screenshot_20210328_073332](https://user-images.githubusercontent.com/22258109/112738930-e6360400-8f99-11eb-815e-903df058eff3.png)

I use `colorscheme peachpuff` in neovim `init.vim`.

**Comment by akiyosi** [comment]
Hi, thank you for this report :)

Hmmm, very strange and interesting problem.
Please give us the following information.

1. What is your neovim vesion?
2. Does this problem reproduce with `goneovim -u NONE --cmd "colorscheme peachpuff"`?

Also, it would be helpful if you could provide a minimal python, perl source code that reproduces this problem, although I cannot reproduce it on my environment.

**Comment by antsn** [comment]
1) My `nvim` version 0.4.4
2) It does not happen with `goneovim -u NONE --cmd "colorscheme peachpuff"`
3) The result is the same with any perl or python codes I tried.

Here is a example of perl file:
[test.zip](https://github.com/akiyosi/goneovim/files/6216869/test.zip)

**Comment by akiyosi** [comment]
@antsn 
thx.

From the information in 2., it looks like there may be something that is affecting your init.vim settings. 
Could you please share the contents of your init.vim as much as you can disclose? 
Or, could you identify and share the problem in your init.vim on your end?

**Comment by antsn** [comment]
It seems that only `colorscheme` option is the cause of this problem (I tested with `init.vim` with only `colorscheme` line), and only with colorscheme with **light background**, for example `morning`, `peachpuff`, `shine`, .....

**Comment by akiyosi** [comment]
Thanks for the confirmation.

I'll looking into this issue.
But it is a bit strange that the problem only occurs with certain file types such as python and perl if it depends only on the `colorscheme` configuration. I was expecting some special configuration about python or perl to be involved.

**Comment by akiyosi** [comment]
Hmmm, I have not been able to reproduce this issue.
Could you please give me some additional information?

* What is your OS?
* What are the detailed steps when the problem occurs? 
  For example, specifying the file path directly as an argument to goneovim from the command line, or opening the file after starting the goneovim application.

I also created a debug binary to see how the data is stored inside the application when this problem is happening.

https://github.com/akiyosi/goneovim/actions/runs/715811413

If you could reproduce the problem with this binary, could you please send me the debug log? (Or gist is fine.)
The debug log will be generated in the current directory by specifying `--debug` as the argument as the following.

```
/path/to/goneovim --debug
```

**Comment by akiyosi** [comment]
I have updated the binary for debugging, please try the following:
https://github.com/akiyosi/goneovim/actions/runs/716091225

**Comment by antsn** [comment]
* I use Mageia 8, KDE5
* I open file by:
  ``goneovim $path_to_file``
[debug.log.zip](https://github.com/akiyosi/goneovim/files/6255135/debug.log.zip)

**Comment by akiyosi** [comment]
Hi,
Thanks for the detailed info!
I was able to successfully reproduce this issue and fixed the problem 🚀 
Could you please test in your environment that the problem is fixed with the following latest binary?
https://github.com/akiyosi/goneovim/actions/runs/767319393

**Comment by antsn** [comment]
Thanks for your hard work! The background color bug is fixed. :man_dancing: 

About 'no identation lines' bug, should this issue be closed and I open new one!?

**Comment by akiyosi** [comment]
> About 'no identation lines' bug, should this issue be closed and I open new one!?

Sorry for the late reply.
It could be that the GUI frontend is failing to get the value of `ts` the first time.
If you go back and forth between those two buffers after splitting the window, do you see the indentation guide?

**Comment by antsn** [comment]
It seems that has no effect.

```
$goneovim file1.pl

:e file2.pl
:bn
:bp
```

**Comment by akiyosi** [comment]
I have included a minor fix in v0.4.12 that may be related to this issue.
Does v0.4.12 reproduce this issue?

**Comment by antsn** [comment]
This bug still occurs!

* neovim 0.5.0
* cleaned neovim setup (emptied configuration file)
* `setting.toml` has only option `IndentGuide = true`

**Comment by akiyosi** [comment]
@antsn 
Sorry for late reply!
What is the whole content of setting.toml?
A minimal indentation guide setting should look like this;

```
[Editor]
IndentGuide = true
```

**Comment by antsn** [comment]
Ah, it works, thanks!
My configuration file was like:
`IndentGuide = true`

But, an (old) problem appears, as I reported here:
https://github.com/akiyosi/goneovim/issues/124#issuecomment-640159447

> Still has problem with space as indentation character (as you can see with the original.cc in my example.zip in the third post).
> If the file is indented with 3 spaces, and tab's length is 4 then indent guides are only displayed for blocks indented by `k * 3 * 4` spaces.
> It seems that goneovim recognize indentation by tab instead of spaces.

Also, it seems, still has problem with python code as I quick check (no indentation line for the first column):
![Screenshot_20210725_042250](https://user-images.githubusercontent.com/22258109/126881422-0ea4bf6f-db5a-4842-85da-8ab87e5a82fb.png)
[ez_setup.py.zip](https://github.com/akiyosi/goneovim/files/6873076/ez_setup.py.zip)

**Comment by akiyosi** [comment]
@antsn 
The indentation guide in goneovim is drawn based on the value of `ts`. What is the value of `ts` (`echo &ts`) when the problem is happening? 

Also, if you change `ts` (`set ts=4`), does the situation change?

**Comment by antsn** [comment]
My tab-stop is 4.
```
echo &ts
4
```
May I ask a question, I thought that this problem was [fixed perfectly](https://github.com/akiyosi/goneovim/issues/124#issuecomment-641738498), so why it was changed later?

**Comment by akiyosi** [comment]
@antsn 
Thanks for the report.
It seems that this problem was not completely fixed before.
I think I have fixed it, so could you please check the behavior with the latest build below.

https://github.com/akiyosi/goneovim/actions/runs/1127072229

**Comment by antsn** [comment]
Thank you for your hard works, those problems are fixed. I think this issue can be closed!
