### ISSUE TITLE
Maximize at startup option causes goneovim crash on Windows

### ISSUE THREAD

**Issue by IceNature** [akiyosi/goneovim#206]
The command line option `--maximized` or `StartMaximizedWindow = true` option in settings.toml causes goneovim crash after startup. The window appeared but closed immediately.
I have tried to delete settings.toml and to start it with `-u NONE` option, but the problem is still here.
I am using nvim v0.4.4 downloaded from its Github release and goneovim v0.4.11 downloaded from its Github release.
My system is Windows 10 20H2 x64 19042.867
Log output with `--debug` command line option:
```
2021/04/06 14:26:22.949525 001.004 --- GONEOVIM STARTING ---
2021/04/06 14:26:22.966473 017.952 detecting home directory path
2021/04/06 14:26:22.967505 018.984 reading config
2021/04/06 14:26:22.967505 018.984 start    generating the application
2021/04/06 14:26:23.161519 212.998 finished generating the application
2021/04/06 14:26:23.161519 212.998 setting environment variable
2021/04/06 14:26:23.161519 212.998 set working directory path
2021/04/06 14:26:23.161519 212.998 initializing font
2021/04/06 14:26:23.161519 212.998 initializing svg images
2021/04/06 14:26:23.161519 212.998 initializing color palette
2021/04/06 14:26:23.162518 213.997 initializing notification UI
2021/04/06 14:26:23.162518 213.997 start    preparing the application window.
```

**Comment by akiyosi** [comment]
Hi, thanks for the report :)
I have fixed this issue.
You could try the latest binary from the following.

https://github.com/akiyosi/goneovim/actions/runs/737013749

**Comment by IceNature** [comment]
@akiyosi That fixed it. Thank you!
