### ISSUE TITLE
it is weird when open goneovim after click icon on Mac

### ISSUE THREAD

**Issue by Young1783** [akiyosi/goneovim#210]
it is normal that i open if from command line. but after i open it from icon, it show only a black screen with nothing.

ON:
Macbook air M1
<img width="804" alt="截屏2021-04-16 16 34 47" src="https://user-images.githubusercontent.com/20237189/114996874-de4eed00-9ed1-11eb-80e9-cd2fa5e78041.png">

**Comment by Young1783** [comment]
After digging, I find that after create a link from the nvim execution file to the directory "/usr/local/bin", the application can be opened. BUT some other errors happened.

**Comment by Young1783** [comment]
Finnally, i fix this by creating a link "~/.zshenv" to "~/.zshrc", since vim gui does not load zshrc.

**Comment by akiyosi** [comment]
Hi
Sorry for the late reply. And I am glad to hear that you have solved the problem.

When goneovim is launched from the application icon on MacOS, it uses a shell program defined by the `$SHELL` environment variable to set environment variables in the application that can be exported in terminal mode.  
(ref: https://github.com/akiyosi/goneovim/blob/master/editor/editor.go#L517-L545)

This process allows goneovim to call the `nvim`.
I think your solution is the correct one.
