### ISSUE TITLE
High CPU when opening Markdown files

### ISSUE THREAD

**Issue by rmagatti** [akiyosi/goneovim#212]
So I'm on the latest MacOS Big Sur release. 0.4.11
Whenever I open a markdown file this happens and CPU goes up quite high.
It keeps going that way until I kill the buffer with the markdown file.

![2021-04-18 16 13 01](https://user-images.githubusercontent.com/2881382/115162496-0ae53f00-a061-11eb-95e9-91ce2ce105c0.gif)

**Comment by akiyosi** [comment]
Hi, thanks for this report :)

Hmm, this looks like a bug in Qt.
The environment is different, but the following problems are very similar.
https://github.com/qutebrowser/qutebrowser/issues/6235

Does the environment variable LANG change the behavior, as discussed in the qutebrowser issue above?

**Comment by rmagatti** [comment]
Hm, not really, doing this `LANG="en_US.UTF-8" goneovim`, didn't change anything.

**Comment by rmagatti** [comment]
Update: latest built doesn't seem to have this issue. A few logs like these show up but they stop and CPU usage never goes up.  Closing the issue.

<img width="1108" alt="Screen Shot 2021-06-02 at 7 15 19 PM" src="https://user-images.githubusercontent.com/2881382/120571208-e0fc9780-c3d6-11eb-8fa4-a6e3b82f2094.png">
