### ISSUE TITLE
WSL2 support?

### ISSUE THREAD

**Issue by fhill2** [akiyosi/goneovim#213]
can goneovim connect to nvim instances running in WSL2 (Linux)?

**Comment by akiyosi** [comment]
Hi :)
I haven't actually tried it, but WSL2 is practically Linux, and Goneovim should be able to attach via remote port with `--ssh` argument.

```
C:\\Users\\MyApp\\goneovim\\goneovim.exe --ssh {wsl2-host}:{wslhost-ssh-portno}
```

If you can't connect or there is no response, please try the following FAQ.
https://github.com/akiyosi/goneovim/wiki/FAQ#the-application-crashes-when-attempting-to-connect-to-a-remote-nvim-using---ssh-option

**Comment by fhill2** [comment]
Thankyou @akiyosi for your reply.
This works fast using ssh over localhost connecting to a WSL2 nvim instance.

Goneovim docs mention 'nvim -u NONE' is supported. I see this is working without --ssh.

However:
`goenovim --ssh host:port -u NONE`
doesnt give nvim the -u parameter

Are we able connect to an nvim instance over ssh while also passing nvim parameters?

**Comment by akiyosi** [comment]
Hi :)

> However:
> goenovim --ssh host:port -u NONE
> doesnt give nvim the -u parameter

Thanks for pointing this out. This was an omission on my part.
I have fixed it, please try with the latest binary.

https://github.com/akiyosi/goneovim/actions/runs/780582585

**Comment by fhill2** [comment]
This is great.. Works perfect now. Thank you for such a speedy fix!
