### ISSUE TITLE
setting environment variables gets in the way of executing other (Qt) applications

### ISSUE THREAD

**Issue by FelipeLema** [akiyosi/goneovim#215]
Hey, everyone

Again, thanks for your commitment to this great piece of software: I use it on an everyday basis.

About the issue: I tried to load a Qt-based application ([krita](https://krita.org/)) and it complained that the Qt shared objects (`.so` files) are not the ones expected: their versions differ.

- [ ] `LD_LIBRARY_PATH` : replace by updating the binary's `rpath` to something like `$ORIGIN/lib`.
- [ ] `QT_PLUGIN_PATH` : use [`QCoreApplication::applicationDirPath()`](https://doc.qt.io/qt-5/deployment-plugins.html)
- [ ] `QT_AUTO_SCREEN_SCALE_FACTOR` unset before calling `nvim`? should save previous value if it was set
- [ ] `RESOURCE_NAME` should unset? is this Qt-related?

**Comment by akiyosi** [comment]
Hi, thanks for this issue reporting!

I understood that the problem is that when goneovim is started, the libraries and environment variables that other Qt applications expect are overridden by the environment variables that goneovim exports, is that correct?

**Comment by FelipeLema** [comment]
yes, that is correct

**Comment by FelipeLema** [comment]
I listed the variables as tasks and added some suggestions on how to deal with them

**Comment by akiyosi** [comment]
Thank you for the detailed information! It is very helpful.

By the way, is your environment Linux? Or is it MacOS or some other OS?

**Comment by FelipeLema** [comment]
linux. ubuntu fork

**Comment by akiyosi** [comment]
thx.
Could you please check that the following latest build solves the problem?

https://github.com/akiyosi/goneovim/actions/runs/805402536

**Comment by FelipeLema** [comment]
checked and the mentioned environment variables are gone

thank you for such a quick answer!

**Comment by akiyosi** [comment]
Thanks for confirming!
Closed.
