### ISSUE TITLE
CachedDrawing and Iosevka font

### ISSUE THREAD

**Issue by bfulop** [akiyosi/goneovim#216]
Hello,

First, I want to congratulate you for this app it's really impressive how far it has progressed since the few years ago when I last used it! 
I especially like the pixel based smooth scrolling, it just makes the app so much more enjoyable to use.

I'll be reporting a few (very small) issue I noticed on my Mac.

First, when I set
```
CachedDrawing = true
```
 **and** use the _Iosevka_ font, some visual glitches appear. In some cases it the `\/` character sequence, in other cases it's the Neovim virtual text (hexokinese plugin to show color previews) that trigger these strange displays (in the ` RegExp` declaration for example):

![BalintFulop-on-Thursday-29-04-at03PM13m12@2x](https://user-images.githubusercontent.com/1718128/116557486-c37f6e00-a8fe-11eb-8e46-c55e00f155d6.png)

However, if I select a different font, or turn off `CachedDrawing`, the text is displayed correctly:

![BalintFulop-on-Thursday-29-04-at03PM14m12@2x](https://user-images.githubusercontent.com/1718128/116557587-dabe5b80-a8fe-11eb-8676-eae288305241.png)

**Comment by bfulop** [comment]
I think it's related to the Ligatures set in Iosevka. When I turn them off in the settings the Regex line is displayed correctly.

**Comment by akiyosi** [comment]
Hello :)
I'm glad you're back.

I have been trying to reproduce the problem you reported in my environment, but I have not been able to reproduce the issue yet.
You mentioned in your additional information that ligatures are involved, how do you enable/disable the ligature feature?

Also, what version of Iosevka font are you using? I'm trying to reproduce this using 6.0.1, which I can get from;

https://github.com/be5invis/Iosevka/releases/tag/v6.0.1
* Iosevka 
* Iosevka Fixed

**Comment by bfulop** [comment]
Thanks, I downloaded and installed the _Iosevka Term_  and it seems to work perfectly!

I installed/updated Iosevka from Homebrew. It looks like the issue is with this version, and so I can close this issue.
