### ISSUE TITLE
Smooth scrolling jumps after `zz`

### ISSUE THREAD

**Issue by bfulop** [akiyosi/goneovim#217]
Hello,

In general, smooth scrolling works really well and it makes a big difference for me in the everyday usability of neovim.

I noticed a small glitch: 

1. do `zt` to scroll the cursor to the top of the page
2. do `zz` to center the line on the page
3. either enter _insert mode_ **or** just scroll one line:
4. the whole page will "jump" to a previous position and jump back immediately 

Here's a short video to demonstrate:

https://user-images.githubusercontent.com/1718128/116559481-cda26c00-a900-11eb-8f2a-bdf1b1fb7cbc.mov

**Comment by bfulop** [comment]
Here's another video (slowed down by 10x) of a similar issue. I'm just switching between buffers by `<c-^>` and so I wouldn't expect any scrolling happening in the window. Instead, there's some scrolling, plus the bottom part of the buffer is not replaced at the same moment as the top part?


https://user-images.githubusercontent.com/1718128/116672077-07777f00-a9a2-11eb-9cf8-d0a80f37e173.mov

**Comment by akiyosi** [comment]
Hi, Thanks for the report.
I have created a fix that improves this problem.
Could you please check the following build?

https://github.com/akiyosi/goneovim/actions/runs/810176004

**Comment by bfulop** [comment]
Hello,

Thank you so much for working on this issue! 
I'm really impressed by the smoothness of Goneovim! This is the strange scrolling effect is the only major issue I have in my daily work with the app.

I'm using the `5.15.2` QT version.

Unfortunately the scrolling issue is still present. I created another recording, slowed down by 4✕ to better illustrate what's happening. (Sorry for long delay between the actions in the video)

In the video, I'm doing `zb` → `zz` → `zz` : the buffer is scrolled. It would the same if I would do `<c-u>`, the buffer would first do a jump/scroll.

Then, I'm just doing `[b` (buffnext) to switching between buffers and again they are being scrolled unnecessarily.

And it looks there's also an issue with the gutter/numbers while scrolling. This is less an issue for me, I only turned on the line numbers for the demo video.



https://user-images.githubusercontent.com/1718128/117029484-ff4f7480-acfe-11eb-86b6-5e23a8e8f25a.mov

**Comment by bfulop** [comment]
I just downloaded the [last available version](https://github.com/akiyosi/goneovim/actions/runs/810305002#artifacts) from the GitHub Actions.

Some more observations:

If I do `zz` → `zz` (buffer needlessly scrolls) → `<c-u>` the buffer will *not* do the extra scrolling ✔︎ (as expected)

If in `buffer A` I'm on line `#26` and on `buffer B` on line `#28`: when doing _buffnext_ → Goneovim will scroll two lines 

If the difference is more than two lines, it will scroll even more. I think when switching buffers there should not be any scrolling happening (since the whole buffer is replaced).

**Comment by bfulop** [comment]
One issue that seems to be resolved:

when I do `zz` → `c-y` the buffer does *not* jump. But it does when I do `c-e` or just `$`

**Comment by akiyosi** [comment]
I made a fix for the zz command problem.
Could you please try it?

https://github.com/akiyosi/goneovim/actions/runs/812101082

I'm also trying to fix the problem with switching buffers.

**Comment by bfulop** [comment]
Thanks, it's working perfectly now! (for the `zz` case)! 👏 

Not strictly related, but I noticed that this setting in my `init.vim`:

```
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
```

makes the scrolling _by line_ a lot more "jaggy" (less smooth). I've disabled it for now in, I don't used folds that much. Let me know if I should create a new issue for this.

**Comment by bfulop** [comment]
Hello @akiyosi,

Thank you for working on the smooth scrolling, it's already great in most cases.

One strange case I noticed (using the very latest version from the Actions build):

Let's say my window shows 40 lines. If I go to the last line of the buffer and either do `zz` or `20<c-e>` (scroll **more than** 20 lines) Goneovim would do a small jump just after it finished scrolling.
However, if I only scroll 19 lines, it's very smooth without a jump. And this only happens when I'm at the last line of the document.

**Comment by akiyosi** [comment]
@bfulop 
Hi, Have you actually tried the latest binary the following?
This latest binary improves the behavior on buffers containing folded lines.

https://github.com/akiyosi/goneovim/actions/runs/817370420

> One strange case I noticed (using the very latest version from the Actions build):
> 
> Let's say my window shows 40 lines. If I go to the last line of the buffer and either do zz or 20<c-e> (scroll more than 20 lines) Goneovim would do a small jump just after it finished scrolling.
> However, if I only scroll 19 lines, it's very smooth without a jump. And this only happens when I'm at the last line of the document.

Thanks for the report.
I can't reproduce this in my environment. 
Maybe the plugin you are using is affecting it. `goneovim -u NONE` will reproduce it?

**Comment by bfulop** [comment]
Hello,

I downloaded the latest version (_Suppress unnecessary smooth scrolling during keyword search_), removed my `init.vim` file and added `-u NONE` flag for the startup.

It's still happening for me.

I have to go to the end of the buffer (`G`), then do `zb`. Then when I do `zz` there's a slight jump after the scroll. However, if I do `zb` then `<c-e>` (just one line) and then do `zz` I don't have this jump and the scroll is perfectly smooth.

**Comment by akiyosi** [comment]
Thank you!
I was able to reproduce the problem. It was affected by an incomplete implementation of the handling process for wrapped lines.

Please try the fixed build.
https://github.com/akiyosi/goneovim/actions/runs/822313359

**Comment by bfulop** [comment]
Thank you it is **perfect** now!

I just love how smooth it is and the easing of the animation! It makes a big difference. The app feels much more performant with these smooth movements.
