### ISSUE TITLE
More Iosevka display issues

### ISSUE THREAD

**Issue by bfulop** [akiyosi/goneovim#218]
It's a pity that the Iosevka font has so many issues, because I cannot imagine using an editor without it! 😅 

For my taste, the weight of the text rendered in the editor is a bit too heavy, I would prefer it the text were a bit lighter (e.g. as rendered in Kitty/Neovim).

I set the same Iosevka font for the GUI in goneovim and here it looks like it's picking up the  _Thin_ variant of the font.

![BalintFulop-on-Thursday-29-04-at03PM43m27@2x](https://user-images.githubusercontent.com/1718128/116561849-f7f52900-a902-11eb-9454-4c248152e8d3.png)
 

It's a not a huge issue, and it looks much better with for example the JuliaMono font:

![BalintFulop-on-Thursday-29-04-at03PM46m51@2x](https://user-images.githubusercontent.com/1718128/116561987-1529f780-a903-11eb-966b-092dcb67ea6b.png)

**Comment by akiyosi** [comment]
Hmm, I do not intentionally use heavy weights, but there may be some differences between environments and fonts.

By the way, if your installed font set includes fonts with light weights, you can set the light weight ones by doing the following.

```
set guifont= Iosevka:h14:l
```

In general, if a font set contains multiple weights, you can enable them as follows:

```
set guifont=Iosevka:h11:t
set guifont=Iosevka:h11:el
set guifont=Iosevka:h11:l
set guifont=Iosevka:h11:n
set guifont=Iosevka:h11:db
set guifont=Iosevka:h11:b
set guifont=Iosevka:h11:eb
```

**Comment by bfulop** [comment]
Yay, thanks, this is really nice! The editor is looking great now!

**Comment by bfulop** [comment]
Just one question:
I've been able to use the _Light_ version with the `:l` flag. 
It looks like Goneovim uses the _Medium_ weight by default. There's also the _Regular_ weight just between _Light_ and _Medium_, which would be the perfect variant.
Is there a way to select this? I tried different flags `:r` or `:m` but didn't see any difference.
