### ISSUE TITLE
Question: how to launch from the command line?

### ISSUE THREAD

**Issue by bfulop** [akiyosi/goneovim#219]
I want to launch Gonevim from the [command line](https://github.com/akiyosi/goneovim/wiki/Usage#command-line-if) to pass the `--nvim` executable path.

The best I could come up with is:

```
/Applications/goneovim.app/Contents/MacOS/goneovim --nvim=$HOME/Downloads/nvim-osx64/bin/nvim
```

How can one create the command line executable ? I guess this is a general question, not related to Goneovim.

**Comment by akiyosi** [comment]
What you expect is that you want to have a MacOS .app application with built-in command line arguments?
I don't know much about it, but I think it could be done using Applescript or something similar. 

Or there might be an idea to make the default startup arguments configurable in the Goneovim configuration file.

**Comment by bfulop** [comment]
Sorry, my question is **much more** beginner-level: how can I "install" `goneovim` for the terminal to open Goneovim ? 
Currently I get this (macOS) :

```
/Applications🔒 
❯ goneovim
zsh: command not found: goneovim
```

**Comment by akiyosi** [comment]
Ah, that looks like it can be solved by setting the following in bash_profile or .zprofile, etc.

```
export PATH=$PATH:/Applications/goneovim.app/Contents/MacOS
```

**Comment by bfulop** [comment]
Nice, thanks!
