### ISSUE TITLE
Smooth scrolling jumps when line is wrapped

### ISSUE THREAD

**Issue by bfulop** [akiyosi/goneovim#220]
Hello,

I noticed that when text is too long to fit the window, the smooth scrolling is behaving strangely. It looks as if the line is unwrapped, then scrolled then wrapped again. This gives the impression that part of the page is jumping (instead of scrolling smoothly).

**Comment by akiyosi** [comment]
Hi,

Yes, this is a known issue, and currently smooth scrolling of screens containing wrapped lines is not well represented.

**Comment by akiyosi** [comment]
@bfulop 
This problem has been fixed in commit 8ec23e67b2397f6cea6687d08082d385459d80fe.
The behavior can be confirmed with the following CI artifacts.

Note that it requires the latest neovim 0.9.0.

https://github.com/akiyosi/goneovim/actions/runs/4651431493

**Comment by bfulop** [comment]
Thank you @akiyosi, it's working great on my side!
