### ISSUE TITLE
Permissions denied on macOS Big Sur when downloading from GitHub Actions

### ISSUE THREAD

**Issue by bfulop** [akiyosi/goneovim#221]
Hello,

I wanted to test the latest versions from Github Actions CI on macOS Big Sur, but I get 

```
zsh: permission denied: goneovim
```

when I try to launch the application. I get the same error when trying to double click the app icon.

**Comment by bfulop** [comment]
I also tried installing from source, but got stuck at this step:

https://github.com/therecipe/qt/issues/939

I have no idea how to _enable `QScript` in the QT Installer_. I have never used QT, so don't even know where to look for it.

**Comment by akiyosi** [comment]
hi,
Could you try the following?

https://github.com/akiyosi/goneovim/wiki/FAQ#if-you-cannot-open-on-macos

**Comment by bfulop** [comment]
Thanks! Stupid me. Lately I've seen many reports of _permissions denied_ on Big Sur, and thought it was something much more complicated!

This latest version already seems to resolve one issue I had in the release version:

Then scrolling one line, the cursor seemed to "lag" behind. It didn't move together with the rest of the buffer, but only after a short (~100ms) delay. There's still a slight delay before the cursor is scrolled, but it's almost not visible and certainly not distracting anymore!
