### ISSUE TITLE
[Bug] --maximized will make program exit immediately after startup

### ISSUE THREAD

**Issue by Verf** [akiyosi/goneovim#227]
**OS:** Windows 10 20H2 19042.985

**Neovim:** 
NVIM v0.5.0-dev+1353-g0a653f7ab
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-612

Features: -acl +iconv +tui

**Configs:**
No vimrc or settings.toml, all settings are kept by default.

**Description:**
The --maximized option will make program exit immediately after program startup. GIF:
![demo](https://user-images.githubusercontent.com/22053969/120418543-4e86d480-c393-11eb-8749-f989bb47628a.gif)

**Debug Log:**

> 2021/06/02 10:56:11.065299 000.998 --- GONEOVIM STARTING ---
> 2021/06/02 10:56:11.079717 015.416 detecting home directory path
> 2021/06/02 10:56:11.080242 015.941 reading config
> 2021/06/02 10:56:11.080242 015.941 start    generating the application
> 2021/06/02 10:56:11.208750 144.449 finished generating the application
> 2021/06/02 10:56:11.208750 144.449 setting environment variable
> 2021/06/02 10:56:11.208750 144.449 set working directory path
> 2021/06/02 10:56:11.208750 144.449 initializing font
> 2021/06/02 10:56:11.208750 144.449 initializing svg images
> 2021/06/02 10:56:11.208750 144.449 initializing color palette
> 2021/06/02 10:56:11.209753 145.452 initializing notification UI
> 2021/06/02 10:56:11.209753 145.452 start    preparing the application window.

**Comment by akiyosi** [comment]
Hi
Thank you for the detailed report :)

Is the version of Goneovim you are using 0.4.11? 
If so, the problem may have been fixed in the latest build. 
Could you please try the following latest build to see if it works?

https://github.com/akiyosi/goneovim/actions/runs/899695524

**Comment by Verf** [comment]
> Hi
> Thank you for the detailed report :)
> 
> Is the version of Goneovim you are using 0.4.11?
> If so, the problem may have been fixed in the latest build.
> Could you please try the following latest build to see if it works?
> 
> https://github.com/akiyosi/goneovim/actions/runs/899695524

Thanks for your reply, this problem does not exist on the latest build. But there is still a small problem. When using the --maximized parameter to full screen, the minimap will cover the status line. If you maximize manually, this problem will not occur.

Maybe this is related to the status line plugin?  I use [galaxyline](glepnir/galaxyline.nvim), and my galaxyline config is [statusline.lua](https://github.com/Verf/vimrc/blob/develop/lua/configs/statusline.lua). 

My settings.toml is:
```toml
[Editor]
FontFamily = "Sarasa Mono SC Nerd"
FontSize = 14
DisableLigatures = false
DisableImeInNormal = true
IndentGuide = false
SmoothScroll = false
[MiniMap]
Disable = false
Visible = true
[Markdown]
Disable = true
[SideBar]
Disable = true
Visible = false
```

Demo:
![demo2](https://user-images.githubusercontent.com/22053969/120583742-63319e00-c461-11eb-8b9c-b932bd0feb84.gif)

**Comment by akiyosi** [comment]
Thank you for the confirmation, the report with the GIF animation is very helpful and easy to understand :D

I was able to reproduce this issue and have fixed it.
I would be happy if you could confirm that it works with the following latest build.

https://github.com/akiyosi/goneovim/actions/runs/903103800

**Comment by Verf** [comment]
> Thank you for the confirmation, the report with the GIF animation is very helpful and easy to understand :D
> 
> I was able to reproduce this issue and have fixed it.
> I would be happy if you could confirm that it works with the following latest build.
> 
> https://github.com/akiyosi/goneovim/actions/runs/903103800

Everything works fine in the latest version, thanks again for your work!
