### ISSUE TITLE
Misplaced scrollbar using coc.nvim

### ISSUE THREAD

**Issue by iCromix** [akiyosi/goneovim#231]
I'm having an issue with the coc.nvim plugin and goneovim. I've tried using other GUIs like nvim-qt and this issue didn't appear.

When typing a function, coc.nvim displays the params and what the function does, this should have a scrollbar beside it like any other popup, but it appears floating allways at the same position.

<img src="https://i.imgur.com/6qgqWnB.png">

Something that i've noticed is that, if i resize the goneovim window, the popup **flickers aligned with the scrollbar**, as if the scrollbar _thinks_ it is beign rendered at the top of the buffer.

<img src="https://i.imgur.com/g81lRfc.gif">

This issue doesn't appear on the autocomplete, here the scrollbar is nicely placed.

<img src="https://i.imgur.com/pm3YJgt.png">

In my **settings.toml** i've only changed **BorderlessWindow**, **Extpopupmenu** to true, nothing else. I tried reinstalling coc.nvim but that didn't solve it.

Sorry if this isn't the place for this issue, maybe someone has an idea of why this is happening.
Thanks in advance!

**Comment by akiyosi** [comment]
Hi, thanks for reporting this problem!

I have investigated this issue and believe that this is not a problem with goneovim, but an issue related to the multigrid ui specification. 
I have created a PR for fixing this issue in the coc.nvim repository. See https://github.com/neoclide/coc.nvim/pull/3150

**Comment by iCromix** [comment]
Thanks a lot for taking your time looking into this, I'll wait the fix on the coc.nvim end.

Cheers!
