### ISSUE TITLE
Is there a CLI?

### ISSUE THREAD

**Issue by samrath2007** [akiyosi/goneovim#236]
It is there according to the wiki but there is none for me(I installed it via the releases page)

**Comment by akiyosi** [comment]
Hey! What's your operating system?
However, every OS has a command line interface in the executable binary; on Windows this CLI help is not displayed due to some problems, however it is valid.

**Comment by samrath2007** [comment]
I am on macOS. Where is the cli located?

**Comment by akiyosi** [comment]
Here;
/Applications/goneovim.app/Contents/MacOS/goneovim

**Comment by samrath2007** [comment]
Thank you for making this wonderful GUI. it got me back to vim!
