### ISSUE TITLE
The application "gonvim.app" cannot be opened.

### ISSUE THREAD

**Issue by khalidchawtany** [akiyosi/goneovim#24]
I finally was able to build gonvim on my machine. However, when I try to launch it I get the following message:

![screen shot 2018-12-18 at 7 16 44 pm](https://user-images.githubusercontent.com/1681606/50167178-a03d6080-02f9-11e9-85e9-fe09cd7dc1ba.png)

Running from the terminal I can see the error which I don't have any Idea about its solution :(
```
>> open -a gonvim
LSOpenURLsWithRole() failed for the application /Users/juju/Development/go/src/github.com/akiyosi/gonvim/cmd/gonvim/deploy/darwin/gonvim.app with error -10810.
```

**Comment by akiyosi** [comment]
Hi,
I have never encountered this problem.
I looked into this and seems to have the following permission problem.
Please check your system.

https://discussions.apple.com/thread/7586240

**Comment by khalidchawtany** [comment]
* Mac OS 10.14
* It does not happen in any of the released versions.

**Comment by smolck** [comment]
@khalidchawtany Is this still an issue with GoNeovim v0.4.0?

**Comment by khalidchawtany** [comment]
Sorry I gave up compiling the app myself. I always download the from the releases.
