### ISSUE TITLE
GUI not working

### ISSUE THREAD

**Issue by pixpack** [akiyosi/goneovim#240]
I'm running into an issue where goneovim starts, but the ui isn't working as expected. Did I mess something up with the installation?

System:
- Windows 10 Home
- 20H2
- 19042.1052

- Nvim 0.4.4

![GUI screenshot](https://user-images.githubusercontent.com/11791251/124140861-27eab500-da89-11eb-9f1c-81b2fbd558b1.png)

Here are the logs: [Log](https://github.com/akiyosi/goneovim/files/6748861/goneovim_ui_problem.log)

**Comment by akiyosi** [comment]
Hi :D
What is the specific UI behavior you expect?
The screenshot shows a plain screen, what problems can I see?

**Comment by pixpack** [comment]
I'm sorry. I'm new to neovim and I was expecting goneovim to be some kind of plug and play solution. So I expected my terminal to appear the same as on the example screenshots :D. I've read up more and configured it and now everything seems to be working.
I've got an issue with coc.nvim and coc-pyright though. The code completion area flickers to the top left of the window when typing.

**Comment by akiyosi** [comment]
I'm glad to see it's working!

As for the coc.nvim issue, updating Neovim to the latest version(It has just been officially released with 0.5.0) and using the latest build of Goneovim below will likely solve it.

https://github.com/akiyosi/goneovim/actions/runs/990825561

**Comment by pixpack** [comment]
Works beautifully! Thanks for the help and the great software :) I think this can be closed.
