### ISSUE TITLE
Package Request

### ISSUE THREAD

**Issue by basicfunc** [akiyosi/goneovim#251]
Hey, Dev!
Thanks for this amazing piece of software, really loved it. Can you please make it available to Void Linux.

**Comment by akiyosi** [comment]
Hi :D
Thanks for this issue report.

Just to confirm, which of the following is your request?
* Goneovim does not work well on Void Linux, so please provide a working binary.
* Please make it possible to install Goneovim with the package distribution system on Void Linux.

**Comment by basicfunc** [comment]
Hey :)
Thanks for your response.
No, actually goneovim is working flawlessly in Void Linux, I'm concerned about getting up-to-date packages. So, I request you to make goneovim available through Void Linux Package repository. It's very simple, every instruction is here [XBPS src Package Manual](https://github.com/void-linux/void-packages/blob/master/Manual.md). I tried to make one but I failed, I won't been able to recognize how all qt dependency get pulled as in other templates they're requested to install from repo itself or sometimes tarball from official website. And I never worked with Go compilation software in XBPS src :(

**Comment by akiyosi** [comment]
@basicfunc 
Hey, sorry for not replying.

I understand your request, but there are other requests for package creation for each distribution, and managing them all in this repository is a bit beyond my control.
If you look at the Github repository, you will see that there are a few scripts of this kind that have been created by volunteers, so my hope is to leave it to the volunteers who feel it is necessary.
I am willing to give advice on package scripting if necessary :)

**Comment by basicfunc** [comment]
Thanks @akiyosi.. Will contact, if help needed.
