### ISSUE TITLE
macOS build is missing version

### ISSUE THREAD

**Issue by vitorgalvao** [akiyosi/goneovim#252]
To accurately display version information, macOS apps need to have the `CFBundleVersion` and `CFBundleShortVersionString` tags in `Info.plist`.

If they’re not set during the build process, they can be added after it’s done by directly editing the `Info.plist`:

```bash
# Change these values
app_path='/PATH/TO/APP/HERE'
app_version='VERSION NUMBER HERE'

# Keep these as they are
/usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${app_version}" "${app_path}/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${app_version}" "${app_path}/Contents/Info.plist"
```

That would use the same version number for both fields. Technically they should be different (`CFBundleVersion` a machine readable string like `48657763` and `CFBundleShortVersionString` a human-centric value like `4.8.2`), but even having the same version in both fields (or even one of them) would be a major improvement.

**Comment by akiyosi** [comment]
Hi,
Thanks for the report.
I have fixed this issue. Here is the latest build that incorporates the fix for this issue.

https://github.com/akiyosi/goneovim/actions/runs/1132239800

I would appreciate it if you could check it out.

**Comment by vitorgalvao** [comment]
> I would appreciate it if you could check it out.

I’m not seeing a way to download the build to check.

**Comment by akiyosi** [comment]
You can get the latest build from the bottom of the page at the link above.

Goneovim-latest-macos-5.13.0 for macOS 10.1X
Goneovim-latest-macos-5.15.2 for macOS bigsur



<img width="1592" alt="スクリーンショット 2021-08-15 22 09 42" src="https://user-images.githubusercontent.com/8478977/129479688-49a2d015-4b97-4a9e-8865-d980ac6b13ca.png">

**Comment by vitorgalvao** [comment]
> You can get the latest build from the bottom of the page at the link above.

Clearly I didn’t scroll down enough!

Confirmed the version is correctly applied in both macOS versions. Thank you for the fast turnaround!

Closing now, as I’m guessing this will be live on the next release.
