### ISSUE TITLE
Possibility to open new window in MacOS

### ISSUE THREAD

**Issue by vshturman** [akiyosi/goneovim#255]
Hello, thanks for goneovim development, this is really great Neovim GUI!

Is it possible to add possibility for MacOS to open new goneovim window from dock by right click (like it works for iterm2, sublime text, etc)?
I can launch new application instance using command like "open -na 'goneovim'", but will be good to have this possibility out-from-the-box.

Thanks!

**Comment by akiyosi** [comment]
Hi :)
It is possible to implement this.
I've implemented it in my build environment before, but I didn't find it useful because the menu only appeared when the application was launched.
Would it be useful, for example, to be able to set startup options in the configuration?

**Comment by vshturman** [comment]
Oh, sounds good.

**Comment by tikhon-kolomytsin-clearscale** [comment]
Looks great, that's all I wanted!

Thank you.

**Comment by akiyosi** [comment]
@vshturman @tikhon-kolomytsin-clearscale 
You're different people, aren't you?

**Comment by vshturman** [comment]
The same. Sorry, forgot to switch accounts)
