### ISSUE TITLE
set guifont syntax limitation

### ISSUE THREAD

**Issue by igor37** [akiyosi/goneovim#258]
I don't know to what degree `set guifont` is intended to be supported. But I just wanted to report that goneovim seemingly does not support the following rule (see `:h guifont`):

> - A '_' can be used in the place of a space, so you don't need to use
>   backslashes to escape the spaces.
> - Examples: 
>	    :set guifont=courier_new:h12:w5:b:cRUSSIAN
>	    :set guifont=Andale_Mono:h7.5:w4.5

So basically setting a font only works if spaces in the font name are escaped with a backslash, replacing the spaces with underscores does not. Good enough for me, but I didn't know that and was wondering for quite a while why it only recognizes the font size.

**Comment by akiyosi** [comment]
Hi,
Thanks for the issue report.
I have fixed this issue. You could see it in the latest build below.

https://github.com/akiyosi/goneovim/actions/runs/1198632122
