### ISSUE TITLE
Refresh rate

### ISSUE THREAD

**Issue by xuliefeng** [akiyosi/goneovim#262]
hi, can I set the refresh rate? I feel very slow at the moment

**Comment by akiyosi** [comment]
@xuliefeng 
Hi,
Thank you for the issue report.
goneovim does not specify the refresh rate explicitly, it refreshes only as needed. 
This means that the actual rate will depend on the machine power.

Could you please provide the following additional information to clarify your issue?
* Your OS and its version
* Your goneovim settings (if you  have configured`settings.toml` )

**Comment by xuliefeng** [comment]
My system is osx 10.15.7.

is my settings

[Editor]
BorderlessWindow=true
Transparent=0.9
StartMaximizedWindow=true
FontFamily="Hack Nerd Font"
FontSize=14
DisableImeInNormal=true
IndentGuide=false
ExtMessages=false
DesktopNotifications=false

[MiniMap]
Disable=true

[Cursor]
SmoothMove=false

Sorry, the description may be wrong. What I mean by slow refers to the sluggishness when moving, compared with the terminal (iterm2)

**Comment by akiyosi** [comment]
@xuliefeng 
Hmmm, what is the specific action that you feel is slow? For example, is it scrolling speed?

Also, changing the following may help a little.

```
[Editor]
BorderlessWindow=false
Transparent=1.0
```

**Comment by xuliefeng** [comment]
@akiyosi 
your are right . After the modification, it is very smooth.

thanks
