### ISSUE TITLE
Fcitx5 input method support

### ISSUE THREAD

**Issue by zeertzjq** [akiyosi/goneovim#266]
I cannot get Fcitx5 input method to work in Goneovim under either KDE Plasma X11 or KDE Plasma Wayland, whether I set `QT_IM_MODULE` to `fcitx` or `ibus` (Fcitx5 provides both a Fcitx and an IBus frontend). The toggling keybinding doesn't do anything, and using "Share Input State: All" doesn't work either.

Neovim Qt doesn't mention "Fcitx" anywhere in its code, but it supports Fcitx5, so maybe something more general is required to support Fcitx5?

**Comment by akiyosi** [comment]
Hi,
I'm sorry for the late reply.
I have successfully reproduced this issue and am investigating.
I'll let you know if I find anything.

**Comment by akiyosi** [comment]
@zeertzjq 
Umm, I don't know the exact cause, but in my environment, I created a binary for archlinux, and I was able to confirm that imput method works correctly.
Could you please check if the binary for archlinux in the following CI build artifacts solves this problem?

https://github.com/akiyosi/goneovim/actions/runs/1263998155

<img width="885" alt="2021-09-23 11 58 16" src="https://user-images.githubusercontent.com/8478977/134448942-7ff5b4f9-0a6e-4f44-9aa3-b95ef3e50082.png">

**Comment by zeertzjq** [comment]
I just tested that and it worked.

**Comment by akiyosi** [comment]
@zeertzjq 
I'm glad to see that it worked.
Maybe it is affected by whether it is based on the system Qt library or the bundled library, but it seems to have worked, so I'd like to close it.
