### ISSUE TITLE
crash when mouse click outside of editor area

### ISSUE THREAD

**Issue by lukeng** [akiyosi/goneovim#275]
OS version: Windows 10 20H2, build 19042.1237
nvim version: NVIM v0.5.0-dev+1357-g192f89ea1
goneovim version: v0.4.12-70-g961dde1

Step to reproduce:
1. Remove / rename the ~/.goneovim/settings.toml
2. Launch `goneovim.exe -u NONE`
3. Click on the statusline

Tried with 0.4.12, which has no issue.
I tried with commit d3e7acc, but found that mouse click outside of editor area has no effect, e.g. cannot change position of cursor in command line.

**Comment by lukeng** [comment]
@akiyosi thanks for the quick fix!

It partially fixed the issue:
- Goneovim did not crash.
- When I click on the tabline (created by `:tabe`), I can change the tab (which in previous commit d3e7acc cannot).
- When I in command mode, I still cannot change the position of cursor.

**Comment by lukeng** [comment]
Thanks for the fix!
Played with build 109bd63, I confirm the mouse can change the cursor position in command mode.

But sadly I found another way to crash goneovim, and happens in both commit 109bd63 and the presvious commit e59ef7d:
1. Launch `goneovim.exe -u NONE`
2. Split the empty buffer (`<C-W><C-S>`)
3. Repeatly click on upper window and lower window by mouse
4. It will crash after some clicks.

I tried with vsplit, but cannot reproduce the issue.

**Comment by lukeng** [comment]
@akiyosi 
I have tried with neovim 0.5.1 stable release, but goneovim still crashes in the both commit 961dde1 and a5cfe78.
May I know which Neovim version should I try?

**Comment by lukeng** [comment]
Thanks!
I tried with `NVIM v0.6.0-dev+493-g035d82e0d` and goneovim did not crash in split windows.

**Comment by akiyosi** [comment]
Closed.
