### ISSUE TITLE
IndentGuides showing in dasboard

### ISSUE THREAD

**Issue by MordechaiHadad** [akiyosi/goneovim#276]
The dashboard i use is called [alpha-nvim](https://github.com/goolord/alpha-nvim) and normally it looks like this
![](https://p0rn.pro/TheRelievedAndFadedHill)
But when i open a [telescope](https://github.com/nvim-telescope/telescope.nvim) window the indent guides show up
![](https://p0rn.pro/ASynonymousAndHomelyGroup)
Is there a way to fix this?

**Comment by akiyosi** [comment]
@MordechaiHadad 
Thanks for additional info.

In my environment, the above CI build does not reproduce the problem.
So I created the following debug build.
If you can reproduce the problem by running goneovim from the command line with the `--debug` option, could you please share the generated `debug.log` on gist?

https://github.com/akiyosi/goneovim/actions/runs/1400049078

**Comment by MordechaiHadad** [comment]
> 
> 
> @MordechaiHadad Thanks for additional info.
> 
> In my environment, the above CI build does not reproduce the problem. So I created the following debug build. If you can reproduce the problem by running goneovim from the command line with the `--debug` option, could you please share the generated `debug.log` on gist?
> 
> https://github.com/akiyosi/goneovim/actions/runs/1400049078

Downloaded the CI build the previous issue doesn't happen.
Should I close the commit?

**Comment by akiyosi** [comment]
Thanks for the confirmation and the close!
