### ISSUE TITLE
Floating window hides multiline messages in Goneovim but not in terminal or other GUIs

### ISSUE THREAD

**Issue by Melkster** [akiyosi/goneovim#278]
I tried using the plugin [floatline.nvim](https://github.com/windwp/floatline.nvim/) which uses a floating window to create one single global statusline. However, I noticed that with the plugin active it covers the last line of multiline printouts. However, I only have this problem in Goneovim, and not in [Neovim-qt](https://github.com/equalsraf/neovim-qt/) or or in my terminal emulator, or [nvui](https://github.com/rohit-px2/nvui/) according to [this comment](https://github.com/windwp/floatline.nvim/issues/10#issuecomment-939304216), leading me to suspect that this is a problem with how Goneovim handles floating windows.

## To reproduce

Here's a minimal `init.vim` to reproduce the error:

```vim
call plug#begin('~/.config/nvim/packages/')
Plug 'windwp/floatline.nvim'
call plug#end()

lua << EOF
require('floatline').setup()
EOF
```

To test it:

1. `> goneovim -u path/to/file/above`
2. `:echo 'foo' | echo 'bar'`
3. Notice that `'bar'` gets hidden by the statusline (a floating window)

Now try the same thing in your terminal emulator (or any other Neovim GUI):

1. `> nvim -u path/to/file/above`
2. `:echo 'foo' | echo 'bar'`
3. `'bar'` does not get hidden

**Comment by Melkster** [comment]
@akiyosi I'm probably doing something wrong because I've downloaded and unpacked the `Goneovim-latest-linux_archlinux-5.15.1` artifact, but when I run the binary but I get the error:
`error while loading shared libraries: libQt5WebChannel.so.5: cannot open shared object file: No such file or directory`

**Comment by akiyosi** [comment]
@Melkster 
Sorry for not being able to document it.
It looks like you tried the package for archlinux, which assumes that you have qt5 libraries on your system (maybe, as I understand it).
Do you have any qt5 packages already installed on your system?

Also, will it work with the normal package Goneovim-latest-linux-5.14.1?

**Comment by akiyosi** [comment]
@Melkster 
Is there any new situation?

**Comment by Melkster** [comment]
@akiyosi Sorry I forgot to respond.

I got it to work by using the normal package `Goneovim-latest-linux-5.14.1` and I it seems to have fixed the issue. Thank you! :)

**Comment by akiyosi** [comment]
@Melkster 
Thank you for confirming!
Closed.
