### ISSUE TITLE
[Question] Difference between linux builds

### ISSUE THREAD

**Issue by MuhammedZakir** [akiyosi/goneovim#281]
Is there any difference between `Goneovim-latest-linux-<ver>` and `Goneovim-latest-linux_archlinux-<ver>`? Latter archive only contains the `goneovim` executable. So does that mean it uses system dependencies? WIll I have to install dependencies myselft (unlike the former archive which bundles them)?

**Comment by akiyosi** [comment]
@MuhammedZakir 
Hi,

Yes, as you understand, the package for archlinux assumes that you have the qt5 module installed on your system. However, I don't know what the actual differences are either.
goneovim uses the qt5 Go binding (https://github.com/therecipe/qt), and the project publishes a build container in it. goneovim has not used containers to build until recently, but there was a problem with the input method in archlinux (https://github.com/akiyosi/goneovim/issues/266) and that was useful to solve. Actually, I don't know why it solves the problem.

**Comment by MuhammedZakir** [comment]
I see. Thanks!

> goneovim has not used containers to build until recently, but there was a problem with the input method in archlinux (#266) and that was useful to solve. Actually, I don't know why it solves the problem.

Have you checked if the arch linux build links against any additional objects/libraries?
