### ISSUE TITLE
goneovim is support char space?

### ISSUE THREAD

**Issue by guolimin1995** [akiyosi/goneovim#288]
settings support linespace.
is support char space?
like iTerm2 font set vi and n/n to change char width.

**Comment by guolimin1995** [comment]
or like vscode: editor.letterSpacing

**Comment by akiyosi** [comment]
Hi :) 

Currently, letter spacing was not supported, but I implemented it as a trial.
The package can be obtained from Please let us know how you like it.

https://github.com/akiyosi/goneovim/actions/runs/1521564033

Note that
* It can be configured as in GonvimLetterSpacing 1.
* If letter spacing is enabled, ligature will be disabled.

**Comment by guolimin1995** [comment]
> Hi :)
> 
> Currently, letter spacing was not supported, but I implemented it as a trial. The package can be obtained from Please let us know how you like it.
> 
> https://github.com/akiyosi/goneovim/actions/runs/1521564033
> 
> Note that
> 
> * It can be configured as in GonvimLetterSpacing 1.
> * If letter spacing is enabled, ligature will be disabled.

thanks for you nice work!
I'll try it

**Comment by guolimin1995** [comment]
> > Hi :)
> > Currently, letter spacing was not supported, but I implemented it as a trial. The package can be obtained from Please let us know how you like it.
> > https://github.com/akiyosi/goneovim/actions/runs/1521564033
> > Note that
> > 
> > * It can be configured as in GonvimLetterSpacing 1.
> > * If letter spacing is enabled, ligature will be disabled.
> 
> thanks for you nice work! I'll try it

i set LetterSpacing = 1 in gonvim setting.toml
or set let g:gonvim_letter_spacing = 10 in my neovim init.vim config
or set GonvimLetterSpacing 1 in init.vim
it's not working for me.

**Comment by akiyosi** [comment]
Sorry for the lack of information.
`GonvimLetterSpacing` is a command. However, due to the timing of the definition of this command, it may not be recognized even if it is written in `init.vim`.
Anyway, I think it will be work if you run like `:GonvimLetterSpacing 0.75` after started Goneovim. 

I'm going to consider adding some configuration items to the Toml file today.

**Comment by guolimin1995** [comment]
> Sorry for the lack of information. `GonvimLetterSpacing` is a command. However, due to the timing of the definition of this command, it may not be recognized even if it is written in `init.vim`. Anyway, I think it will be work if you run like `:GonvimLetterSpacing 0.75` after started Goneovim.
> 
> I'm going to consider adding some configuration items to the Toml file today.

very nice of you. thanks

**Comment by akiyosi** [comment]
@guolimin1995 
Some updates have been made :) 

latest binary:
https://github.com/akiyosi/goneovim/actions/runs/1535447411

doc:
https://github.com/akiyosi/goneovim/pull/292

**Comment by guolimin1995** [comment]
> @guolimin1995 
> Some updates have been made :) 
> 
> latest binary:
> https://github.com/akiyosi/goneovim/actions/runs/1535447411
> 
> doc:
> https://github.com/akiyosi/goneovim/pull/292
> 

thanks for you work
