### ISSUE TITLE
Can't change font-size on Window 10

### ISSUE THREAD

**Issue by TobiasDev** [akiyosi/goneovim#293]
Hello, 

I've been trying to change the font-size instead of Goneovim without any luck. I have the settings.toml in the right place since I can turn of the frame and all of that. But no matter how much I try to change the font-size it stays the same. 

```
FontFamily = "JetBrainsMono Nerd Font"
FontSize = 6

```

What do I need to do? 

I double checked so I'm not setting the font anywhere else.

**Comment by akiyosi** [comment]
Hi :) 

Is there any guifont setting in the neovim configuration file init.vim?
The guifont setting has priority in goneovim.

**Comment by TobiasDev** [comment]
My font is set in init.lua, but no font-size is added there. 
https://gitlab.com/tobiasdev/dot-files/-/blob/main/nvim/init.lua

Maybe that is the error. I'll try and comment it out and see.

**Comment by TobiasDev** [comment]
Sorry... my fault, I was dumb and had it set in my init.lua
