### ISSUE TITLE
Make cursor change when pressing Y or D once, like it does in Neovide?

### ISSUE THREAD

**Issue by TobiasDev** [akiyosi/goneovim#294]
Hello, 

I was wondering if it's possible to get the cursor to change when I'm "half-in" a command. E.g. I need to press "y" twice to yank something. So by the first press it becomes half-size and then when I press again it goes back to the full size. 

Would this be possible to add? I just like some visual representation when I'm not done with my key-presses yet.

**Comment by akiyosi** [comment]
Hi,
goneovim supports the `guicursor` option, which is well known in gVim, and I think it can be achieved by setting the `guicursor` appropriately.

See the help `:h guicursor` for details.

By the way, I was also trying out guicursor yesterday, but there was a bug in goneovim about guicursor, so I fixed it.
You can get the latest build that includes this fix from the following:

https://github.com/akiyosi/goneovim/actions/runs/1549827826

**Comment by akiyosi** [comment]
Closed.
