### ISSUE TITLE
Float window blocks switching focus from goneovim to other app

### ISSUE THREAD

**Issue by colinux** [akiyosi/goneovim#295]
Hi, sorry me again ! 

When a floating window is opened (by coc.nvim for instance), I can't switch focused app on macos (with ⌘-Tab or clicking on another window). I have first to close floating window.

The bug appeared from with v0.4.13. (100% sure it was ok with v0.4.12). Reproduced on Intel & M1.

Here is a small capture. It seems goneovim reclaims the focus a few milliseconds after the switch.

https://user-images.githubusercontent.com/150279/145201495-496d32e1-5ff5-47af-a349-500035761468.mp4

**Comment by akiyosi** [comment]
@colinux 
Thanks for the issue report.
A capture video of the issue would be very helpful :)

I am investigating this issue, but at this time I have not been able to reproduce the problem in my environment (Intel, MacOS 1.15, 1.14).

In the implementation, the float window and popup menu have a similar mechanism in goneovim.
So, could you please check the following?

1. Start with `goneovim -u NOEN`
2. Open a file.
3. Do `<C-x><C-n>` to display the popupmenu.

Does the same problem occur with this step?

**Comment by colinux** [comment]
Hi @akiyosi,

I don't have the issue with popupmenu like you suggested (with my config neither with `-u NONE`).
I don't know how to open a float window without any config/plugin.

But I investigated my config and found what's responsible for the bug :

```vim
set number
set relativenumber
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
```

Basically, I'm using relative numbers when vim is focused, real numbers when it's not. Removing the `augroup` block removes the bug. (It worked before, and it's working with nvim.)
Because I didn't know how to trigger float window without plugin, I still had `coc.nvim` as the only plugin enabled.

I attached a longer video, it may be easier to understand. This time I only used the cursor to show the windows switches attempts.

https://user-images.githubusercontent.com/150279/145780345-4b20f825-8948-4b1e-847f-47377865467a.mp4

**Comment by akiyosi** [comment]
@colinux 
Thanks for the additional info!

I was able to reproduce the issue and have identified the cause. It involves a focusgained event.
Please wait as I am working on a fix :D

**Comment by akiyosi** [comment]
@colinux 

It has been fixed.
Could you please try it in your environment?

https://github.com/akiyosi/goneovim/actions/runs/1583187878

**Comment by colinux** [comment]
@akiyosi  yes, I confirm you it's fixed ! Thanks :)

**Comment by akiyosi** [comment]
Thanks for confirming!
Also, thanks for the always clear issue reports.

This issue is closed.
