### ISSUE TITLE
Statusline and command area not rendering properly

### ISSUE THREAD

**Issue by ppebb** [akiyosi/goneovim#296]
Both lualine and the area where commands are typed do not reach the edge of the window.
My goneovim version is 0.4.13-1.

![image](https://user-images.githubusercontent.com/36719558/145743138-cb2d781f-e090-4c4a-9140-698a1cf1d8d3.png)

The command area also seems to not change color when transparency is set, leaving a grey-ish bar instead of making it the same color as everything else.

Full goneovim config:
```
[Editor]
Transparent = 0.8
SmoothScroll = true

[Message]
Transparent = 0.8

[Statusline]
Visible = false
```

When looking through other issues, one said to set termguicolors. I've tried this and it does not help. I can post any additional config or system information if needed.

**Comment by akiyosi** [comment]
@pollen00 
Hi,
I'm sorry for the late reply. I was dealing with other high priority issues.

Regarding what you reported, Goneovim has a small margin at the edge of the window. The size of this margin can be reduced somewhat by setting the following in `settings.toml`, but it still leaves a small margin.

```toml
[Editor]
#...
Gap = 0
#...
```

This is a specification, but if it is absolutely necessary, we will consider extending the feature.

Also, the transparency settings for the message window should be set as follows:

```toml
[Message]
Transparent = 0.7
```

**Comment by pollen00** [comment]
Setting `Gap` to 0 in the Editor section doesn't seem to change anything. The margin is still the same size.

**Comment by akiyosi** [comment]
@13k 
This was originally hard-coded for implementation reasons.
Also, the extra space at the bottom or right side of the window beyond what is set is "left over" space from the window geometry and font metrics calculations. As you noted, it is understandable that it looks ugly.

I will respond to you on How to solve these issues in Issue #289.

**Comment by 13k** [comment]
It seems f0624e5b01e82bef701f0eac6d7d64abec2b2132 fixed the issue (tested on linux and macos)
