### ISSUE TITLE
incorrect char when copy chinese char to paste

### ISSUE THREAD

**Issue by guolimin1995** [akiyosi/goneovim#298]
when yy to copy chinese, then p to paste.
it's get incorrect char ?????.

https://user-images.githubusercontent.com/29330637/146699613-fbde12cb-cf57-434c-9651-2e4e64c681fe.mov

**Comment by akiyosi** [comment]
hi, thanks for the issue report.

I don't know the exact cause, but it may be solved by setting the environment variable LC_ALL or some other environment variable value in your shell profile. Could you please check this point of view first?

The following issues may be helpful.

https://github.com/akiyosi/goneovim/issues/164
https://github.com/akiyosi/goneovim/issues/259#issuecomment-925066731

**Comment by guolimin1995** [comment]
> hi, thanks for the issue report.
> 
> I don't know the exact cause, but it may be solved by setting the environment variable LC_ALL or some other environment variable value in your shell profile. Could you please check this point of view first?
> 
> The following issues may be helpful.
> 
> #164 [#259 (comment)](https://github.com/akiyosi/goneovim/issues/259#issuecomment-925066731)

thanks for reply.
add lang setting to .zprofile is working.
tks
