### ISSUE TITLE
Switch to Light Background

### ISSUE THREAD

**Issue by goerz** [akiyosi/goneovim#30]
Is there a way to switch the app to a normal light colorscheme?

**Comment by akiyosi** [comment]
Do you want to switch the application to a light colorscheme, except for light theme colorscheme setting in init.vim?

**Comment by goerz** [comment]
Yes, I‘d like the entire application interface to have light colors (like any regular Mac app). In addition to that, &background should also be “light”, so that the color scheme I choose in my init.vim sets the appropriate colors.

**Comment by bfulop** [comment]
Hello @goerz,

I have personally never had problems using light themes with Gonvim. Just installed them via Plug and set the `colorscheme` in `init.vim` and somehow Gonvim automagically adopted the colours from that colorscheme. 

You can also try `set background=light`, but in my experience it was not necessary.

**Comment by goerz** [comment]
That doesn't seem to work for my colorscheme: https://github.com/goerz/vimrc/blob/17f67b6f85a0c5c5c7370b86426d4ff68894fba0/colors/goerz.vim

**Comment by akiyosi** [comment]
Hi,
gonvim communicates with neovim via [RPC PAI](https://neovim.io/doc/user/ui.html) and draws a GUI.
Currently, if there is no explicit color notification by the RPC API from neovim, gonvim draws the entire GUI with a dark theme regardless of the value of &background.
I will consider reading the &background option on startup, but it may affect the startup speed of the application.
