### ISSUE TITLE
Can you release a new version like Goneovim-v0.4.13-linux.tar.bz2 which also packaged its running environment?

### ISSUE THREAD

**Issue by Banana-Two** [akiyosi/goneovim#303]
Can you release a new version like Goneovim-v0.4.13-linux.tar.bz2 which also packaged its running environment? We can run it although our version of qt is smaller than 5.14. Thanks very much.

**Comment by akiyosi** [comment]
Hi,
I have updated the release to 0.5.1. Please check the contents.

https://github.com/akiyosi/goneovim/releases/tag/v0.5.1

**Comment by Banana-Two** [comment]
@akiyosi 
Ok, thanks very much.
