### ISSUE TITLE
goneovim fails on windows when nvim is a symbolic link in path

### ISSUE THREAD

**Issue by j-xella** [akiyosi/goneovim#304]
Hi, I have nvim installed in a custom folder on my Windows 10 PC. I did not want to expand path, so instead I created a symbolic link to nvim.exe in one of the folders already in path:

PATH=...;C:\Users\alex\Projects\bin

dir C:\Users\alex\Projects\bin
...
06/01/2022  11:11    <SYMLINK>      nvim.exe [c:\Users\alex\MyApps\Neovim\bin\nvim.exe]

This works - now I can run nvim.exe from anywhere. But when I try to start goneovim, it starts for a second, then disappears. Running it with --debug produces this:

2022/01/06 11:14:11.595407 000.000 --- GONEOVIM STARTING ---
2022/01/06 11:14:11.595407 000.000 detecting home directory path
2022/01/06 11:14:11.596405 000.998 reading config
2022/01/06 11:14:11.596405 000.998 start    generating the application
2022/01/06 11:14:11.613359 017.952 finished generating the application
2022/01/06 11:14:11.613359 017.952 setting environment variable
2022/01/06 11:14:11.613359 017.952 set working directory path
2022/01/06 11:14:11.614357 018.950 initializing font
2022/01/06 11:14:11.614357 018.950 initializing svg images
2022/01/06 11:14:11.614357 018.950 initializing color palette
2022/01/06 11:14:11.614357 018.950 initializing notification UI
2022/01/06 11:14:11.614357 018.950 start    preparing the application window.
2022/01/06 11:14:11.674199 078.792 finished preparing the application window.
2022/01/06 11:14:11.675194 079.787 window layout done
2022/01/06 11:14:11.675194 079.787 done calculating the width of the font.
2022/01/06 11:14:11.675194 079.787 initialize workspace
2022/01/06 11:14:11.676192 080.785 initialazed UI components
2022/01/06 11:14:11.676192 080.785 assembled UI components
2022/01/06 11:14:11.676192 080.785 done initialazing workspaces
2022/01/06 11:14:11.676192 080.785 done connecting UI siganal
2022/01/06 11:14:11.676192 080.785 starting nvim
2022/01/06 11:14:11.676192 080.785 focused UI
2022/01/06 11:14:11.714090 118.683 done starting nvim
2022/01/06 11:14:11.714090 118.683 updating size of UI components
2022/01/06 11:14:11.714090 118.683 attaching UI

**Comment by j-xella** [comment]
Just to be clear - there are at least 2 workarounds that work:

- Add path to actual nvim.exe to %PATH%
- run goneovim with --nvim=... option

But it would be nice for goneovim to work without those hacks...

**Comment by akiyosi** [comment]
@j-xella 
Hi :)
Thanks for this issue reporting.

After researching this issue, it seems that for execution via the command line (and execution of nvim inside Goneovim is equivalent to execution via the command line), the symbolic link is not enough for nvim.exe alone.
In my environment, I was able to start Goneovim by preparing a symbolic link to an appropriate directory registered in %PATH% as follows.


```cmd

C:\test>mklink nvim.exe C:\Users\akiyoshi\Desktop\Neovim\bin\nvim.exe
symbolic link created for nvim.exe <<===>> C:\Users\akiyoshi\Desktop\Neovim\bin\nvim.exe

C:\test>mklink winpty.dll C:\Users\akiyoshi\Desktop\Neovim\bin\winpty.dll
symbolic link created for winpty.dll <<===>> C:\Users\akiyoshi\Desktop\Neovim\bin\winpty.dll

C:\test>mklink uv.dll C:\Users\akiyoshi\Desktop\Neovim\bin\uv.dll
symbolic link created for uv.dll <<===>> C:\Users\akiyoshi\Desktop\Neovim\bin\uv.dll

C:\test>mklink msgpackc.dll C:\Users\akiyoshi\Desktop\Neovim\bin\msgpackc.dll
symbolic link created for msgpackc.dll <<===>> C:\Users\akiyoshi\Desktop\Neovim\bin\msgpackc.dll

C:\test>mklink lua51.dll C:\Users\akiyoshi\Desktop\Neovim\bin\lua51.dll
symbolic link created for lua51.dll <<===>> C:\Users\akiyoshi\Desktop\Neovim\bin\lua51.dll

C:\test>dir

 Directory of C:\test

01/08/2022  11:15 AM    <DIR>          .
01/08/2022  11:15 AM    <DIR>          ..
01/07/2022  01:28 PM    <SYMLINK>      lua51.dll [C:\Users\akiyoshi\Desktop\Neovim\bin\lua51.dll]
01/07/2022  01:27 PM    <SYMLINK>      msgpackc.dll [C:\Users\akiyoshi\Desktop\Neovim\bin\msgpackc.dll]
01/07/2022  01:04 PM    <SYMLINK>      nvim.exe [C:\Users\akiyoshi\Desktop\Neovim\bin\nvim.exe]
01/07/2022  01:27 PM    <SYMLINK>      uv.dll [C:\Users\akiyoshi\Desktop\Neovim\bin\uv.dll]
01/07/2022  01:27 PM    <SYMLINK>      winpty.dll [C:\Users\akiyoshi\Desktop\Neovim\bin\winpty.dll]
```

**Comment by akiyosi** [comment]
@j-xella 
Closing this issue.
If there is anything else related to this issue, please open it again.
