### ISSUE TITLE
Tab no longer inserts a tab character since 0.3.2

### ISSUE THREAD

**Issue by jaapz** [akiyosi/goneovim#31]
When I installed 0.3.2, I was no longer able to insert tabs using the tab key. Reverting back to 0.3.1 fixed the problem.

**Comment by akiyosi** [comment]
Hi,
The problem may be in the focus of the UI. When Gonvim is focused on other than vim's screen, no arrow key or tab is entered. This focus is unfocused with the Esc key. Please confirm this point.
I will improve so that it will not be focused in the future.

**Comment by jaapz** [comment]
I'll have to recompile and check out 0.3.3 to see if that's the case, I'll try to test it soon
