### ISSUE TITLE
Linux build for latest release reposted?

### ISSUE THREAD

**Issue by alerque** [akiyosi/goneovim#310]
We're having a little trouble with the AUR package that uses the upstream binary. Different people are getting different checksums off the file and it's blocking automatic installs.

Did you guys repost the Goneovim-v0.5.1-linux.tar.bz2 attached to the latest release after initially posting it?

**Comment by akiyosi** [comment]
Hi :)

Yes, the Linux build has been replaced once from the first release of v0.5.1. Sorry for not reporting the impact of the work on the AUR.
If it is for archlinux, I recommend `Goneovim-v0.5.1-linux_arch.tar.bz2`.

**Comment by alerque** [comment]
Please don't do that. If something is wrong with the build and the artifacts need replacing cut a patch release.
