### ISSUE TITLE
DMG packaging for macos

### ISSUE THREAD

**Issue by psadi** [akiyosi/goneovim#312]
im using a company restricted macos, and it would be great if dmg packaging is provided.

**Comment by akiyosi** [comment]
Hi,
Thanks for this issue report.
Okay, I will consider releasing it in DBG format from the next release.

**Comment by addy3494** [comment]
Thanks for consideration.

**Comment by akiyosi** [comment]
@addy3494 
Hmmm, goneovim.app is currently not code-signing, so even if you install it in DMG format in your environment, it will still be "from an unidentified developer" and I doubt it will solve your problem.

You can get the installer in DMG format from the following CI. Please make sure that it works on your company restricted macos.

https://github.com/akiyosi/goneovim/actions/runs/1754042756

**Comment by addy3494** [comment]
Hi @akiyosi 

yes you are correct, using DMG didn't solve either.
Are there any considerations for code signing ?

**Comment by akiyosi** [comment]
@addy3494 
Yes, I do plan to codesign the app, but currently I do not have an Apple Developer ID.
Sorry, it is difficult to support this immediately, but this matter will be addressed in the future and it will take some time to prepare.

**Comment by psadi** [comment]
@akiyosi  - I understand, I am  closing this issue
