### ISSUE TITLE
keep crashing with vim-go

### ISSUE THREAD

**Issue by bon-ami** [akiyosi/goneovim#318]
v0.5.1 crashes very often, while former versions and nvim-qt.exe did/does not.
editing go files, so I'm using many plugins for golang. I suppose vim-go is the cause.

**Comment by akiyosi** [comment]
@bon-ami 
Hi :) 
Thanks for this issue report.

The application crash is a critical issue and I will give it priority for investigation.
Could you please provide me with the following information?

* Your Operating System information
* `nvim --version`
* `/path/to/goneovim --version`, or `:GonvimVersion` in running goneovim.
* Your goneovim's settings (`~/.config/goneovim/settings.toml` in linux/macOS, `~/.goneovim/settings.toml` in Windows)

**Comment by bon-ami** [comment]
not reproduced in two days. I'll monitor it.
Thanks for your prompt response.

**Comment by akiyosi** [comment]
@bon-ami 
Thanks for the additional information.
I'm trying to reproduce the issue and am also performing static analysis of the code base.
There are two possibilities for this problem, one is a bug in Goneovim and the other is a possible problem on the nvim side. (From the looks of it, you're not using the release version, but the nightly or close to it version)

I would appreciate it if you could report anything new in this issue.

Translated with www.DeepL.com/Translator (free version)

**Comment by bon-ami** [comment]
Since I cannot reproduce it at the former rate, I'd like to close this.
