### ISSUE TITLE
detach from terminal

### ISSUE THREAD

**Issue by ehsanghorbani190** [akiyosi/goneovim#320]
Hi :D currently i run goneovim from terminal, the problem is when i run goneovim, the terminal stops because its launching goneovim. this terminal will become a problem when switching between windows using alt+tab. also i need another terminal for running `npm start` and it would be better if i could run that command in the same terminal tab after opening goneovim. is there a way to detach the program from terminal like neovide ?

**Comment by akiyosi** [comment]
Hi :)
Does running commands with `&` in the background, as is well known, not fit into your workflow?
e.g.

```
/path/to/goneovim &
```

**Comment by MuhammedZakir** [comment]
I have this in my ZSH config (see section `JOBS` in `zshmisc` manpage):
```zsh
function launch() {
  local type="$1"; shift;
  case "$type" in
    (s) "$@" >/dev/null 2>&1     ;;   # (q)uiet
    (b) "$@" >/dev/null 2>&1 &   ;;   # quiet+(b)ackground
    (d) "$@" >/dev/null 2>&1 &!  ;;   # quiet+(d)isown
  esac
}
```

Example usage: `launch d /path/to/goneovim`. You will be able to do the same in other shells (except maybe the third one - disowning). You can also use this in other places like keyboard remapper or in auto-start scripts if you put this in a seperate file and then source it when needed.

**Comment by ehsanghorbani190** [comment]
@akiyosi i tried but it doesn't work , unless using `nohup`
@MuhammedZakir great job! :+1: 

for zsh users, @MuhammedZakir 's way will be more than enough :D
i managed to write a function in fish( my shell ):
`function mvim
        nohup goneovim --maximized $argv &
        disown %1
    end
`
this detaches goneovim totally from the terminal you used to run it.
**BE AWARE: this function can be unsafe to use for you! i wrote it in this way because i always open a terminal to just open my project, `disown %1` can be dangerous if you use terminal to open some jobs in background before using this**

I hope its useful :D

**Comment by akiyosi** [comment]
I understand what you mean about the request to detach from the terminal.
I will keep this issue open and consider supporting it in the near future.

**Comment by Mo8it** [comment]
@ehsanghorbani190 
`goneovim &; disown`
This should be enough in fish. No need to specify the job number. It will disown the last job.
From the docs: https://fishshell.com/docs/current/cmds/disown.html#example

**Comment by akiyosi** [comment]
Hi guys,
I am creating a fix that will detach goenovim from the terminal by default.
I would appreciate it if anyone could help us to confirm the behavior and feedback.

https://github.com/akiyosi/goneovim/actions/runs/2307587101

**Comment by akiyosi** [comment]
The fixes have been merged.
