### ISSUE TITLE
terminal command not found such as ipython

### ISSUE THREAD

**Issue by sigma2647** [akiyosi/goneovim#326]
OS: MacOS
I recently found if I open goneovim from the terminal the type `:terminal ipython` is worked
but if I open goneovim for the launcher  type `:terminal ipython` it shows `zsh:1: command not found: ipython`

**Comment by sigma2647** [comment]
I try to type `:terminal echo $PATH` in those two ways, then realize it shows different environment variable base on different way of launch app
It's there any way I can configure that?

**Comment by MuhammedZakir** [comment]
Suggestion: a cli command to generate an env file with the current env vars would be nice. The file could be in Vimscript or Lua.

It can be generated using the the commands `env` and `set` in \*nix and Windows respectively. It would be nice to get a few additional options like in `doom` cli (of doom-emacs):
```
$ doom help env
  Options:
    -a, --allow REGEXP
      An additive envvar whitelist regexp
    -r, --reject REGEXP
      An additive envvar blacklist regexp
    -A REGEXP
      Blacklist everything but REGEXP
    -R REGEXP
      Whitelist everything but REGEXP
    -c, --clear
      Clear and delete your envvar file
    -o PATH
      Generate the envvar file at PATH. [...]
```

`-o PATH` is useful to use different env vars for different jobs.

See https://github.com/hlissner/doom-emacs/blob/master/core/cli/env.el for more information (e.g. needed default backlist).

**Comment by akiyosi** [comment]
@sigma2647 
When launched from the .app, goneovim launches the program specified by `SHELL` environment variable in login shell mode and performs the same environment variables that are defined on the shell program, all of which are set on the goneovim program.
See the process:
https://github.com/akiyosi/goneovim/blob/dbb94f2ea790ab16de573998c7d2fe516ccd30ce/editor/editor.go#L563-L592

I think you need to check to make sure that the shell program specified in the environment variable `SHELL` is the same shell program that is run by the terminal software you use on a daily basis.

**Comment by sigma2647** [comment]
Thanks! I found it's the virtual end problem, I put the python path in `.zprofile` then it can run ipython commmand in goneovim
