### ISSUE TITLE
Neomake linters are not showing up in gonvim

### ISSUE THREAD

**Issue by jaapz** [akiyosi/goneovim#33]
I have nvim configured to use  neomake (https://github.com/benekastah/neomake) which runs linters like `flake8` for python and `gometalinter` for go. When I save a file, the linters are automatically executed and any errors are shown in a gutter. 

However, when running gonvim, these errors never show up. Does gonvim support such things yet, and have I misconfigured it, or is it not supported?

**Comment by jaapz** [comment]
I switched to ALE (which I saw you supported in another issue), but those also don't show up when editing a file or saving it. I also don't see any linters being called by nvim when saving or editing. Maybe linting integration is just broken?

**Comment by akiyosi** [comment]
Hi,
gonvim lint feature is disabled by default, in order to enable, it is necessary to append the following to the `setting.toml`.

```
[Lint]
Visible = true
```

If it still does not show up, please tell me the minimal init.vim to reproduce the problem.

**Comment by jaapz** [comment]
I have it enabled already. I'll try to find a minimal init.vim that exhibits the problem
