### ISSUE TITLE
Status line shows file name as [No Name]

### ISSUE THREAD

**Issue by damanis** [akiyosi/goneovim#332]
goneovim version: nightly-1-g531049e

![image](https://user-images.githubusercontent.com/65733488/161050539-9e3cffcb-3101-438c-9a70-ea31526dfc00.png)

settings.toml:
```
[Statusline]
Visible = true
Left = [ "mode", "filename" ]
# Right = [ "message", "git", "filetype", "fileformat", "fileencoding", "curpos", "lint" ]

```

P.S. I know, it should not be here, but worth adding status line colors configuration. White status line in dark goneovim window looks strange.

**Comment by proofer** [comment]
![statusline](https://user-images.githubusercontent.com/1290776/188327477-122cc254-b53a-4038-b13c-0c843e8b9448.png)

**Comment by damanis** [comment]
It start work if switch to another file:
- goneovim test_file.txt -> [No Name]
- ':e test_file2.txt' -> test_file2.txt

**Comment by akiyosi** [comment]
Close this issue with #475.
