### ISSUE TITLE
winsize, set columns, and set lines don't change window size

### ISSUE THREAD

**Issue by mars0i** [akiyosi/goneovim#334]
goneovim seems very nice!  There is one set of functions that I use all the time that it doesn't fully implement.

neovim (and vim) include commands `set columns` to change the window width in characters, `set lines` to set the number of text rows, and `winsize` to set both at the same time.  In MacVim, these commands change the internal vim window size as well as the GUI window size.  In plain neovim, in some terminal apps (e.g. iTerm2), running these commands also changes the GUI window size of the terminal program.  

In goneovim, `set columns`, `set lines`, and `winsize` change the internal window size--you can see this because the status line changes its position or length--but they don't change the GUI window size.  So, for example, if the window starts out with 80x40 text, and then you run `set lines=25`, the status line moves up so that it's floating in the GUI window.

(Some other neovim GUI apps have the same problem btw.  I'm not sure why.)

Thanks very much.

**Comment by akiyosi** [comment]
@mars0i 
Hi, 
Thanks for this report!

I implemented the ability to resize the application window by set lines, set columns, etc.
You can get the artifacts from the following CI job to try it out.
Your feedback would be appreciated.

https://github.com/akiyosi/goneovim/actions/runs/2155548260

**Comment by mars0i** [comment]
Thanks @akiyosi !   I'll figure out how to set myself up to build it and try it out tonight or tomorrow.  (I used a pre-built image before.)

**Comment by mars0i** [comment]
OK, found it.

**Comment by mars0i** [comment]
No problems at all.  The window sizing commands have been working perfectly.  

By the way, as far as I know, goneovim is the Neovim GUI on MacOS that implements those commands now.  (I think I've tried all of the Neovim GUIs that run on MacOS--all of the general-purpose ones, at least; some are for specialized uses.) Thank you!  This is very nice.

I hope you don't mind--there are a couple of other issues that I'll submit.  These are things I didn't notice or didn't understand previously.

**Comment by akiyosi** [comment]
Thanks for the confirmation and feedback.
I have merged this feature into master.
I will close this issue.
