### ISSUE TITLE
Command line options do not work in windows

### ISSUE THREAD

**Issue by shiena** [akiyosi/goneovim#335]
OS: Windows10
goneovim: nightly-1-gaeea7ae

![image](https://user-images.githubusercontent.com/1295639/162691995-58827a08-2a74-457d-a195-9f0a909ef0e0.png)

However, it is possible to open the file specified in the argument.

**Comment by shiena** [comment]
This setting seems relevant.
https://forum.qt.io/topic/120368/console-settings

**Comment by shiena** [comment]
The windows build uploaded to the following URL was output to the console.
https://github.com/akiyosi/goneovim/actions/runs/2149147269
![image](https://user-images.githubusercontent.com/1295639/162780877-8fe2bb3a-827b-4a70-bc32-80bb3074cf80.png)

**Comment by akiyosi** [comment]
It seems that enabling `QT_DEBUG_CONSOLE` launches a console window in addition to the GUI window. 
There may need to be a way to suppress this or another mechanism to display application help, version information, etc. 
neovim-qt seems to have achieved this with its own widget.

**Comment by shiena** [comment]
I think it's okay to revert this commit.
https://github.com/akiyosi/goneovim/commit/939f78d2151cf27d1cad434cd1ae5524b0729159

**Comment by shiena** [comment]
@akiyosi 
I ran `goneovim --help` from within Goneovim and got the output. So, I created a script to display it in a float window.

```vim
function! GoneovimHelp() abort
	let output = systemlist("wmic process where \"name='goneovim.exe'\" get executablepath")
	let exepath = ''
	for line in output
		if stridx(line, 'goneovim.exe') != -1
			let exepath = line
		endif
	endfor
	if strlen(exepath) == 0
		return
	endif

	let output = systemlist(exepath . ' --help')
	let width = 0
	for line in output
		let length = strlen(line)
		if length > width
			let width = length
		endif
	endfor
	let height = len(output)
	let opts = {
				\ 'relative': 'editor',
				\ 'width': width + 1,
				\ 'height': height,
				\ 'col': 1,
				\ 'row': 1,
				\ 'anchor': 'NW',
				\ 'style': 'minimal'
				\ }
	let buf = nvim_create_buf(v:false, v:true)
	let win = nvim_open_win(buf, v:true, opts)
	call nvim_buf_set_lines(buf, 0, -1, v:true, output)
endfunction
command! GoneovimHelp call GoneovimHelp()
```

<img width="615" alt="image" src="https://user-images.githubusercontent.com/1295639/235991517-966ab9f9-6785-48b0-aa45-0ef41b7be39a.png">

**Comment by akiyosi** [comment]
@shiena 
Nice! 
It might be a good idea to add this command as a Windows-only default.

**Comment by shiena** [comment]
I don't know why, but I was able to output the help to the console with the following command.

```
# for PowerShell
goneovim --help | Out-Host
# or
goneovim --help | Out-Default
```

```
# for cmd
goneovim --help | more
```
