### ISSUE TITLE
winpos doesn't position window

### ISSUE THREAD

**Issue by mars0i** [akiyosi/goneovim#338]
If it's possible and not too difficult, another Vim GUI command that would be very helpful for me is `:winpos X Y`, where X and Y are numbers of pixels.   This sets the upper left coordinates of the GUI window to be at  X,Y.  (I want to combine this with the window size commands.)  

I know you're busy and can't implement everything, but I thought I'd mention this for future reference.  Thank you!

**Comment by akiyosi** [comment]
@mars0i 
Hi :) 
Currently, it seems that neovim does not support `winpos` command. Therefore, it will be necessary to modify the neovim side to implement `winpos` command.
On the other hand, it would be possible to implement the same functionality with Goneovim's own commands.
If I have time, I would like to implement it.

**Comment by mars0i** [comment]
Thanks @akiyosi.  

(That makes sense that nvim doesn't have it.  Running nvim in iTerm2, where the `winsize` and `set columns`, etc. commands work, `winpos` doesn't work.  It doesn't seem like terminal apps would allow apps running in them to change the window position.)

**Comment by mars0i** [comment]
I thought I might try to implement this function.  I don't have time to learn much about Go or Qt unfortunately, but it seems like it ought to be a relatively simple thing to implement, so I thought I'd give it a try.  If I don't succeed because I don't know enough, that's OK.

I'm finding that it's tricky to get the "setup Go binding" step on the Development page to work.  I am not sure, but it seems as if I have to have exactly version 5.13.0 of Qt, and the closest version that the installation tool offers to me is 15.13.2.  Or maybe there's a component of Qt that I haven't installed?  I don't know.  Since I don't have time to learn much about Go and Qt--which might be a mistake--I may just be stuck.

This is not your problem!  I'm just letting you know.  I might figure it out.

(I have a couple of lines of code that I added to workspace.go that might be enough, but I haven't been able test it, and it's unlikely that what I've added is enough on its own given how little I know.)

**Comment by mars0i** [comment]
Never mind.  I figured out how to install Qt 5.13.0.  I'll see whether that works.

**Comment by akiyosi** [comment]
@mars0i 
Hi :D 
Thank you for your willingness to contribute.
I would like to support you in any way I can.

Now, I apologize for the lack of clarity in the documentation.
Actually, Qt versions 5.13.X, 5.14.X, 5.15.X are all fine. (I haven't tested any other Qt5 versions recently, and Qt binding doesn't seem to support Qt6.)
The documentation describes using `5.13.0` in the `QT_API` environment variable, but this is like the interface version of the Qt Go binding, not the version of Qt you are using. Of course, using Qt 5.13.0 is fine.

**Comment by mars0i** [comment]
Thank you @akiyosi!

I was able to complete the qtsetup step with a full installation of Qt 5.13.0.  (  When I used 5.13.2, the qtsetup process stopped with an error that it couldn't find a file.  I could see that a file with that name was somewhere under the 5.13.2 directory, but the qtsetup process wasn't finding it.  That's why I thought it might work if I installed Qt 5.13.0, and it did work.

I did have one warning when I ran qtsetup with Qt 5.13.0:
```
stat /Users/myusername/go/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtWebEngineCore.framework/QtWebEngineCore: no such file or directory
```
I got the same message when I ran `$(go env GOPATH)/bin/qtdeploy build desktop`, but the build seems to have succeeded.  I'm able to run the newly created binary.

**Comment by mars0i** [comment]
Hi @akiyosi. I have a working version of a new `:GonvimWinpos {x} {y}` command here: https://github.com/mars0i/goneovim/commit/ab76d0f1c96241e69e64f7172f3f44b4ab528bb4 .

Please let me know if you have feedback at this point.  Maybe a different name for the command or some of my variables would be better, maybe the code needs more error handling, or maybe it would be better to use entirely different methods.

I'm still experimenting with the `GonvimWinpos` version of goneovim.  I'm finding that after a few minutes it would go to > 100% CPU.  Maybe this is related to #345, or maybe it has to do with what I added or how I was running goneovim: I just ran the binary file from inside the goneovim/cmd/goneovim/deploy/darwin/goneovim.app tree under ~/go.  

I think that I am building using the latest versions of the goneovim and goqtframlesswindow source, but I'm not certain.  I'm still figuring out how to use the go build and configuration tools, and I haven't yet figured out how to pull updates to the code from the repos (goneovim, goqtframelesswindow), as I would do with `git pull`.

(If I run `go get -d github.com/akiyosi/goneovim/...` now, in order to get more recent source, will it overwrite what needs to be overwritten, and clean out what is stale?  Can I use `git clone` instead?)

Thanks!

**Comment by akiyosi** [comment]
@mars0i 
Hi :D 
Thank you for your contribution! It looks good to me.
I am waiting for your PR.

> I'm still experimenting with the GonvimWinpos version of goneovim. I'm finding that after a few minutes it goes to about 100% CPU. (I haven't seen that with the goneovim version I have installed in /Applications, which is nightly-1-g0e35e77.) Maybe this is related to https://github.com/akiyosi/goneovim/issues/345, or maybe it has to do with what I added , or how I was running my new version of goneovim: I just ran the binary file from inside the goneovim/cmd/goneovim/deploy/darwin/goneovim.app tree under ~/go. Also, go test gives me warnings about object files that were "built for newer macOS version (10.15) than being linked (10.12)". Could that cause the high CPU usage?

I have tried your branch on my machine and `:GonvimWinpos` command is working fine and the CPU never seems to go to 100% when I am not operating anything.
Indeed, the problem with your Goneovim going to 100% after a few minutes could be the same problem with the #345.
It might be a good try to test with `goneovim -u NONE`.

> (If there are changes in the master branch, and I run go get -d github.com/akiyosi/goneovim/... now, in order to get more recent source, will it overwrite what needs to be overwritten, and clean out what is stale? Can I use git pull instead?)

I understand that `go get` command uses git mechanism internally, so each repository downloaded under `$GOPATH` is a git repository and can be controlled by commands such as `git fetch` in each directory.

**Comment by mars0i** [comment]
Excellent!  I'll submit the PR in a moment.  Being able to set the window position programmatically is important to me.  I'm happy that I was able to contribute.

About CPU usage, yes with `-u NONE` my new version of goneovim does not have high CPU usage.  I'll continue my remarks about this at #345, since it seems to be the same issue.
