### ISSUE TITLE
Proposed Logo

### ISSUE THREAD

**Issue by b-fuze** [akiyosi/goneovim#34]
I love Gonvim, but I want it to have a logo, so I made this logo in Inkscape
![Gonvim Logo](https://i.imgur.com/nijrdJC.png)

The blue is from the Gopher mascot of GoLang. Let me know what you think

**Comment by akiyosi** [comment]
Hi,
Gonvim already has a [logo](https://raw.githubusercontent.com/wiki/akiyosi/gonvim/images/gopher-with-neovim.png). 
The MacOS and Windows application icon uses this logo as an application icon.
Do you expect this proposal to replace the application icon?
As it is, the image of the proposal is cool.

**Comment by b-fuze** [comment]
Oh, I see, I should've looked, here is what I see on Linux (Ubuntu 18.04 LTS) amusingly 
![image](https://user-images.githubusercontent.com/10504957/51844154-8e7caf00-22e2-11e9-986c-6066aab666a4.png)

If you want to think about changing it you can, otherwise I would just like to see Linux show the icon... It's some kinda Qt thing hmm...

**Comment by akiyosi** [comment]
I have not investigated enough about how to set icons for Linux applications.
ref: https://github.com/therecipe/qt/wiki/Setting-the-Application-Icon
I will probably consider implementing it in the next version.

**Comment by akiyosi** [comment]
I'm wondering whether to change the application icon at v0.4.0. 
The current icons are also good, but more modern designs may be preferred by many.

**Comment by Mariappan** [comment]
@akiyosi Any plans to change the icons ?? The above one looks good

**Comment by akiyosi** [comment]
@Mariappan 
Don't you like the current v0.4.0 icon?
I want to change if there is a better icon.

**Comment by Mariappan** [comment]
This is the current one right ?
https://raw.githubusercontent.com/akiyosi/gonvim/0.4.0/cmd/gonvim/gonvim.ico

May be its the circle above which makes it uglier.
for ex: fvim icon is awesome. Take a look.
https://github.com/yatli/fvim/blob/master/fvim.svg

Looks simple and upto the point. But I am not much of the designer though.

**Comment by akiyosi** [comment]
@Mariappan 
thx. for opinion 😀
Yes, that icon.
I'm also not a designer, but I think that the goodness of the icons is a matter of personal preference. I don't like the fvim icon so much.
 
Currentry I'm going to adopt the basic design of the icon of gonvim after 0.4.0 (I'll also change the name to "goneovim") with the capital letter N, plus a triple line, inspired by Go language.
The above icon enclosed in a circle is my first idea.

I will try to make a version that is not enclosed in a circle, but it will take some time.

**Comment by akiyosi** [comment]
I created a icon which not enclosed in a circle version.
How about that 🙃
![goneovimicon](https://raw.githubusercontent.com/wiki/akiyosi/gonvim/images/goneovim-icon.png)

**Comment by smolck** [comment]
@b-fuze Can this be closed now that the GoNeovim has a new logo?

**Comment by b-fuze** [comment]
Yeah, sure.
