### ISSUE TITLE
Add tip about Cmd-C, Cmd-V for MacOS?

### ISSUE THREAD

**Issue by mars0i** [akiyosi/goneovim#343]
This is not at all urgent, and it's a very minor question.

One of the things I got used to with MacVim was using MacOS standard mappings for copying (`Cmd-C`) and pasting (`Cmd-V`) from the system buffer.  At first I kept hitting these keys in goneovim. This caused a little bit of frustration with goneovim.  (`Cmd-C` made text go away!)

Eventually I realized that it's very simple to make `Cmd-C` and `Cmd-V` work in the normal MacOS way by putting these lines in a startup file such as .config/nvim/init.vim 
```
map <D-c> "+y
map <D-v> "+p
```
I was wondering whether you think it would be helpful to add this tip to the main Wiki document.  Maybe not everyone would want these keymappings, but some people might want to know that they can have them easily if they want.

If this does seem like useful info to include in the Wiki page, I'm not sure where to put it.  Maybe in a "Tips" section at the end?  I can make a quick PR for this if you want.

If you don't think it's worthwhile to add a tip about these mappings to the wiki, that's ok.  I understand.  I wanted to ask, though.

(I thought that I probably needed to enable `Clipboard = true` and maybe `Macmeta = true` in settings.toml to make those keymappings work, but the mappings seem to work even if I reverse the values of those variables.)

**Comment by akiyosi** [comment]
@mars0i 
Hi, thanks for this issue.

Sorry for the lack of documentation.
I think it would be useful to have this information about keymaps on the Wiki, but I have not had enough time to maintain it.
It would be very worthwhile to include this information in the Wiki.
I just created `Tips` page on the Wiki.

Note that these key mappings in MacVim are achieved by default by applying the dedicated mapping settings.
It may be useful to refer to the following configuration file in the MacVim repository.

https://github.com/macvim-dev/macvim/blob/master/runtime/macmap.vim#L48-L55

**Comment by mars0i** [comment]
Thanks very much for pointing me to the right way to define these mappings!  I have usually ignored the different `map` commands, but I can see that the version in the MacVim file you referenced are better.  I had to investigate understand the differences from my mappings, but now I understand.  I'll add a tip when I get a chance.

**Comment by mars0i** [comment]
I added a tip page about how to add MacOS key shortcuts.  Let me know if you'd like me to make changes, and of course you can modify it in any way you want.

I can't see the page now. I assume that it won't be visible until you approve it. I have a copy, though, so if you don't like the new page and want me to do something differently, you can delete the new page and I can submit a new one.

I thought it would be good to just point users to the macmap.vim file for MacVim.  Adding a link to it should not require you to add the Vim license.
