### ISSUE TITLE
Cmd-Q doesn't close Goneovim in MacOS

### ISSUE THREAD

**Issue by mars0i** [akiyosi/goneovim#354]
In MacVim, `Cmd-Q` tries to shut down MacVim.  If there are modified buffers, there's a popup message asking if the user wants to continue, and giving them the option to cancel the shutdown.  This is a standard MacOS behavior.  

In Goneovim, `Cmd-Q` does nothing.  It's not very important to me that `Cmd-Q` shut down Goneovim, but it would be convenient if it did do that.  (`Cmd-Q` is listed on Goneovim's MacOS menu in the upper left of the screen, but I assume that's just a MacOS Qt default.  The menu doesn't matter to me.  The main reason that I would like to have `Cmd-Q` shut down Goneovim is that this is what my fingers want to do sometimes.)

I thought that maybe I could map `<D-q>` to `:quit<CR>`, but it appears that `Cmd-Q` isn't passed through to Neovim.

Is it possible to implement an exit function for `Cmd-Q` in MacOS or to pass `Cmd-Q` through to Neovim so that it can be mapped?

(I'd be happy if someone else implemented this--I have enough work(!) and it's not very important to me.  But if I wanted to try to make `Cmd-Q` work, where should I look in the Goneovim source code?)

**Comment by akiyosi** [comment]
@mars0i 
hi :)

My comments below on similar issues in the past are all I am aware of at this time: the situation is probably still the same, that it is difficult to handle cmd-q naively at the qt layer.

https://github.com/akiyosi/goneovim/issues/133#issuecomment-640020701

**Comment by mars0i** [comment]
Hi @akiyosi--thank you.  I apologize for not searching the issues and finding #133.  I usually search first, but I forgot to do that.

That's fascinating that: (a) it's difficult to map Cmd-Q directly in Qt, but (b) it's easy to map it by adding a shortcut for a *different* key combination.  That is good enough for me.  Thanks.

If it would be OK with you, I could add a tip about Cmd-Q on MacOS. (I assume that you saw that I added a tips page about Cmd-V, etc.--for whenever you get to it.)
