### ISSUE TITLE
Option to disable mouse

### ISSUE THREAD

**Issue by Mo8it** [akiyosi/goneovim#355]
Is there a way to disable mouse interaction completely?
I hate it when I accidentally touch the touchpad while editing and my cursor is then somewhere else :(
I also don't use the mouse in nvim. In my nvim config, the `mouse` option is set as an empty string.

It would be awesome if Goneovim would respect the `mouse` option :)

Thanks for the awesome GUI!

**Comment by akiyosi** [comment]
@Mo8it 
Hi, Thanks for this issue report.

The problem was that Goneovim was ignoring UI events related to the mouse; I have fixed it so that Goneovim's mouse behavior changes according to the setting of Neovim's `mouse` option. 
You can try it from the following CI job artifacts:

https://github.com/akiyosi/goneovim/actions/runs/2286282880

**Comment by Mo8it** [comment]
Thanks for the quick response!
I did try it out. Mouse clicks are disabled in this build, but scrolling is still active.

**Comment by Mo8it** [comment]
I guess the scrolling problem should be fixed with this commit: https://github.com/akiyosi/goneovim/commit/2b6b2ca354bb6d3462fe31e748e661da1bd3a019

But there is no build to test it.

btw.: How is the release cycle? The last official release is from about 5 months.

**Comment by Mo8it** [comment]
@akiyosi 
One more question: Is there a way to send you some money for a drink? I would like to support your development :)

**Comment by MuhammedZakir** [comment]
> I guess the scrolling problem should be fixed with this commit: [2b6b2ca](https://github.com/akiyosi/goneovim/commit/2b6b2ca354bb6d3462fe31e748e661da1bd3a019)
> 
> But there is no build to test it.

See https://github.com/akiyosi/goneovim/actions. You can find the apps for successful builds at the bottom of each action. They are called Artifacts in actions.

> btw.: How is the release cycle? The last official release is from about 5 months.

In case you don't know, nightly versions are available: https://github.com/akiyosi/goneovim/releases/tag/nightly.

**Comment by akiyosi** [comment]
@Mo8it 

> I guess the scrolling problem should be fixed with this commit: [2b6b2ca](https://github.com/akiyosi/goneovim/commit/2b6b2ca354bb6d3462fe31e748e661da1bd3a019)
> 
> But there is no build to test it.
> 
> btw.: How is the release cycle? The last official release is from about 5 months.

It can be found at the bottom of the CI job execution results page below.

https://github.com/akiyosi/goneovim/actions/runs/2286936133

I will also be releasing the next v0.5.2 soon! :)


> One more question: Is there a way to send you some money for a drink? I would like to support your development :)

Thank you for your kind offer.
However I do not intend to accept any financial assistance at this time. But such comments are very encouraging.

**Comment by Mo8it** [comment]
I did test it. No klicks and no scrolling with the mouse. Thank you!
