### ISSUE TITLE
Release artifacts should have the version in the filename

### ISSUE THREAD

**Issue by alerque** [akiyosi/goneovim#362]
The new 0.6.0 binary artifacts attached to the release do not have versions in the filename. This is an inconvenience for end users causing possible confusion in the future, but more importantly it is an outright error than needs manual correction for distro packagers.

![image](https://user-images.githubusercontent.com/173595/172020539-2897741b-f2bf-4f1b-8a2c-86bc8a2502f7.png)

Note the 0.5.1 release had the tag in the filename, so downloads were unique. Now every download filename is going to overwrite previous versions messing with things like checksums when distro packages attempt updates.

**Comment by akiyosi** [comment]
@alerque 
Thank you for your report.
I have released v0.6.1, which incorporates your points and other minor fixes.

https://github.com/akiyosi/goneovim/releases/tag/v0.6.1

**Comment by alerque** [comment]
Thanks for that fix. I got the Arch Linux [AUR -bin package variant](https://aur.archlinux.org/packages/goneovim-bin) updated. Given the improvements in the build process I think it should be relatively easy to get a normal source build variant setup too, and if that goes well and there is enough interest we can probably move it to [community] too.
