### ISSUE TITLE
Dina bitmap font don't display specific size on Windows

### ISSUE THREAD

**Issue by harg** [akiyosi/goneovim#363]
Hello,

Font used : https://www.dcmembers.com/jibsen/download/61/

Goneovim is displaying the 10pt version of the Dina font when i set `set guifont=Dina:h9` , here is the comparaison with gvim :

![image](https://user-images.githubusercontent.com/34398/172650855-d189848c-4c9c-4c7d-b610-5cfa0b372a6d.png)

Everything is fine with the 8pt version :

![image](https://user-images.githubusercontent.com/34398/172651608-8f7907ad-f92d-400a-bc38-f37f3a29ad38.png)

**Comment by akiyosi** [comment]
@harg 
Hi :)
it is because gvim and goneovim use different GUI frameworks, they handle fonts fundamentally differently.
