### ISSUE TITLE
Windows:  Use XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by homaji** [akiyosi/goneovim#366]
I set ENV XDG_CONFIG_HOME in Windows.
But goneovim don't get XDG_CONFIG_HOME.
I want  "goneovim" folder set in .config folder.

It seems in [config.go](https://github.com/akiyosi/goneovim/blob/master/editor/config.go)  line 162-175.
I should write code and send pull request.  Sorry, I tried and failed.

So, I send request.

**Comment by akiyosi** [comment]
@homaji 
hi,
Since I did not know the prevalence of xdg_config on Windows, I restricted it to unix-like operating systems.

I have removed this limitation with latest.
Please try it on the following CI job artifacts.

https://github.com/akiyosi/goneovim/actions/runs/2482398740

**Comment by homaji** [comment]
@akiyosi 
Thanks for your reply. Maybe, it's rare case to use xdg_config on windows.

I tried the binary in the [link](https://github.com/akiyosi/goneovim/actions/runs/2482398740) . It works! 
read setting file from ~/.config/goneovim/setting.stoml .

There are 2 windows binaries. 1st one is no problem.
2nd one shows other window. Is it OK?
![image](https://user-images.githubusercontent.com/1880055/173225756-33ffdfb2-31bb-4b53-9a51-47a0be3f3f65.png)

**Comment by akiyosi** [comment]
@homaji 
Uh, sorry for the confusion.
The windows-2 artifacts are for my experimentation. Never mind.
