### ISSUE TITLE
changing buffers through double click doesn't select word

### ISSUE THREAD

**Issue by M1cha** [akiyosi/goneovim#367]
when you have a split and double-click a word in the inactive pane it should select that word by going to visual-mode.
This works in alacritty, neovide and nvim-qt but not in goneovim.
In goneovim the first click in an inactive buffer simply changes focus to that buffer but does not seem to forward the click to it. The result is that I have to triple-click instead.

**Comment by akiyosi** [comment]
@M1cha 
Hi, Thanks for this issue report.
I am trying to fix this issue. The latest CI job artifact in the following has fixed the problem in my environment.
Could you please try it in your environment as well?

https://github.com/akiyosi/goneovim/actions/runs/2509880781

**Comment by M1cha** [comment]
It works great now, thx 🙂
