### ISSUE TITLE
Mouse / trackpad support

### ISSUE THREAD

**Issue by jaanauati** [akiyosi/goneovim#368]
Hey, I'm trying goneovim and I can't seem to be able to use the trackpad: I'm trying to select text, scroll or just click to move the cursor position but nothing happens. I this the expected way it should work?

GoneoVim version: 0.6.1

```
cat ~/.config/goneovim/settings.toml


[Editor]
SmoothScroll = true

[ScrollBar]
Visible = true


[MiniMap]
Visible = true

[Cursor]
SmoothMove = true
```

```
nvim --version
NVIM v0.8.0-dev+366-gc6d747e6a
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by jonatan@Jonatans-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-c6d747e/share/nvim"

Run :checkhealth for more info
```

Thank you.

**Comment by jaanauati** [comment]
oh, nvm, figured it out.: https://github.com/akiyosi/goneovim/issues/355, 

closing this one, thanks.

**Comment by akiyosi** [comment]
@jaanauati 
hi :) 
Try `set mouse=a` in your init.vim
