### ISSUE TITLE
Gonvim-fuzzy ag not working with remote attachment

### ISSUE THREAD

**Issue by Mariappan** [akiyosi/goneovim#37]
Hi Akiyosi,

I recently started using the remote attachment feature of gonvim to connect to my local linux vm, from host mac os and it is amazing. Thanks for this wonderful feature.

I had one little problem though. When trying to grep files using GonvimFuzzyAg, no results has been displayed.

This is only one pending feature which prevents me from using this GUI. All other fuzzy finders like GonvimFuzzyFiles and  GonvimFuzzyBuffers are all working.

I am not able to raise an issue in gonvim-fuzzy. Hence raising an issue here.
Can you please take a look ?

**Comment by akiyosi** [comment]
Hi,

> I am not able to raise an issue in gonvim-fuzzy. Hence raising an issue here.

It is no problem here.

> I had one little problem though. When trying to grep files using GonvimFuzzyAg, no results has been displayed.

In remote attach mode, ag must be installed on the remote host. Can you confirm this point?
If ag is not in PATH, you can also set Absolute Path of ag command with `g:gonvim_fuzzy_ag_cmd` variable in `init.vim` on the remote host.

**Comment by Mariappan** [comment]
Thanks @akiyosi 
It is in PATH only
`[maari@manjarooo gonvim-fuzzy]$ which ag
/usr/bin/ag
[maari@manjarooo gonvim-fuzzy]$ echo $PATH
/home/maari/.local/bin:/home/maari/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[maari@manjarooo gonvim-fuzzy]$ `

When i try to set the g:gonvim_fuzzy_ag_cmd manually, I get the following error while searching
let g:gonvim_fuzzy_ag_cmd='/usr/bin/ag --nogroup --column --nocolor'

`Invalid directory`

**Comment by akiyosi** [comment]
I'm sorry. I was misunderstanding.😓

In the current specification `GonvimFuzzyAg` searches for local files, not remote.
I am planning to improve `GonvimFuzzyAg` to search for remote host in remote attached case.
