### ISSUE TITLE
[Bug] GoNeovim doesn't show up when passing wrong/some cli flag to it. Happens after the addition of bg-forking feature.

### ISSUE THREAD

**Issue by MuhammedZakir** [akiyosi/goneovim#372]
When a wrong cli flag is passed, instead of showing that an unrecognized flag is given, GoNeovim forks and eats up CPU. I suspect this happened after the background-forking feature.

`goneovim --version`: `nightly-3-gde65d2d`
OS: Manjaro XFCE (Linux X11)

**Comment by MuhammedZakir** [comment]
The problem is not only with wrong cli flag. GoNeovim doesn't open if `-u NONE` is passed. It opens if you also `--nofork`.

**Comment by akiyosi** [comment]
@MuhammedZakir 
Thanks for this issue report.
I have fixed this problem in https://github.com/akiyosi/goneovim/commit/1045ebd503a3c84aafb3d91fb81bf8f47e5ec393
Please try the latest artifact.

https://github.com/akiyosi/goneovim/actions/runs/2522633084

**Comment by MuhammedZakir** [comment]
The problem when passing `-u NONE` is fixed. However, problem when passing wrong cli flag is not. E.g. `goneovim --helpp`.
