### ISSUE TITLE
how to disable ime on command-mode?

### ISSUE THREAD

**Issue by dian-yu-luo** [akiyosi/goneovim#380]
how to disable ime on command-mode?

**Comment by akiyosi** [comment]
@dian-yu-luo 
Hi, Thanks for this issue report.
Are you having problems disabling the IME in command line mode?

**Comment by shiena** [comment]
For windows, you can disable ime in command-mode with zenhan.

https://github.com/iuchim/zenhan/releases/tag/v0.0.1

```
autocmd InsertLeave * :call system('zenhan 0')
autocmd CmdlineLeave * :call system('zenhan 0')
```

**Comment by dian-yu-luo** [comment]
> @dian-yu-luo Hi, Thanks for this issue report. Are you having problems disabling the IME in command line mode?

yes ,I can disable on normal mode automatically by config  this 
```
DisableImeInNormal = true 
```
so ,could that auto convert by build-in configure when change to command-mode

**Comment by akiyosi** [comment]
@dian-yu-luo 
I have added a new option `ModeEnablingIME`. 
This allows you to specify the mode in which the IME is enabled. 
Try it out.

https://github.com/akiyosi/goneovim/actions/runs/2604591237


```
[Editor]
## This option specifies a list of modes in which the IME is to be enabled, and goneovim will enable
## the IME only in those modes.
## It may be useful for users who use the input method editor (e.g. East Asian users).
## e.g. 
## ModeEnablingIME = ["insert", "cmdline_normal"]
## The available mode strings:
##   "normal", "insert", "replace", "visual", "visual_select",
##    "cmdline_normal", "cmdline_insert", "cmdline_replace", etc.
# ModeEnablingIME = []
```
