### ISSUE TITLE
Allow Cmd+ and Cmd- to change font size?

### ISSUE THREAD

**Issue by mars0i** [akiyosi/goneovim#383]
In MacOS gvim, Cmd+ and Cmd- increase or decrease the font size, while keeping the same font in other respects.  (Would this be easy to implement in Goneovim?)  I don't know whether there are analogous keymappings that would make sense in other OSes.  Thanks-

**Comment by akiyosi** [comment]
@mars0i 
Hi :)
This functionality can be configured via vimscript or lua. The following is an example of lua configuration.
Note that the keynotation to be mapped needs to be adjusted depending on the keyboard language setting and the keyboard layout. 
For example, on my PC (Cmd, +) is conveniently mapped as `<D-;>`. This is because on my PC I need to press [shift]+[;] for +.

Also, the following settings are quite appropriately conceived, so there is a lot of room for improvement :P

``` lua
vim.keymap.set("n", "<D-+>", [[:lua guifontscale(1)<CR>]], { noremap = true })
vim.keymap.set("n", "<D-->", [[:lua guifontscale(-1)<CR>]], { noremap = true })
function guifontscale(n)
    if type(n) ~= "number" then
	return
    end

    local gfa = {}
    for c in vim.gsplit(vim.o.guifont, ":") do
        table.insert(gfa, c)
    end
    local buildnewgf = ""
    for k, v in ipairs(gfa) do
	if v:find("h", 1, true) == 1 then
	    fweight = ""
	    for w in vim.gsplit(v, "h") do
		if tonumber(w) == nil then
		    goto continue
		end
		wn = tonumber(w)
		wn = wn + n
		fweight = fweight .. tostring(wn)
		::continue::
	    end

	    buildnewgf = buildnewgf .. "h" .. fweight .. ":"
	else
	    buildnewgf = buildnewgf ..  v .. ":"

	end
    end

    local setcmd = "set guifont=" .. buildnewgf
    vim.cmd(setcmd)
end
```

**Comment by mars0i** [comment]
Thank you!  I had no idea about how to do this.  

This was the main thing that was still missing from Goneovim for me, so I'm very happy to have it working.

It turns out that on my Mac laptop Cmd-+ has to be entered as `<D-=>`. That makes sense since `+` is on the `=` key as the shift option.  That's actually the key that I have been pressing in MacOS gvim: Cmd-= , but it's easier to think of it as Cmd-+ .

**Comment by akiyosi** [comment]
@mars0i 
Glad to see that it worked well for you.
I have also integrated the wiki page you previously created into the following tips.

https://github.com/akiyosi/goneovim/wiki/Tips#how-to-make-goneovim-closer-to-macvim

**Comment by mars0i** [comment]
Ah, excellent.  Thanks!

**Comment by mars0i** [comment]
I realized that I should add a point.  What your Lua script does is not identical to what Cmd+ and Cmd- do in MacVim.  In MacVim, when Cmd+ increases the font size, the window size is increased as well.  And Cmd- also decreases the window size.  So the number of lines and columns stays the same as one uses Cmd+ and Cmd- (unless border hits the edge of the screen, and then that border doesn't expand any more).

I didn't mention that earlier because I think that what your Lua script does might be better.  I think it depends on the situation.

But in Wiki section about emulating MacVim, maybe it would be worth mentioning that the Lua script does something a little bit different from MacVim--maybe something better, in fact.  (I could add that text if you wanted it.)

**Comment by akiyosi** [comment]
@mars0i 
Thanks for pointing that out.
Perhaps an improvement to the lua script that more closely resembles the behavior of MavVim, or perhaps adding a note to the Wiki about the difference between the current lua script behavior and MacVim behavior would be a good idea.
Also, the Wiki is currently editable by any person, and I respect the ideas and contributions of those who edit the Wiki.

Perhaps a more straightforward implementation to achieve closer behavior would be to get the number of rows and columns in Neovim before the font size change and then perform `set lines`, `set colums` after the font size change?

**Comment by mars0i** [comment]
Yes, that all makes sense. 

Learning a tiny bit of nvim Lua so I can try that out ....

**Comment by mars0i** [comment]
Thanks @akiyosi.  I've been using a font with no spaces in the name, so I wouldn't have noticed yet.
