### ISSUE TITLE
lines and columns options can't be set inside lua function?

### ISSUE THREAD

**Issue by mars0i** [akiyosi/goneovim#386]
Hi @akiyosi,

I was interested in trying to follow up on your suggestion in #383 that one can wrap the `guifontscale` function (now in the wiki page) in `set lines` and `set columns` if one wanted to preserve the number of lines and columns when increasing or decreasing font size.  I'm wondering whether there is a problem with setting `lines` and `columns` from inside a lua function.  Maybe this has to do with how `set lines` and `set columns` were implemented in response to #334.

This is the first time I've written anything in lua, so I might be doing something wrong.

Here is one version of what I tried:
```lua
function guifontwinscale(n)
    local lins = vim.api.nvim_get_option('lines')
    print('before: ' .. lins)

    guifontscale(n)

    -- These don't have any effect:
    vim.o.lines = lins
    -- vim.cmd('set lines=' .. lins)
    -- vim.api.nvim_set_option('lines', lins)

    print('after: ' .. vim.api.nvim_get_option('lines'))

    -- For the sake of comparison, note that this works:
    if n == 1 then
       vim.o.wrap = true
    else
       vim.o.wrap = false
    end
end
```
If I run it like this, `:lua guifontwinscale(1)`, or this, `:lua guifontwinscale(-1)`, then `print(vim.api.nvim_get_option('lines'))` reports that the `lines` option has been restored to its earlier value.  However, the window size does not change, and after the function is run, `:echo &lines` reports a different number, because the font size has changed but the window size hasn't.  Using one of the other ways of setting the option (`vim.cmd`, `vim.o`) has the same result.

I've seen a similar problem with `columns`, but I haven't tested it as many ways.

**Comment by mars0i** [comment]
I meant to add that if I execute any one of the following within Goneovim at the colon prompt with "<an integer>" replaced by 40, or 30, etc., they work as expected: the dimensions of the window change:
```vim
    :lua vim.o.lines = <an integer>
    :lua vim.cmd('set lines=' .. <an integer>)
    :lua vim.api.nvim_set_option('lines', <an integer>)
```
It's only when these lines are called from a function that they have no effect.

**Comment by mars0i** [comment]
Thanks @akiyosi, @MuhammedZakir .  Yes, `testsetlines` works for me, too.  That's weird.  I'll experiment further.

**Comment by mars0i** [comment]
If instead of calling my function, I do the same thing by adding its contents separated by semicolons after `:lua `, the behavior is the same: print statements indicate that the number of lines is being preserved, but the window size doesn't change.  So the problem is not being embedded in a function.  It's as if `guifontscale` has a delayed effect, after the set lines command that runs after it, but I don't see why that makes any sense.

**Comment by akiyosi** [comment]
@mars0i 
After investigating, I found that it is behaving as if the lines change event is being overwritten by the guifont change processing event.

I tried several lua codes and confirmed that the following would work.

```lua
function guifontwinscale(n)
    local lines = vim.api.nvim_get_option('lines')
    local columns = vim.api.nvim_get_option('columns')

    guifontscale(n)

    vim.cmd('sleep 10m')
    vim.cmd('winsize ' .. columns .. ' ' .. lines)
end
```

**Comment by mars0i** [comment]
Thanks @akiyosi !  Interesting.  
This is much appreciated.

**Comment by mars0i** [comment]
I added a note about this to the Tips page.
