### ISSUE TITLE
Unable to find Windows setting.toml

### ISSUE THREAD

**Issue by xMithx** [akiyosi/goneovim#387]
`~/.goneovim/settings.toml` does not exist on my Windows 10 system and creating the folder and file manually does not effect Goneovim in anyway.

**Comment by xMithx** [comment]
Note: I used scoop to install both Neovim AND Goneovim

**Comment by akiyosi** [comment]
@xMithx 
Hi,
Are you using a version newer than nightly or 0.6.2?
If so, goneovim has changed the specification to look at `%XDG_CONFIG_HOME%\goneovim\settings.toml` on Windows as well.

**Comment by xMithx** [comment]
`$XDG_CONFIG_HOME` is a Linux standard. So I'm not sure where exactly you want me to search for this undocumented path on Windows 10....

**Comment by xMithx** [comment]
Honestly I'm just not going to bother. The fact that you don't even know where your Windows settings path is located shows the lack of care for the system. I'll just use goneovim for projects that don't require Windows, I hate working on it anyway. 

I am in no way trying to be mean, I honestly think you should just drop Windows support and focus your efforts on Linux. Windows users have to be like, 1% of your user base? Thanks for your time.
