### ISSUE TITLE
pum_getpos() seems to return wrong value for ext_popupmenu

### ISSUE THREAD

**Issue by acomagu** [akiyosi/goneovim#388]
When I see popup like this:

![image](https://user-images.githubusercontent.com/1362750/179259165-e460cd5f-7aaf-41cb-9c7a-ba7e4c12ca3d.png)

`pum_getpos()` returns such value:

![image](https://user-images.githubusercontent.com/1362750/179259045-a941acca-11b5-4f10-a56a-dece007e477a.png)

The values of `width`, `height` and `size` seems to be far from those of native pum.

![image](https://user-images.githubusercontent.com/1362750/179260920-3de59c4a-5a86-4976-8283-88da1273d84a.png)

![image](https://user-images.githubusercontent.com/1362750/179260904-6e61c465-c5d8-4702-9885-89421c5973e5.png)

I understand they won't be exact same value, but I guess `width` and `height` should be more smaller.

## Why I need this to be fixed

I use nvim-cmp as completion engine. When I use it with GoNeovim ExtPopupMenu, the floating window of documentation next to popup menu appears very narrow.

![image](https://user-images.githubusercontent.com/1362750/179262059-0c8eeb1d-1d26-4e91-8bf4-79b9c9b06b04.png)

This problem may be caused because the width value of `pum_getpos()` is wrong.

Thank you!

**Comment by acomagu** [comment]
@akiyosi I can see it's fixed! Thank you for your incredibly quick work!

**Comment by akiyosi** [comment]
@acomagu 
Also, I fixed a problem in 10fe882baf3 with external popupmenu where the menu parts would partially cover the icon display, as seen in your screen capture.

**Comment by acomagu** [comment]
@akiyosi Wow, you helped me a lot!! Thank you!
