### ISSUE TITLE
Is there a plan to support mouse selection?

### ISSUE THREAD

**Issue by epheien** [akiyosi/goneovim#39]
Such as the title.
Currently gonvim can not support mouse selection on macOS and Windows (I do not test on LInux).

**Comment by akiyosi** [comment]
Hi,
Gonvim supports mouse selection. The cause may be a conflict with your setting. Is it possible to mouse select even with `gonvim -u NONE`

**Comment by epheien** [comment]
I just test `gnovim -u NONE', but mouse selection still not work.
macOS High Sierra 10.13.6

**Comment by akiyosi** [comment]
I'm sorry, I got a late reply.

Let me confirm the word, is "mouse selection" intended for the feature of selecting text in neovim's buffer using mouse or touch pad?
If so, Gonvim supports that feature, and the bug can not be reproduced in my environment 😟
(My MacOS is the same 10.13.6 as you)

Please tell me the following.
* Setting contents of setting.toml
* The version of nvim you are using

**Comment by epheien** [comment]
```
[Editor]
# Editor minimum width (>= 800)
Width = 630
# Editor minimum height (>= 600)
Height = 630
# Editor font-family, font-size, linespace.
FontFamily = "Menlo"
FontSize = 12
Linespace = 0
# Gonvim copy the yank text to clipboad
Clipboard = false
# Editor cursor blink
CursorBlink = true
# Disable IME in Normal mode
#DisableImeInNormal = false
# start fullscreen
StartFullscreen = false
# load vimscript after setting of g:gonvim_running=1
GinitVim = '''
set guifont=Menlo:h12
'''
```
I just test -u NONE and mv settings.toml away, and test on nvim 0.4.0 and nvim 0.3.4
mouse selection always not works.
I use mouse, not touchpad.

**Comment by akiyosi** [comment]
Hmmm, weird.
Not reproduced at all in my environment.

If possible, could you debug the application?
The code implementing mouse selection is the following.

https://github.com/akiyosi/gonvim/blob/master/editor/screen.go#L431-L435

**Comment by epheien** [comment]
ok，I will try.

**Comment by epheien** [comment]
I found the reason, because I nnoremap mouse left click.

**Comment by eyalk5** [comment]
It doesn't support mouse selection at all in my case. Tried with `-u NONE`. I am on High Sierra. The mouse is a Logitech mouse with all the drivers.

**Comment by Zarainia** [comment]
Do you know what settings could cause it to not work, before I go scouring through my .vimrc? I have no problems with mouse selection in terminal or any other Neovim GUI.

**Comment by akiyosi** [comment]
@Zarainia 
Thanks for the comment.
I will continue to investigate and track this issue in another issue below.

https://github.com/akiyosi/goneovim/issues/297

**Comment by akiyosi** [comment]
@Zarainia 
I have fixed this probrem.
You can get the fixed binary from the following
https://github.com/akiyosi/goneovim/actions/runs/1598620554

**Comment by Zarainia** [comment]
I found the culprits -- tab and scrollbar plugins, which can definitely be disabled when using Goneovim because it implements both of those things. dstein64/nvim-scrollview and seblj/nvim-tabline were the specific ones.

**Comment by Zarainia** [comment]
It would be best to figure out why these cause issues, though.

**Comment by akiyosi** [comment]
@Zarainia 
Thanks for the report!

In response to your report, I have also investigated and confirmed that there is a pattern of omissions in the fix. However, as far as I can confirm, this pattern seems to be a little different from the behavior you reported in your last report. I have fixed the missing pattern, so to isolate the problem, could you please check the behavior with the following latest binary according to this fix?

https://github.com/akiyosi/goneovim/actions/runs/1607832574

Since the tablines and scrollbar in Goneovim are independent of the mouse selection, it is unlikely that alternative plug-ins would prevent the mouse selection function from working, so I think some kind of bug is involved.

**Comment by Zarainia** [comment]
I tested it and the results are the same -- without the plugins enabled, mouse selection works fine. With them, it doesn't select (dragging doesn't work).

**Comment by Zarainia** [comment]
Not super related, but I'm finding libmd4c.dll, libbrotlicommon.dll, and libbrotlidec.dll to be missing from these builds. I copied them from mingw, but it may be a problem for it being completely standalone.

**Comment by akiyosi** [comment]
@Zarainia 
Thanks for the confirmation. I will try to reproduce it in my environment using the plugin you are using.

> Not super related, but I'm finding libmd4c.dll, libbrotlicommon.dll, and libbrotlidec.dll to be missing from these builds. I copied them from mingw, but it may be a problem for it being completely standalone.

Yes, I've noticed that problem before, and I'm only making issues below, but I haven't gotten around to it... :P

**Comment by akiyosi** [comment]
@Zarainia 
I have identified the cause of this problem and fixed it.
Could you please check if it works in your environment?
https://github.com/akiyosi/goneovim/actions/runs/1611624161

**Comment by Zarainia** [comment]
Yep, it works! Thanks, everything looks good.

**Comment by akiyosi** [comment]
Thanks for confirming!
Closed.
