### ISSUE TITLE
Release artifact naming inconsistency for Linux

### ISSUE THREAD

**Issue by 13k** [akiyosi/goneovim#395]
Every release since 0.5.1 has a different naming format for Linux artifacts:

| release version | naming format | note |
| --- | --- | --- |
| 0.6.2 | `goneovim-v<version>linux.tar.bz2` | lowercase, version, no separator |
| 0.6.1 | `goneovim-v<version>-linux.tar.bz2` | lowercase, version, separator |
| 0.6.0 | `goneovim-linux.tar.bz2` | lowercase, no version, separator |
| <= 0.5.1 | `Goneovim-v<version>-linux.tar.bz2` | uppercase, version, separator |

This breaks every attempt at automating updates for tools like [huber](https://github.com/innobead/huber) or simple shell scripts. The usual workflow for such automatic updates is to fetch the latest release version via Github API and then guess the artifact name, usually based on a pre-defined format that you can interpolate the version into. So this process is completely broken if naming format changes for every single release.

**Comment by akiyosi** [comment]
@13k 
Thank you for pointing this out. I apologize for creating the release artifact in this state.
I have automated the generation of release artifacts with Github actions, so the file names are expected to be consistent in the future. 
Note that the missing hyphen in the most recent v0.6.2 release for Linux was a bug in the release script.

**Comment by 13k** [comment]
No need to apologize, thanks for understanding!
