### ISSUE TITLE
Scroll TUI application in NeoVim terminal

### ISSUE THREAD

**Issue by acomagu** [akiyosi/goneovim#401]
Goneovim doesn't seem to support scrolling of TUI application in the NeoVim terminal(instead it scrolls the terminal buffer). In Windows Terminal, it scrolls properly.

For example, fzf suggestions can be scrolled in Windows Terminal, but cannot in Goneovim.

https://user-images.githubusercontent.com/1362750/187858387-5e03c05a-772f-4711-ac4e-f5fc59ab5c81.mp4

I hope can scroll TUI application in Goneovim. Thanks!

**Comment by akiyosi** [comment]
@acomagu 
Hi :)
Thanks for reporting this issue.
The specifications related to this are being worked on by https://github.com/akiyosi/goneovim/pull/398.


I have added a fix to the branch in response to your report.
You can retrieve the artifacts from the following CI job.
Any feedback would be appreciated.

https://github.com/akiyosi/goneovim/actions/runs/2983352488
