### ISSUE TITLE
New user: line height; mousing in the text area

### ISSUE THREAD

**Issue by proofer** [akiyosi/goneovim#402]
MacOS 12.3.1, nvim 0.7.2

1) I have the same font family and size specified that I use in Terminal.app, but I'm getting ~3.5 more lines per window (63 versus ~57.5, same vertical space), indicating that the lines are closer together in goneovim. That makes it a little harder for me to read. Any way to adjust line height?

2) The text area is not responsive to the mouse; I can't select text nor use the scroll-wheel. I've enabled the scrollbar, and I can use the mouse to scroll that way. --EXCEPT if the command line is active, e.g., with a '/' search string; then the scroll bar just spews "jkjkjkjkjk..." into the command line. Yes, I've mapped 'jk" to '\<Esc\>' in insert mode. This is a minor issue.

(Until today I've been using nvim via Terminal, with an Applescript droplet app to open files. Previously I was using MacVim, but I want to use nvim. Now I'm hopeful that I will be able to use goneovim as my regular editor. Please let me know if there's a better place to ask dumb new-user questions!)

**Comment by akiyosi** [comment]
@proofer 
Hi, Thanks for this issue report.
All questions and opinions are welcome in this repository :)

1.  Line spacing can be adjusted with `linespace` option. e.g. `:set linespace=2`. 
2. The mouse can be controlled with `mouse` option, which can be enabled in all Vim modes as follows: `:set mouse=a`

**Comment by akiyosi** [comment]
Also, I am currently working on improving the scrolling functionality with the mouse in geneovim. 
If you are interested, please try this as well.
PR at work: https://github.com/akiyosi/goneovim/pull/398
Related Issue: https://github.com/akiyosi/goneovim/issues/401

**Comment by proofer** [comment]
@akiyosi I heard a rumor that your support of Goneovim was excellent; confirmed!

>     1. Line spacing can be adjusted with `linespace` option. e.g. `:set linespace=2`.
`=1`is perfect for me! (I note that `linespace` is absent from settings.toml.)

>     2. The mouse can be controlled with `mouse` option, which can be enabled in all Vim modes as follows: `:set mouse=a`
Ah! Using nvim with the Mac's Terminal.app I originally had `mouse=a` in init.lua but then commented that out as a "keyboard only" training exercise.  The mouse wheel still moved the cursor up or down, with "scrolling" when the cursor moved off screen.  I had forgotten about the `mouse=` setting.

>     Also, I am currently working on improving the scrolling functionality with the mouse in geneovim. If you are interested, please try this as well. PR at work: #398 Related Issue: #401
I'm happy with `mouse=a` but the mouse wheel scroll rate is maybe a bit slow. I'll look into the PR, and leave the issue open for now.

**Comment by proofer** [comment]
> PR at work: #398

With nightly-1-gccee4b8 the scrolling works fine but is still substantially slower than in nvim/Terminal.app. That is, substantially fewer lines scrolled per mouse wheel rotation amount.
