### ISSUE TITLE
Sidebar usage?

### ISSUE THREAD

**Issue by proofer** [akiyosi/goneovim#404]
So far, all I can do with the sidebar is click to unfold the root directory, and then double-click on a directory to open a netrw browser in the main window. I don't know of a way to access or use the sidebar with the keyboard. But I can open a netrw browser from the command line, so I don't need the sidebar for that. What am I missing?

**Comment by akiyosi** [comment]
@proofer 
As you understand. Currently, the sidebar has only a very simple feature.
One major point to note is that while goneovim has the ability to manage independent instances of nvim as [workspaces](https://github.com/akiyosi/goneovim/wiki/Usage#workspace), the sidebar is the only view that allows you to visually browse these independent workspaces.

**Comment by proofer** [comment]
OK. It'd be great to have a file browser in a sidebar that is accessible with the keyboard and from which a file could be opened into a window or tab of the current project (workspace?).

**Comment by akiyosi** [comment]
Yes. The sidebar displays multiple workspaces managed by goneovim.
 New workspaces can be created with `:GonvimWorkspaceNew` command.
