### ISSUE TITLE
[Feature Request] hide cursor when typing

### ISSUE THREAD

**Issue by Marskey** [akiyosi/goneovim#407]
OS: macos
Goneovim-version:0.6.3
this is fastest gui that i've used, i love it, Appreciate your effort

**Comment by akiyosi** [comment]
@Marskey 
Hi, Glad you liked it.
And thanks for this issue report.
I would like to know a little more about your issue.

1. You say that the cursor disappears while typing, does the problem occur with `/path/to/goneovim -u NONE` ?

2. if the problem does not occur with 1. please let me know your neovim configs.

**Comment by Marskey** [comment]
Oh, my mistake, this is not a issue, it's a feature that i want it.

**Comment by Marskey** [comment]
Neovide has a option `let g:neovide_hide_mouse_when_typing = 1` i really like it, but Neovide is good tool but not faster than yours. can you add this options?

**Comment by akiyosi** [comment]
I understand the details of the requested feature.
I think it is useful and I have added it to the goneovim.
You can try the feature with the following CI job.

https://github.com/akiyosi/goneovim/actions/runs/3022868955


You can activate the feature by putting the following in settings.toml

``` toml
[Editor]
# ...
HideMouseWhenTyping=true
```

**Comment by Marskey** [comment]
sorry for taking your time，i missed it

**Comment by Marskey** [comment]
Thank your
