### ISSUE TITLE
Add mimetypes intot the desktop file

### ISSUE THREAD

**Issue by gi1242** [akiyosi/goneovim#409]
Could you add mimetypes into `goneovim.desktop`, so that desktop environments know goneovim can open text files?

For instance `nvim-qt` uses:

    MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;

**Comment by akiyosi** [comment]
@gi1242 
Hi :)
Ummm, How do you install goneovim?
goneovim stores a desktop file in the repository for the user's reference, and mime is defined there.
https://github.com/akiyosi/goneovim/blob/master/cmd/goneovim/goneovim.desktop

If you are installing using some package manager, it may be a problem with the goneovim installation script on the package manager side.

**Comment by gi1242** [comment]
Oof. Yes, you do it right. I gotta trace the error down. I'm using `Arch` and installed using AUR. I'll report it there, thanks.
