### ISSUE TITLE
Bug: Weird Visual artifacts

### ISSUE THREAD

**Issue by keefle** [akiyosi/goneovim#41]
Sometimes  after searching then ':nohlsearch', some leftover artifacts appear, which disappear after moving over them. 

![Sun_17-03-19-19:46:00](https://user-images.githubusercontent.com/45905717/54494691-1dbf3f80-48ee-11e9-9cea-3afde5cfbbeb.png)

Reproducing isn't consistent.

**Comment by akiyosi** [comment]
Hi, 
I also happen this event sometimes.
Perhaps it's a drawing problem on the qt side, but I'll see if the application can work around it.
