### ISSUE TITLE
Window is not visible with BorderlessWindow = true in goneovim-windows

### ISSUE THREAD

**Issue by shiena** [akiyosi/goneovim#412]
- os: Windows10
- paltform: goneovim-windows
- version: https://github.com/akiyosi/goneovim/actions/runs/3076351432

Setting `[Editor]/BorderlessWindow = true` in goneovim-windows makes the window transparent. However, in the following situations, the window will not become transparent and will be displayed.
- Maximize window (`:GonvimMaximize`)
- Set `[Editor]/Transparent` to less than 1

https://user-images.githubusercontent.com/1295639/190911796-70e5706a-4734-4548-b1ad-b41a456f0c64.mp4

**Comment by akiyosi** [comment]
@shiena 
Hi, Thanks for this isssue report. It is a very weird issue.

The version you pointed out simply adds the MSVC build to CI, so the code of the Goneovim itself is essentially unchanged. 
Have you confirmed this issue with the MSVC build for example?

**Comment by shiena** [comment]
@akiyosi 
MSVC builds show normal windows.
But I can't resize the window because the mouse cursor doesn't change at the edge of the window.
Also, both the mingw and msvc builds have larger font sizes than the current nightly.


https://user-images.githubusercontent.com/1295639/190920981-65180647-b3a6-4340-aa2e-2bb02ee3e5a1.mp4

**Comment by shiena** [comment]
When I turned on the compatibility mode from the properties, a window was displayed.
![image](https://user-images.githubusercontent.com/1295639/190941242-4b5bcc84-a09c-436b-bc4b-b978c92c03c8.png)

**Comment by shiena** [comment]
I had the same problem on windows11.

**Comment by akiyosi** [comment]
Thank you for these information.
It is very helpful.
Is this problem not present in versions earlier than https://github.com/akiyosi/goneovim/actions/runs/3076351432 ?

**Comment by shiena** [comment]
I checked the old artifacts in the master branch.
There is a problem from the following versions.
https://github.com/akiyosi/goneovim/actions/runs/2854083067
Maybe the build environment is different between CI and release?

**Comment by akiyosi** [comment]
@shiena 
Thanks for the info. Very helpful.
I think the cause was that the build was based on an older Qt version.

By the way, does the 0.6.3 release artifact not retain this issue? 
In the release artifact generation script, the Windows binaries have a build procedure using a Docker container for builds, but I am thinking that the version of the Qt library contained in this Docker container is still old.

**Comment by shiena** [comment]
@akiyosi 
I'm glad it was resolved.
No problem with the 0.6.3 release artifact.
