### ISSUE TITLE
Bug: `cmd+q` does not work on mac

### ISSUE THREAD

**Issue by chrisgrieser** [akiyosi/goneovim#416]
`cmd+q` does not work at all on Mac. Closing via the close button or via the menubar → quit `goneovim` work though. (`cmd+q` seems to get captured though, since mapping `<D-Q>` to `:q!` also does not work.)

**Comment by chrisgrieser** [comment]
(also, might I add how ironic this is, that *you cannot quit goneovim until you use `:q!`* 😆 )

**Comment by akiyosi** [comment]
Hi,
This issue was duplicated.
See https://github.com/akiyosi/goneovim/issues/133#issuecomment-640020701
