### ISSUE TITLE
`HideMouseWhenTyping` and `RestoreWindowGeometry = false` do  not work

### ISSUE THREAD

**Issue by chrisgrieser** [akiyosi/goneovim#418]
I found this nice hidden feature to hide the mouse when typing in #407. The feature does not work on my end 😕 

`RestoreWindowGeometry = false`, too, does not seem to work for me.

**Comment by akiyosi** [comment]
Please tell us the following about your goenovim

* The result of `/path/to/goneovim --version`
* The location where you put your settings.toml
