### ISSUE TITLE
`<S-Space>`, `<C-i>` etc. are not recognized

### ISSUE THREAD

**Issue by chrisgrieser** [akiyosi/goneovim#419]
Keys that a terminal has trouble recognizing (e.g. Shift-Space, differentiating between ctrl-i and tab) *should* work inside a GUI. However, with goneovim, it seems they are not supported, like in the Terminal, which is a bit of a bummer since the ability to use those keys is one of the reasons people choose to use a GUI

**Comment by damanis** [comment]
<C-i> and <Tab> are different for me (but, <C-i> works like in vim, not in neovim).
But <C-i><C-i> and <Tab><Tab> are same. Also in others nvim GUI I tested (nvui, fvim, nvim-qt, neoray).
For example, [this bookmarks plugin](https://github.com/crusj/bookmarks.nvim) uses <Tab><Tab> to open bookmarks list - in all GUIs above <C-i><C-i> opens it too.
