### ISSUE TITLE
Auto-Completion Popups are sometimes empty

### ISSUE THREAD

**Issue by chrisgrieser** [akiyosi/goneovim#420]
Here is the autocompletion popup from coc.vim in the terminal:
<img width="50%" alt="Pasted image 2022-10-04 00 14 10" src="https://user-images.githubusercontent.com/73286100/193695564-157be19f-0181-4641-bd3a-960820799878.png">

and here it is in goneovim
<img width="50%" alt="Pasted image 2022-10-04 00 10 54" src="https://user-images.githubusercontent.com/73286100/193695741-66a91a50-9672-4ba1-bb98-365d03e89628.png">

same location, same file, same letter as trigger.

The bug mostly seems to occur at the beginning of a word.

---

I tried it with `ExtPopupmenu = true` and with `false`, the setting does not seem to have any effect and the bug occurs with both.

**Comment by akiyosi** [comment]
@chrisgrieser 
Hi :)
Perhaps this problem does not occur in the latest version.
If it occurs again, please reopen the issue
