### ISSUE TITLE
The frame is displayed even if borderless is enabled in nightly-1-g5deb344

### ISSUE THREAD

**Issue by shiena** [akiyosi/goneovim#424]
# environment

OS: Windows11 Pro 22H2
version: nightly-1-g5deb344

## BorderlessWindows = true in nightly

<img width="433" alt="image" src="https://user-images.githubusercontent.com/1295639/202839211-1d35a55c-9684-43a1-bcf8-e5771f325ca2.png">

## BorderlessWindows = false in nightly

<img width="401" alt="image" src="https://user-images.githubusercontent.com/1295639/202839229-5c2f1ac1-1a5a-40e6-afc3-ef4f4974dd56.png">

## BorderlessWindows = true in goneovim v0.6.3

<img width="402" alt="image" src="https://user-images.githubusercontent.com/1295639/202839289-06116d53-f81b-4d26-8b4d-29625cd02574.png">

## BorderlessWindows = false in goneovim v0.6.3

<img width="390" alt="image" src="https://user-images.githubusercontent.com/1295639/202839334-654b3b5a-9df8-44f7-ab58-9d0b722c35b7.png">

**Comment by shiena** [comment]
The previous nightly version looks the same as v0.6.3.
https://github.com/akiyosi/goneovim/actions/runs/3425121992

**Comment by shiena** [comment]
Fixed in nightly-1-g508947c.

**Comment by akiyosi** [comment]
@shiena 

Thanks for this report.
The problem was a bug in the most recent changes to goqtframelesswindow on which gooneovim depends.

I am glad to hear that it has been fixed.

On the other hand, I noticed a problem with the borderless window no longer having a shadow. I am investigating this.
