### ISSUE TITLE
Artifacts on last stable release have version marked as nightlly instead of matching tag

### ISSUE THREAD

**Issue by alerque** [akiyosi/goneovim#429]
The binary artifacts attached to [v0.6.4](https://github.com/akiyosi/goneovim/releases/tag/v0.6.4) all have `-nightly` instead of `-v0.6.4` segments in the file name as previous releases did.

**Comment by akiyosi** [comment]
Sorry for the trouble.
It seems that the version tag in the release job is returning nightly instead of v0.6.4.
This is a bug in the release script, but I am not sure of the cause at this time.
I will continue to investigate.

**Comment by akiyosi** [comment]
I have fixed the release and will close this Issue.
