### ISSUE TITLE
github.com/therecipe/qt is not updated anymore

### ISSUE THREAD

**Issue by Ptkatz** [akiyosi/goneovim#432]
The github.com/therecipe/qt project has not been updated for two years, and the author does not know where he is. Can you contact the author of this project?

**Comment by akiyosi** [comment]
@Ptkatz 
I also cannot contact the author.
I am aware that `github.com/therecipe/qt` project has not been updated for a long time, but the project has no major problems with Qt5. Therefore, I believe that goneovim can be maintained in its current structure until 2025, which is the EOL for Qt5.

On the other hand, we think it is necessary to consider the direction after 2025. For example, it is possible to fork therecipe/qt to support Qt6.
