### ISSUE TITLE
Unable to find settings.toml

### ISSUE THREAD

**Issue by ricoshett** [akiyosi/goneovim#433]
I extracted .zip file from Releases and there's no settings.toml file. The extracted folder looks like this: 
![image](https://user-images.githubusercontent.com/93671911/213887333-b7a1d64c-ad3f-4c94-8469-6b3d1c1eb86c.png)
Where is settings.toml located?

**Comment by akiyosi** [comment]
Thanks for this issue report :)

See https://github.com/akiyosi/goneovim/wiki/Usage#configuration

**Comment by akiyosi** [comment]
You need to create path and file.
