### ISSUE TITLE
goneovim window does not close with latest neovim releases

### ISSUE THREAD

**Issue by damanis** [akiyosi/goneovim#434]
Steps to reproduce:

- Download [Nvim development (prerelease) build](https://github.com/neovim/neovim/releases) and install it
- open any file in goneovim
- make change, then `:wq`

**Expected**: file saved, then goneovim closed
**Problem**: goneovim window isn't closed. The neovim process (ps ax) does not exist, but goneovim process still exists.

It is not goneovim specific, nvui also has it, but not nvim-qt. Seems, something changed in nvim API.

**Comment by akiyosi** [comment]
Hi, Thanks for this issue report.
I cannot reproduce the problem on my machine using the steps you provided.
I think the problem may be related to a specific plugin.

Is the problem reproducible with the following steps?

* Run goneovim with the following
  ```
  /path/to/goneovim -u NONE /path/to/file
   ```
* make change, then :wq

**Comment by damanis** [comment]
@akiyosi 
You right, it works without plugins. Strange that same plugins used with neovim-qt without any problem.
I will check my plugins.
P.S. Will you add binaries for Ubuntu 20.04 (older libc)?

**Comment by akiyosi** [comment]
@damanis 
Thanks, it would be useful to know which plugins are affecting the problem.

> P.S. Will you add binaries for Ubuntu 20.04 (older libc)?

Would this one work?

https://github.com/akiyosi/goneovim/actions/runs/3992430747

**Comment by damanis** [comment]
@akiyosi 
The problem plugin is [galaxyline](https://github.com/glepnir/galaxyline.nvim).

> Would this one work?
https://github.com/akiyosi/goneovim/actions/runs/3992430747

Yes, this image works.

**Comment by akiyosi** [comment]
@damanis 
Thanks for info!

In other words, am I correct in understanding that the problem is reproduced in your environment by the following steps?

1. Run goneovim with the following
    ```
    /path/to/goneovim -u NONE --cmd 'set clipboard=unnamed' /path/to/file
    ```
2. make change, then :wq

**Comment by damanis** [comment]
@akiyosi 
Yes, these steps cause the problem.

**Comment by akiyosi** [comment]
@damanis 
I have tried to reproduce the problem on my MacOS, archlinux and pop!os machines, but have not been able to reproduce it at this time.

I am thinking that perhaps it has something to do with the clipboard provider. What is the neovim clipboard provider on your system?
Reading `:h provider-clipboard`, it seems that on Linux, there are `wl-copy`, `wl-paste`, `xclip`, etc.

**Comment by damanis** [comment]
@akiyosi 
Since commit `b042f6d90` neovim prefer `xsel`. I have it installed.

**Comment by damanis** [comment]
@akiyosi 
I see `/usr/bin/xsel --nodetach -i -p` in `ps ax ` output when goneovim exits. This command tries copy selection to primary buffer, but, seems, the selection is empty. If double click (i.e., select something) on any word, for example, in a terminal, goneovim immediately exits.

**Comment by damanis** [comment]
@akiyosi 
May be this will help you.
The workaround clears primary selection buffer before exit. It is default behavior in `vim` (as I know, it according freedesktop specification), but changed in `neovim`.
```
if vim.g.goneovim then
  -- Workaround: clear primary before exit
  vim.api.nvim_exec([[
    :autocmd VimLeavePre * call setreg('*', [])
  ]], false)
end
```

**Comment by akiyosi** [comment]
@damanis 
Thanks for the info. What are your `settings.toml` settings?

**Comment by akiyosi** [comment]
@damanis 
goneovim adds the following settings if `Clipboard = true` and the default value is `true`

https://github.com/akiyosi/goneovim/blob/d91125000f3aa70b1d34a08a8c8a963b05b5d813/editor/workspace.go#L766

If this clipboard setting is enabled, Goneovim will copy the yanked text to the clipboard using https://github.com/atotto/clipboard; on Linux, this copying seems to be done using `xsel`.

Perhaps you can work around this problem by adding the following to settings.toml It is arguable whether the default value should be true or false.

```
[Editor]
# Copy yanked text to clipboard
Clipboard = false
```

**Comment by damanis** [comment]
@akiyosi 

I have `clipboard = false` in `~/.config/goneovim/settings.toml` - it doesn't help.

I compared `goneovim` and `nvim-qt` behavior on exit by `execsnoop-bpfcc` (it show `execv` calls): `goneovim` calls `/usr/bin/xsel --nodetach -i -p` at exit, while `nvim-qt` doesn't, so it doesn't stuck.
`nvim-qt` doesn't touch primary selection, so previously copied content exists in primary selection after `nvim-qt` exit.

**Comment by damanis** [comment]
@akiyosi 

As I understand, `clipboard` module copy `primary selection` to `clipboard`. This is another action, not what `xsel --nodetach -i -p` does: the `xsel` call copies nvim's `*` register to `primary selection`.
I think the problem causes, because of `nvim` process already exited, so `*` register isn't accessible. The proper behavior, seems, is do not call `xsel` at exit like `nvim-qt` does.

**Comment by akiyosi** [comment]
@damanis 
Can you post the file contents of your settings.toml?

**Comment by damanis** [comment]
```
[Editor]
WindowGeometryBasedOnFontmetrics = true
IgnoreFirstMouseClickWhenAppInactivated = false
Width = 900
Height = 780
LineToScroll = 3
FontFamily = "GoMono Nerd Font Mono"
FontSize = 11
ExtPopupmenu = true
CachedDrawing = true
DisableLigatures = false
Clipboard = false
[Cursor]
SmoothMove = false
[Palette]
[Message]
[Statusline]
Visible = false
[Tabline]
Visible = false
[Popupmenu]
[ScrollBar]
Visible = false
[MiniMap]
Disable = true
[Markdown]
Disable = true
[SideBar]
Visible = false
[FileExplore]
[Workspace]
RestoreSession = false
```

**Comment by akiyosi** [comment]
@damanis 
Thank you. I have identified the direct cause code. I am looking into ways to resolve the issue.

**Comment by akiyosi** [comment]
Ummm, It seems to be the cause is that the following autocmd.
But I have no idea why this autocmd causes such problems...

https://github.com/akiyosi/goneovim/blob/eb1ed9b5ad0e581202bfecf88616a33672ef93e8/editor/workspace.go#L753

I believe you can confirm that the problem does not occur by executing the following command to override the above autocmd after starting goneovim.

```
:aug Goneovim | au! | aug END
```

**Comment by damanis** [comment]
After start goneovim, I entered `:aug Goneovim | au! | aug END`, then make changes and `:wq` - problem reproduced.

**Comment by akiyosi** [comment]
Really?
The problem does not reproduce in my Linux environment.
I don't understand it even more. I will continue to investigate.

**Comment by damanis** [comment]
Tested again - reproduced. `Goneovim` waits until `xsel` exits as written above. Workaround with clearing `*` register works.

**Comment by akiyosi** [comment]
Could you reproduce the problem with the following binaries?

https://github.com/akiyosi/goneovim/actions/runs/4134917312

**Comment by damanis** [comment]
Yes, reproduced, also after `aug` command you provided.

**Comment by akiyosi** [comment]
@damanis 
Thanks for confirming.
Hmmm, so the problem I was able to reproduce in my environment and the problem in yours is the same problem, but the cause is slightly different.

If I run both of the following commands in your environment, do you reproduce the problem? This will disable all autocmd's that Goneovim needs, so Goneovim may not work properly, but it will isolate the problem.

```
:aug Goneovim | au! | aug END
:aug GoneovimCore | au! | aug END
```

**Comment by damanis** [comment]
@akiyosi 
I tested on Ubuntu 22: after `goneovim` started, I entered two commands your provided - problem reproduced.
It possible, that the problem not in `goneovim` hooks, but in QT code: may be, it need to configure some QT option. I tried find something in `neovim-qt` code (it works with new `nvim` releases), but didn't find any yet.

**Comment by akiyosi** [comment]
@damanis 
The contents of the commit on the neovim side that triggered this problem may tell us something.
Do you know the hash value of the commit?

**Comment by damanis** [comment]
@akiyosi 
I'm not sure what exactly commit. I thought it is `b042f6d9022`, but it too old, after it was no problem.
I see problem only in GUI uses QT (excluding neovim-qt), all other neovim GUI works properly.

**Comment by damanis** [comment]
@akiyosi 
I found that problem `xsel` process ran by `jobstart` command from
runtime/autoload/provider/clipboard.vim (from neovim package):
```
let jobid = jobstart(selection.argv, selection)
```

**Comment by akiyosi** [comment]
@damanis 
Thanks for this info.
I noticed that a change directly related to clipboard is trivial on the commit history in neovim repo.
The changes in `clipboard.vim` seems to be included in this kind of changes.
I will make time to investigate with bisect.

```
b042f6d	2022-11-07 11:46 +0800	wzy                  	fix(clipboard): prefer xsel #20918
ef1d291	2022-11-09 16:21 -0700	Gregory Anders  	fix(clipboard): update version regex pattern (#21012)
fdeb20d	2022-11-18 15:39 +0000	XDream8         	feat(clipboard): added wayclip support (#21091)
5529b07	2023-01-04 07:17 +0800	zeertzjq            	fix(clipboard): show provider warning when not during batch changes #21451

```

**Comment by akiyosi** [comment]
@damanis 
Here is a follow-up report on the survey results.
I have identified the neovim commit where this problem began to occur as https://github.com/neovim/neovim/commit/1d16bba4d8b8b648d2dabd610924bcf3051a0f29.
I have also identified the code for the problem on the Goneovim side.

I am currently working on a fix.

**Comment by damanis** [comment]
@akiyosi 
Great news! How did you find it?
I also detect that same problem with `+` buffer (system clipboard). Seems, fix will solve all, the difference only in `xsel` parameters: `xsel --nodetach -i -b` instead of `xsel --nodetach -i -p`.

**Comment by akiyosi** [comment]
related: https://github.com/neovim/go-client/issues/153

**Comment by akiyosi** [comment]
@damanis 
This problem has not yet been fundamentally resolved.

On the other hand, with the most recent fix, goneovim has begun to provide its own clipboard provider(7b7aeb4db2)
This makes it possible to work around this problem by setting `Clipboard=true` in `settings.toml`.

**Comment by damanis** [comment]
@akiyosi 
Yes, I tested it.
Note, that goneovim own clipboard provider does not provide all required API now, so some extensions, such as `yanky`, cannot work.
Currently, I prefer workaround with clearing `*` and `+` buffers on exit.

**Comment by damanis** [comment]
> related: [neovim/go-client#153](https://github.com/neovim/go-client/issues/153)

Did last commits in `go-client`, at 19 and 20 Jun, solve the problem?

**Comment by akiyosi** [comment]
related: https://github.com/neovim/neovim/issues/26743

**Comment by damanis** [comment]
> related: [neovim/neovim#26743](https://github.com/neovim/neovim/issues/26743)

Yes, cross-reference :). It was opened by [neovide](https://github.com/neovide/neovide) author after I wrote him with references to your exploring.

**Comment by damanis** [comment]
@fredizzimo reported that the issue fixed in neovim. Last `neovide`, 0.13.0 works properly with clipboard.

**Comment by damanis** [comment]
I tested with neovim 10 release — the problem is not reproduced. Seems, the [go-client issue](https://github.com/neovim/go-client/issues/153) also may be closed.

**Comment by akiyosi** [comment]
@damanis 
Thank you! This issue is now closed.
