### ISSUE TITLE
set keymap with `alt` key as prefix does not work

### ISSUE THREAD

**Issue by liaohui5** [akiyosi/goneovim#438]
## question intro
`<M-*>` does not work

## environment

+ OS: MacOS 13.1
+ neovim: v0.8.3
+ goneovim: 0.6.4

## cnofig files
+ ~/.config/goneovim/settings.toml

```toml
# load lua config
Ginitvim = '''
lua << EOF
require("goneovim")
EOF
'''
```

+ ~/.config/nvim/goneovim.lua

```lua
local keymap = vim.api.nvim_set_keymap;
local option = {
  noremap = true,
}

-- working
keymap("n", "<C-t>", "<cmd>lua print('111')<CR>", option);


-- not woring
keymap("n", "<M-t>", "<cmd>lua print('222')<CR>", option);
```

Do you need more information?

**Comment by akiyosi** [comment]
Hi,
Thanks for the issue report.
Goneovim does not allow M-mapping by default in Mac OS. (Note that the Alt key prefix is A- in Goneovim.)
To use it, you must set `Macmeta` to `true` in settings.toml. In a launched instance, the settings can be controlled with `GuiMacmeta [0|1]`.

**Comment by akiyosi** [comment]
I have looked into a few past cases, and it seems that controlling at the MacOS configuration level is also effective.

https://github.com/equalsraf/neovim-qt/issues/579#issuecomment-666915803

**Comment by liaohui5** [comment]
> Hi, Thanks for the issue report. Goneovim does not allow M-mapping by default in Mac OS. (Note that the Alt key prefix is A- in Goneovim.) To use it, you must set `Macmeta` to `true` in settings.toml. In a launched instance, the settings can be controlled with `GuiMacmeta [0|1]`.

Thank you very much!
