### ISSUE TITLE
[Feat request] Support line padding without messing up glyphs

### ISSUE THREAD

**Issue by pro-anon** [akiyosi/goneovim#442]
This is how kitty looks like with `modify_font cell_height 200%`
![image](https://user-images.githubusercontent.com/97809837/223449682-4827e1b2-f533-4b2f-b7ae-70ddfbafa3b5.png)

This is how goneovim looks like after setting `linespace=20`
![image](https://user-images.githubusercontent.com/97809837/223450076-3e362814-84fb-4d47-8e4d-d291fbb53d92.png)

**Comment by bfulop** [comment]
In my understanding, this is a feature unique to Kitty. It will scale up certain glyphs (e.g. vertical separator line) to be 100% "line height".

**Comment by pro-anon** [comment]
I think so yeah. This is how VS Code looks like if you set the `"editor.lineHeight"` to `38` to add some padding.

![image](https://user-images.githubusercontent.com/97809837/223735638-0ce9823a-816c-4ed3-9f09-07736bd5b704.png)

I don't think it stretches out the unicode symbols? But it's not a terminal app so maybe they have more flexibility in their rendering so that they can increase the line padding without affecting the text inside each line.


A workaround that I've found is using `vim.g.goneovim` flag to change my separator glyph. But stuff like the telescope menu look a bit weird.

![image](https://user-images.githubusercontent.com/97809837/223734541-6ac818b0-f0bb-41e9-af73-2ca860f74788.png)

**Comment by akiyosi** [comment]
Hi, Thanks for this issue report :)
I believe it is possible to scale specifically for some glyphs in goneovim as well.
I will try it.

**Comment by akiyosi** [comment]
https://github.com/akiyosi/goneovim/actions/runs/4392964666

I have implemented this feature as a trial, please try it out.
Any feedback would be appreciated.

**Comment by bfulop** [comment]
Thank you @akiyosi for working on this! 

I always wished to have this feature exist in Goneovim!

The glyph vertical scaling is already looking great in the test build. 🎉 

There are a few issues I noticed:

1. the biggest issue is that the letter `a` is replaced by some different font (I'm using `Iosevka Term` font)


<img width="279" alt="CleanShot 2023-03-12 at 10 50 40@2x" src="https://user-images.githubusercontent.com/1718128/224537575-e774abe7-9e83-4482-9da2-b8b02f490182.png">

2. There's some gap in the left pointing triangle:

![CleanShot 2023-03-12 at 10 51 56@2x](https://user-images.githubusercontent.com/1718128/224537601-784c7ebe-eebe-4add-8193-53e996bc0bf2.png)

3. The border edges don't align (e.g. in telescope):
4. 
![CleanShot 2023-03-12 at 10 51 24@2x](https://user-images.githubusercontent.com/1718128/224537645-c7103688-0c1d-44c5-a0ed-71cf4c0fbc44.png)

Thanks again for working on this! ❤️

**Comment by pro-anon** [comment]
Same issues as @bfulop
![image](https://user-images.githubusercontent.com/97809837/224560853-f76b5ee8-446a-46a8-a619-19f836c77935.png)
![image](https://user-images.githubusercontent.com/97809837/224560866-644a6089-a1bd-4f4f-b144-30f323933afe.png)
With a different font:
![image](https://user-images.githubusercontent.com/97809837/224561043-d63983f1-3499-4ed7-8f4e-a09ff24747cf.png)

**Comment by akiyosi** [comment]
@pro-anon @bfulop 

I have updated this feature.

https://github.com/akiyosi/goneovim/actions/runs/4397528120

The "a" character was being scaled because the "a" character was also scaled in the implementation for testing purposes.
In this new feature, the character to be scaled can be set in the configuration file `settings.toml`.
The default setting is as follows

<img width="655" alt="2023-03-13 22 56 12" src="https://user-images.githubusercontent.com/8478977/224723110-c1bcf992-56d9-4f76-a212-a77a75fb6014.png">

**Comment by bfulop** [comment]
Thank you so much, that was fast! It's looking great on my machine!

I can now remove the `DrawWindowSeparator` option from config. 🎉 
The only reason I had it on was to have the continous separator line between splits.

**Comment by bfulop** [comment]
Hello @akiyosi ,

I was wondering if this feature could be included in the nightly releases?

I tested previous nightlies and did not see this applied. I just tried testing it again with the [currently latest nightly](https://github.com/akiyosi/goneovim/commit/f3a185199b46e692a954af04aba1703d38af782a) but this release does not open on my Mac.

**Comment by akiyosi** [comment]
@bfulop 
This has not yet been merged.
This change may have a slight performance impact and I am reviewing it closely.

**Comment by akiyosi** [comment]
merged.
