### ISSUE TITLE
render error

### ISSUE THREAD

**Issue by Marskey** [akiyosi/goneovim#445]
![image](https://user-images.githubusercontent.com/13499986/225268380-aac5a046-e13d-4b4d-aab0-06c92770e937.png)
when i scroll the screen.

**Comment by akiyosi** [comment]
@Marskey 
This problem was fixed in 0940c68153f059e77f74a6026d70a4bc058e1714

You can get the fixed binaries from:
https://github.com/akiyosi/goneovim/actions/runs/4582145623/jobs/8092171090
