### ISSUE TITLE
Feature Request: Own window separator

### ISSUE THREAD

**Issue by Mariappan** [akiyosi/goneovim#45]
Since neovim supports external window management, do you have plans to add this support in gonvim ?

Also floating window support and virtual text support

**Comment by akiyosi** [comment]
HI,

I plan to add the feature in v0.4.0.
But those features, the floating window and the virtual text should be work in the current version as well.

**Comment by Mariappan** [comment]
May be not in the remote attachment ?

I tried to use git-p.nvim plugin which seems to work in terminal version. But with gonvim in remote attachment, it does not seems to work 🤔

**Comment by akiyosi** [comment]
Umm..., I do not use those features in remote attachments. 🤔 
I will check.

**Comment by akiyosi** [comment]
In passing, is remote nvim using 0.4.0?

**Comment by Mariappan** [comment]
Yes it is 
`NVIM v0.4.0-430-g8698830cb                                                                                                                                                                                                                                          
Build type: RelWithDebInfo
LuaJIT 2.0.5`

**Comment by akiyosi** [comment]
I checked the feature; the floating window and the virtual text with the remote attachment and confirmed that it works.
I did not work well the `git-p.nvim`.
Instead I checked with `Shougo/deol.nvim` and `w0rp/ale`.

**Comment by Mariappan** [comment]
@akiyosi I am seeing there are some checkins in the **multi-grid** branch. 
Is it in workable condition?
Any chance I get a linux binary to test 😃

**Comment by akiyosi** [comment]
@Mariappan 
Yes, It is work with nvim v0.4.0.
But currentry, there is a bug. See https://github.com/neovim/neovim/issues/9899

**Comment by Mariappan** [comment]
Cool @akiyosi  
Can you please share the linux zip then ? 
I can start testing. I dont use tabs much so it wont impact me much

**Comment by akiyosi** [comment]
Ummm, 
Is it possible to build on your machine?
I think it is not at the stage that can share the binary yet.😥
There are still bugs in neovim's Multigrid UI, and the implementation policy on the GUI side has not been clearly obtained.

**Comment by Mariappan** [comment]
@akiyosi 
After some boring stuff, compiled successfully the multigrid branch.
And I found the reason for the window close problem too. Raised a PR to fix it.

https://github.com/akiyosi/gonvim/pull/55

Once you verify this fix, you can close the https://github.com/neovim/neovim/issues/9899

**Comment by Mariappan** [comment]
This multigrid-branch is pretty much usable. I am using for half an hour and it looks fine.

One compelling thing needed urgently is to implement the window separators for horizontal and vertical split. It looks aweful

**Comment by akiyosi** [comment]
@Mariappan 
Thank you very much.
Perhaps it was added in the debugging of `Multigrid UI` events in old commit of nvim.😅

> One compelling thing needed urgently is to implement the window separators for horizontal and vertical split. It looks aweful

I think the window separator is equivalent to the original vim at present, is it so aweful?

**Comment by Mariappan** [comment]
<img width="824" alt="Screenshot 2019-05-15 at 12 45 56 AM" src="https://user-images.githubusercontent.com/947300/57725467-d4e7f500-76aa-11e9-9598-44daa5a25537.png">
Please take a look 😢

**Comment by akiyosi** [comment]
Umm, ok.
I will consider 😁

**Comment by akiyosi** [comment]
I made minimal changes to draw window separators now 31ad7c52b
I want your opinion.

**Comment by Mariappan** [comment]
Thanks @akiyosi. I have tried your changes and it looks fine.
In vertical separator, the file name is shown which has to be removed, which i believe, you will fix it in the further updates.

I have one doubt, are we not creating separate windows, for splits ?
Are we using same one window for all the splits and just drawing the line to create/visualise the splits. 
Sorry I don't understand the design

**Comment by akiyosi** [comment]
@Mariappan 
Currently, gonvim creates a window-widget for each neovim window.
In the [Multigrid UI](https://neovim.io/doc/user/ui.html), the window separator(and file name, ruler info in the statusline) is notified as an grid-event with a special grid ID 1, and the current separator implementation is drawing for window widget with a grid ID 1.

**Comment by Mariappan** [comment]
Thanks @akiyosi I have tried the latest changes and it looks awesome.
This is my daily driver now. Thanks for addressing this in very short time 😄 

There is one bug in gonvimfuzzyAg display which I am tracking now. 
Will raise pull request once i found RC

**Comment by Mariappan** [comment]
Hi @akiyosi There is some cursor bug in 0.4.0 branch currently
When you move the arrows using left and right arrow keys, I am seeing this .
<img width="157" alt="Screenshot 2019-06-02 at 7 39 06 PM" src="https://user-images.githubusercontent.com/947300/58762528-5de9a200-856e-11e9-9d00-c4c1e9ee5aa3.png">

Also cursor shape move from block to vertical

**Comment by Mariappan** [comment]
<img width="121" alt="Screenshot 2019-06-02 at 7 41 45 PM" src="https://user-images.githubusercontent.com/947300/58762540-7eb1f780-856e-11e9-9c8d-f1545b1e75c5.png">

**Comment by akiyosi** [comment]
@Mariappan 
Thank you for your testing!
I am very grateful.

> Also cursor shape move from block to vertical

I think it is default [guicursor](http://vimdoc.sourceforge.net/htmldoc/options.html#'guicursor') value behavior.
You can confirm the same behavior in macvim.
If you want to change the behavior, you should set the [guicursor](http://vimdoc.sourceforge.net/htmldoc/options.html#'guicursor') option.
`command-line Normal` and `command-line Insert` are the targets of setting, especially for the behavior you pointed out🙂

By the way, I fixed the cursor position bug 0df8f9d6
