### ISSUE TITLE
freeze in random moment

### ISSUE THREAD

**Issue by gmankab** [akiyosi/goneovim#450]
it freezes every 10-20 minutes in random moments

vanilla neovim not freezes at all

<details>
  <summary>neofetch</summary>

  ![image](https://user-images.githubusercontent.com/73340745/227707781-f652f79c-303f-4a06-aa80-92f60e6e384a.png)

</details>

[debug.log](https://github.com/akiyosi/goneovim/files/11068456/debug.log)
[init.vim](https://github.com/akiyosi/goneovim/files/11068459/init.vim.txt)
[settings.toml](https://github.com/akiyosi/goneovim/files/11068460/settings.toml.txt)

**Comment by akiyosi** [comment]
Hi,
Thanks for this issue report.
What is your goeovim's versions (`/path/to/goneovim --version`)?

**Comment by gmankab** [comment]
![image](https://user-images.githubusercontent.com/73340745/227715050-bcbeecbf-c953-4c14-be1e-11f6da6b1b67.png)

installed from aur

**Comment by gmankab** [comment]
i forgot to say

when it freezes, it freezes at all, and there is no ability to make it to continue work

so i must force close it

**Comment by akiyosi** [comment]
Hmm, I am not sure of the cause yet, but it could be an OS-specific or specific plug-in or configuration-dependent issue, as I have not seen such a problem in my MacOS environment.

By the way, does the problem occur with the latest version of Goneovim?
https://github.com/akiyosi/goneovim/releases/tag/nightly

**Comment by gmankab** [comment]
> By the way, does the problem occur with the latest version of Goneovim? https://github.com/akiyosi/goneovim/releases/tag/nightly

i'l test it, thanks

**Comment by gmankab** [comment]
no freezes on nightly build

**Comment by gmankab** [comment]
got freeze again on nightly build

i downloaded it about a week ago

![image](https://user-images.githubusercontent.com/73340745/230082844-ea3534ee-bba4-4455-adcf-69ae97d50479.png)

**Comment by akiyosi** [comment]
@gmankab 
Thanks for the report.
I was able to reproduce a similar problem in your settings and have made a fix to the process that I believe is one of the possible causes of this issue. (https://github.com/akiyosi/goneovim/commit/68f9ca045dca4be311a5d0bd21923be02326f555)

You can get the fixed binary below.

https://github.com/akiyosi/goneovim/actions/runs/4627102845

**Comment by gmankab** [comment]
thanks, i'll try it

**Comment by gmankab** [comment]
got freeze right now

[debug.log](https://gmankab.github.io/files/debug.log)

**Comment by akiyosi** [comment]
@gmankab 
Sorry for the frequent freezes and the annoyance it causes.
I believe commit cf35f01 fixed this problem.
You can try the following CI deliverable binaries.

https://github.com/akiyosi/goneovim/actions/runs/4651133371

**Comment by gmankab** [comment]
thanks, i'll try

**Comment by gmankab** [comment]
got freeze
[debug.log](https://github.com/akiyosi/goneovim/files/11194597/debug.log)
![image](https://user-images.githubusercontent.com/73340745/231014786-480959ad-edcf-4723-8d24-336165f5db15.png)

**Comment by gmankab** [comment]
i'll disable minimap, thanks
