### ISSUE TITLE
status line is cut off

### ISSUE THREAD

**Issue by shiena** [akiyosi/goneovim#451]
## Environment

- goneovim version: nightly 0940c68153f059e77f74a6026d70a4bc058e1714
- OS: Windows11

## Steps to reproduce

1. add `ExtTabline=true` to settings.toml
2. run goneovim
3. execute `:tabnew`

note: The status line is properly rendered when resizing the window.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/1295639/229733528-919d6c84-6584-44f5-85d9-318a511a4986.png">

**Comment by akiyosi** [comment]
Thanks for the issue report.
I have fixed this issue in 336219c

**Comment by akiyosi** [comment]
Closed.
