### ISSUE TITLE
WSL Clipboard does not work

### ISSUE THREAD

**Issue by DanWiseProgramming** [akiyosi/goneovim#460]
When I attempt to paste something into Neovim which was copied from Widows using [this build](https://github.com/akiyosi/goneovim/actions/runs/4665198934), running it with `goneovim.exe --wsl`, it does not work.

According to `:checkhealth`, no clipboard tool is installed. Other GUIs register themselves as clipboard providers such as Neovide, FVim, etc.

Is this a known issue? Am I missing something?

**Comment by akiyosi** [comment]
Thanks for this issue report.
I have added the functionality to make gooneovim a clipboard provider.

Try the following.

https://github.com/akiyosi/goneovim/actions/runs/4839753238

To activate the feature add the following to settings.toml

``` toml
[Editor]
Clipboard = true
```

**Comment by akiyosi** [comment]
The branch has been merged into master, the issue has been solved.
Closed.

**Comment by DanWiseProgramming** [comment]
Hi @akiyosi ,
Thank you - I will give it a test soon. Thanks for working on fixing this!
