### ISSUE TITLE
neovim flatpak - executable file not found

### ISSUE THREAD

**Issue by gmankab** [akiyosi/goneovim#467]
i am installed neovim from flathub, and i can't make it works with goneovim

```bash
➜ ./goneovim

exec: "nvim": executable file not found in $PATH
```

```bash
➜ ./goneovim "nvim=flatpak run io.neovim.nvim"

exec: "nvim": executable file not found in $PATH
```

```bash
➜ echo "flatpak run io.neovim.nvim" | sudo tee /bin/nvim
➜ sudo chmod +x /bin/nvim
➜ ./goneovim

fork/exec /usr/bin/nvim: exec format error
```

**Comment by shiena** [comment]
I found a flatpak package for neovide, another neovim GUI. This package includes neovim and resolves path issues. I believe that packaging goneovim in a similar way would also solve path issues.
https://github.com/deisi/flathub/tree/neovide

**Comment by gmankab** [comment]
perhaps packing goneovim in flatpak with neovim binary included will solve the problem

#431

**Comment by akiyosi** [comment]
Ok, I understand the fact of the problem.
I will try to make a flatpak package for goneovim If I make the time.

**Comment by gmankab** [comment]
@akiyosi, thank you

**Comment by gmankab** [comment]
@shiena, I didn't know it was possible

when you run a flatpak via `flatpak run`, it runs in isolation from the system, and it has other paths to configs

i wouldn't recommend running flatpaks without `flatpak run`, because then it will not be isolated, and the wrong config paths will be used

**Comment by shiena** [comment]
@gmankab Then you can use the wrapper script.

```
cat nvim-wrapper
#!/bin/sh

exec flatpak run io.neovim.nvim "$@"
```

```
chmod u+x nvim-wrapper
goneovim --nvim=./nvim-wrapper
```

**Comment by gmankab** [comment]
@shiena

![image](https://github.com/akiyosi/goneovim/assets/73340745/6a812f5e-fc49-415c-b3bf-119ae44b2758)

**Comment by shiena** [comment]
Try changing `#!/bin/sh` to `#!/bin/bash` in nvim-wrapper.

**Comment by gmankab** [comment]
my problem was that i accidentally inserted an empty line at the beginning of the file

i changed

```

#!/bin/sh
```

to

```
#!/bin/sh
```

now it works, thanks @shiena 

i am closing this issue, but #431 is still actual

**Comment by gmankab** [comment]
@akiyosi, please make goneovim automatically try to run flatpak nvim, if binary nvim is not found in the system

**Comment by shiena** [comment]
If you copy `nvim-wrapper` to a folder where the path, such as `~/.local/bin/nvim`, is included, you can start goneovim without any options.

**Comment by gmankab** [comment]
yes, but it would be cool to free the user from having to create a wrapper script
