### ISSUE TITLE
"goneovim" cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by trsplms** [akiyosi/goneovim#469]
I just installed `goneovim` via Homebrew (by running the command outlined in this repo). The installation was successful. However, when I try to run `goneovim` I got the following error:

`"goneovim" cannot be opened because the developer cannot be verified.`
`macOS cannot verify that this app is free from malware`

<img width="1680" alt="Screenshot 2023-05-09 at 8 03 36 PM" src="https://github.com/akiyosi/goneovim/assets/49292621/9c62a0e4-1dc3-41d7-af0c-77c9e5a9539e">

**Comment by bfulop** [comment]
You have to allow it to _open anyway_ in the system preferences → security .
You only have to do it once.

![goneovim@2x](https://github.com/akiyosi/goneovim/assets/1718128/e9d08b7a-79c9-4067-91a1-3a8532172e41)

**Comment by trsplms** [comment]
Thanks, @bfulop, but I'm not getting that option in the Settings menu.

<img width="1680" alt="Screenshot 2023-05-11 at 8 21 26 AM" src="https://github.com/akiyosi/goneovim/assets/49292621/ab70d7ce-5bb0-4c1d-956d-3e9aaac8c783">

**Comment by bfulop** [comment]
I think first you have to click on the `Cancel` button on warning popup.

**Comment by akiyosi** [comment]
@trsplms 
How about the procedure described in the following

https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by trsplms** [comment]
Thanks, @akiyosi. I had to manually run the app to do that, I was trying to run from the Terminal first, but now it works from there as well.
