### ISSUE TITLE
Control scroll granularity/sensitivity

### ISSUE THREAD

**Issue by b-fuze** [akiyosi/goneovim#47]
Is there a way to control scroll granularity/sensitivity? I'm also thinking scroll shouldn't take effect for small scrolling distances on a trackpad.

**Comment by akiyosi** [comment]
Hi,
Currently, there is no way to control the scrolling distance on the trackpad.
Do you want to scroll at a greater(e.g. 3-line or more) distance?

**Comment by b-fuze** [comment]
Oh no, actually it scrolls too fast for me. I was hoping less.

**Comment by akiyosi** [comment]
Scrolling by the track pad is realized internally by the input of `<C-e>` / `<C-y>`.
So, if you set the `nnoremap` or `map` to these keys, scrolling may move by a large distance unit.

**Comment by b-fuze** [comment]
So I can use either of those to override the internal mappings or is it not possible atm? If anything I just want to scroll by one line and not two like it does currently

**Comment by akiyosi** [comment]
Currently, there is no setting to override the internal input key of the scroll process.
So, if you map a `<C-e>` / `<C-y>` in `init.vim`, it will scroll in a large distance unit.
If you want to scroll per one line, the only way is to delete those mappings.

**Comment by b-fuze** [comment]
Okay, thanks. Will this be in consideration for the future? (should I keep this issue open for now)

**Comment by akiyosi** [comment]
> Okay, thanks. Will this be in consideration for the future? (should I keep this issue open for now)

ok, I will consider.
I think it is best for neovim to provide input for scrolling. `<ScrollWheelUp>` / `<ScrollWheelDown>` can be used for the scroll process as well, but its moving distance is in units of 3 lines.

**Comment by b-fuze** [comment]
Also, I'd like to add that horizontal scrolling is too much atm, it should also be adjustable.

**Comment by akiyosi** [comment]
Related to https://github.com/neovim/neovim/pull/12355

**Comment by andmis** [comment]
See also https://github.com/neovim/neovim/issues/11738.
