### ISSUE TITLE
welcome screen skipped

### ISSUE THREAD

**Issue by gmankab** [akiyosi/goneovim#470]
hello

goneovim creates new empty file, and shows it instead of noevim's welcome screen

how can i see welcome screen on startup?

**Comment by shiena** [comment]
`:help :intro`

**Comment by gmankab** [comment]
> `:help :intro`

oh, why after i opened `:help :intro`, the welcome screen stopped skipping?

i think it's weird

**Comment by shiena** [comment]
Please read the explanation in the intro carefully.
> When Vim starts without a file name, an introductory message is displayed.  It
is removed as soon as the display is redrawn.  To see the message again, use
the ":intro" command.  To avoid the intro message on startup, add the "I" flag
to 'shortmess'.

**Comment by gmankab** [comment]
i never touched the shortmess flag

i was confused by the fact that when i just ran nvim, the welcome message was shown, but when i ran goneovim it didn't

now after i open `:help :intro` the message is shown as it should

i think it should always be shown, out of the box, without having to open `:help :intro`

**Comment by shiena** [comment]
is this the message you saw?
https://github.com/flathub/io.neovim.nvim/blob/master/neovim-first-run.txt
In this case, it is a message that is displayed only for the first time due to the mechanism unique to the flatpak package.

**Comment by gmankab** [comment]
> is this the message you saw?

no, i mean this (pic from google)

![IMG_20230512_110711_285](https://github.com/akiyosi/goneovim/assets/73340745/cc441169-ce72-4a77-8eca-93e7539ba8e8)

**Comment by gmankab** [comment]
> Fixing this will require a fix on the Neovim mainframe side.

@akiyosi, but why now i can see welcome message in goneovim after i open `:help :intro`

**Comment by akiyosi** [comment]
> @akiyosi, but why now i can see welcome message in goneovim after i open :help :intro

This is because the Welcome content is drawn on the "normal" grid, not on the global grid, when the user explicitly executes the command to display it.

**Comment by gmankab** [comment]
it's weird but ok

**Comment by akiyosi** [comment]
I would like to keep this issue open, as it is possible that there are others who care about this issue and it would be better to have it fixed.

**Comment by akiyosi** [comment]
It seems that the Neovim core supports that feature.

Related:
* https://github.com/neovim/neovim/pull/24764
* https://github.com/neovim/neovim/issues/24705
