### ISSUE TITLE
Broken smooth mouse scrolling with v0.6.5

### ISSUE THREAD

**Issue by pjg** [akiyosi/goneovim#477]
In the latest release the scrolling is very jerky. It is smooth for a moment, but then it suddenly jumps a couple of lines. This makes scrolling extremely annoying.

**Comment by akiyosi** [comment]
@pjg 
Thanks for the issue report.
What is your Neovim version?
goneovim v0.6.5 requires Neovim 0.9.0 or higher.

**Comment by pjg** [comment]
```bash
☺ brew list --versions G neo                                                                                                                                                                                                    neovim 0.9.1
goneovim 0.6.5
```

**Comment by akiyosi** [comment]
Your OS is MacOS right?

**Comment by pjg** [comment]
Yes :)

**Comment by akiyosi** [comment]
Hmm, the smooth scroll control is implemented a little differently between v0.6.5 and v0.6.4. However, I can still scroll smoothly on my MacOS with v0.6.5.

It is possible that some Neovim setting is affecting this.
Is my understanding correct that your settings are the ones in the following dotfiles?

https://github.com/pjg/dotfiles/tree/main/.vim

**Comment by pjg** [comment]
This is correct. In particular this is my .vimrc: https://github.com/pjg/dotfiles/blob/main/.vimrc

**Comment by akiyosi** [comment]
@pjg 
Does your setup output a vimrc error when Neovim (Goneovim) starts?
It seems that this error output is causing the settings that Goneovim requires for smooth scrolling to not be reflected properly.

**Comment by pjg** [comment]
Indeed it does. Here's the `:messages` output:

```
Error detected while processing .../.vim/plugged/clrzr/plugin/clrzr.vim:
line 17:
clrzr disabled: +textprop Vim feature not found
```

Looks like neovim doesn't support `+textprop` whatsoever. I think I need to disable this plugin when running in neovim context.

**Comment by akiyosi** [comment]
Yes, I recommend upgrading such configurations.
I have confirmed that if I comment out `Plug 'BourgeoisBear/clrzr'` in your config, smooth scrolling works.
