### ISSUE TITLE
When completing on the status bar, sometimes characters are not displayed

### ISSUE THREAD

**Issue by shiena** [akiyosi/goneovim#478]
# Environment

- OS: Windows11
- version: nightly-1-g075a17b

https://github.com/akiyosi/goneovim/assets/1295639/4c2e80ca-f64c-4510-be4f-ca8dabc07b30

It seems that when you enter the tab key in the status bar, it is replaced with two spaces.

**Comment by akiyosi** [comment]
@shiena 
Thanks for the issue report.
I don't have a clear cause, but I have fixed the code that seems to be relevant in e010a37d89, please let me know if you encounter the same problem again with the binary that corresponds to e010a37d89.

**Comment by shiena** [comment]
@akiyosi Thank you for fixing the bug. https://github.com/akiyosi/goneovim/actions/runs/5230805544 fixed the problem.
