### ISSUE TITLE
Font issue in ExtPopupmenu

### ISSUE THREAD

**Issue by damanis** [akiyosi/goneovim#486]
Goneovim version: https://github.com/akiyosi/goneovim/actions/runs/5503533898
Seems, invalid item height calculation.
![image](https://github.com/akiyosi/goneovim/assets/65733488/be6a5e25-a2e4-4b29-9a0c-4ecfb4a4c711)

**Comment by akiyosi** [comment]
Fixed with [25efc26](https://github.com/akiyosi/goneovim/commit/25efc26f3aaf714af7d460e6e681bc0211b3a2a8)
