### ISSUE TITLE
FocusGained does not reload buffer when autoread is set 

### ISSUE THREAD

**Issue by akiyosi** [akiyosi/goneovim#492]
Same issue as following
https://github.com/equalsraf/neovim-qt/issues/846

**Comment by damanis** [comment]
So, what need to configure in config files to goneovim reload changed files?

**Comment by akiyosi** [comment]
@damanis 
No configuration is needed.
If the binary contains https://github.com/akiyosi/goneovim/commit/92f16b33c94dc9710ed7b30fca1cd6e9c98ca197, it will be automatically loaded when the application is activated under `set autoread` setting.
