### ISSUE TITLE
Buggy status bar rendering in 0.6.6

### ISSUE THREAD

**Issue by BastiDood** [akiyosi/goneovim#494]
![status bar shows split rendering of command mode and normal mode which ends up reading as "cormal" mode](https://github.com/akiyosi/goneovim/assets/39114273/702bc87f-60d4-4025-920f-1f63faad8c3f)

Since 0.6.6, the status bar doesn't seem to update correctly anymore. May it be mode switching, LSP messages, `packer.nvim` update screens, or even scrolling through text: the status bar does not update. And when it does in specific occasions (such as that in the screenshot above where I simply pressed `:` to go from normal mode to command mode), the updates are partial.

Most interestingly, this appears to have been previously reported and fixed in #478, but as seen in the screenshot above, the bug still persists.

> **Note**
> I run Goneovim 0.6.6 for Windows.

**Comment by akiyosi** [comment]
@BastiDood 
Hi :)
Thanks for the report.
I could not reproduce the problem in my environment, but I have fixed the code that I believe is related to this issue.
Does the following fixed binary solve the problem?

https://github.com/akiyosi/goneovim/actions/runs/5822863158

**Comment by BastiDood** [comment]
Hello there! The build artifacts don't seem to be present in that workflow run.

**Comment by BastiDood** [comment]
Oh, I forgot to ask. When would be a great time to release the patch update for this? For the meantime, I've stuck with 0.6.5, but I'd like to receive the other bug fixes from 0.6.6 as well.
