### ISSUE TITLE
font error

### ISSUE THREAD

**Issue by jkwroi24io9342fsdjklAdf** [akiyosi/goneovim#497]
`(base) ╭─lucas@M2Air ~/.config/goneovim
╰─➤  /Applications/goneovim.app/Contents/MacOS/goneovim
(base) ╭─lucas@M2Air ~/.config/goneovim
╰─➤  qt.qpa.fonts: Populating font family aliases took 58 ms. Replace uses of missing font family "Fire Code" with one that exists to avoid this cost.
2023-09-05 11:00:27.798 goneovim[54649:9805252] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit`

![image](https://github.com/akiyosi/goneovim/assets/4435013/4d0e4532-55fc-43e9-911d-c40f6d3af267)

**Comment by akiyosi** [comment]
Hi,
This is an error that Qt is giving you, indicating that the font you specified is taking a lot of time to process.
Please let me know what your problem is.
Is this a solution to this error? Or is it about the standard output of goneovim for this error?
