### ISSUE TITLE
How to build correctly?

### ISSUE THREAD

**Issue by msdobrescu** [akiyosi/goneovim#498]
Under Gentoo there is no ebuild for goneovim, so I've tried building it manually.
There is an already built package, but that one does not work under gentoo for missing some specific library version.
So I've tried the following:
- fetched the git tag for v0.6.7
- built as instructed in the development section:

1.     Clone this repo and cd into the repo
2.     make qt_bindings
3.     make deps
4.     make app

The result is a smaller binary, of 9.5 MB, instead of 26 MB.

What am I doing wrong? What is the right procedure?

**Comment by akiyosi** [comment]
@msdobrescu 
Hi :)
I believe the binary you generated is the correct binary.
The binaries published in repository releases are static builds, which usually have a larger file size than a naive build.

**Comment by msdobrescu** [comment]
So is it normal to start like this?

![image](https://github.com/akiyosi/goneovim/assets/7279637/1cb05e01-2f41-475f-9583-0245ff7384a0)

**Comment by akiyosi** [comment]
Yes. 
If Neovim is plain with no plugins installed, it will start in the style shown above.

**Comment by msdobrescu** [comment]
Where are those plugins?

**Comment by akiyosi** [comment]
@msdobrescu 
You can take a look at some things at the following

https://dotfyle.com/neovim/plugins/trending

**Comment by msdobrescu** [comment]
Thanks!
I have expected to list the links to the ones in the screenshots here.

**Comment by akiyosi** [comment]
Ah, is that a screenshot of this repository?
To be honest, I no longer know the exact list of plugins used in that screenshot. That screenshot is about 2 years old.
I believe the color scheme is the following.

https://github.com/patstockwell/vim-monokai-tasty
