### ISSUE TITLE
Can't set the workspace properly on windows and some UI bugs

### ISSUE THREAD

**Issue by DeepDarkOdyssey** [akiyosi/goneovim#50]
![TM20190429140222](https://user-images.githubusercontent.com/37280638/56878676-d947c780-6a87-11e9-9815-b77f61540946.png)
Currently I'm using gonvim on windows, and I tried to set the workspace path in setting.toml to my projects on D:\Projects. As is shown in the picture, somehow it doesn't work. I've tried many style of the path, windows-like, unix-like, all fails. So how does gonvim resolve the path on windows? 

BTW: Great work，Gonvim is exactly what I need of neovim on Windows. Just file explorer and fuzzy finding, then leave everything else to neovim, Excellent!

**Comment by akiyosi** [comment]
Hi 😃 

I'm sorry, the wiki setting example is not appropriate.
`name` and `full`, `minimum` are all options that can be specified for `PathStyle`, and are not themselves key config item. In other words, the intention is that the following settings are possible. 
```
PathStyle = "name"
PathStyle = "full"
PathStyle = "minimum"
```

**Comment by DeepDarkOdyssey** [comment]
So currently I can't set a startup workspace ?

**Comment by DeepDarkOdyssey** [comment]
Also the wildmenu disappeared
