### ISSUE TITLE
Typo in goneovim.txt

### ISSUE THREAD

**Issue by purple4pur** [akiyosi/goneovim#502]
Should be `.config` not `.condig` i think.

https://github.com/akiyosi/goneovim/blob/3c8b47e59dabcce9c4be6556fa2050f7a7447942/runtime/doc/goneovim.txt#L329-L330

**Comment by akiyosi** [comment]
Thank you! 
Fixed with https://github.com/akiyosi/goneovim/commit/4d49ecf2d9c908c011ca1a55a193645e00238532
