### ISSUE TITLE
error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JesseChavez** [akiyosi/goneovim#504]
Trying to upgrade my `goneovim` after 10 months or so.

I'm getting the following error

```
./goneovim-v0.6.5-linux/goneovim
./goneovim-v0.6.5-linux/goneovim: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory
```

My OS is Ubuntu `23.04`, the old  `goneovim` still works in Ubuntu `23.04`

Thanks

**Comment by JesseChavez** [comment]
I found the below post, it seems Ubuntu needs `libtiff.so.6` but I guess previously `goneovim` did not depend on `libtiff.so.6` or `libtiff.so.5` since my old `goneovim` still works.

https://askubuntu.com/questions/1467216/libtiff-so-5-issue-with-emacs-after-upgrade-to-ubuntu-23-04

**Comment by akiyosi** [comment]
@JesseChavez  
Hi :)
Thanks for this issue reporting.
Does v0.6.7 also cause this problem?

**Comment by JesseChavez** [comment]
Hi @akiyosi 

Same issue:

```
$ ./goneovim-v0.6.7-linux/goneovim --version
./goneovim-v0.6.7-linux/goneovim: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory
```

This is the old version that works in my environment:

```
$ ./own/goneovim-v0.6.3-linux/goneovim --version
v0.6.3
```

This is my environment:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar
```

**Comment by akiyosi** [comment]
@JesseChavez 
The build procedure for release binaries has been changed for v0.6.3 and v0.6.5 and later. It is not easy to revisit this changed procedure and remove the dependency on libtiff.
Based on the content of the error regarding libtiff, I believe that the error can be avoided by installing the necessary libraries.




The error message `error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory` indicates that the program is attempting to load a shared library named `libtiff.so.5`, but this library does not exist on the system. Here are several ways to address this issue:

1. **Library Installation**:
   - Installing the required library on the system can resolve the error. On Ubuntu, you can install the `libtiff5` package using the following command:
     ```bash
     sudo apt-get install libtiff5
     ```

2. **Creating a Symbolic Link**:
   - If a different version of `libtiff.so.5` is already installed on your system, you can create a symbolic link to help the program find the library:
     ```bash
     sudo ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.<installed-version> /usr/lib/x86_64-linux-gnu/libtiff.so.5
     ```

3. **Setting the LD_LIBRARY_PATH**:
   - You can set the `LD_LIBRARY_PATH` environment variable to explicitly specify the path where the program should look for `libtiff.so.5`:
     ```bash
     export LD_LIBRARY_PATH=/path/to/directory/with/libtiff.so.5:$LD_LIBRARY_PATH
     ```

**Comment by akiyosi** [comment]
@JesseChavez 
Is there any progress on this?
If you feel differently about my answers above, I would like to discuss them with you.

**Comment by indivisible** [comment]
libtiff5 is gone since ubuntu lunar (23.04). Debian bookworm also dropped it, so the releases are broken on that too.

**Comment by akiyosi** [comment]
@indivisible 
Thanks for comment!
I think I can generate a fixed binary by building on a newer ver of Ubuntu.
I will work on this issue and create a trial binary.

**Comment by akiyosi** [comment]
@indivisible 
By the way, Are the following procedures unacceptable to you?

```
cd /usr/lib/x86_64-linux-gnu
sudo ln -s libtiff.so.6 libtiff.so.5
```

ref:
https://askubuntu.com/questions/1467216/libtiff-so-5-issue-with-emacs-after-upgrade-to-ubuntu-23-04

**Comment by indivisible** [comment]
Thanks, it does start up with that hack, though I'd say symlinking the system `libtiff.so` to the release's `lib/` directory is cleaner

IMO a flatpak or appimage would result in a more robust cross-distro build (or also bundling libtiff with the builds)

**Comment by akiyosi** [comment]
Thanks for your opinion.
We will consider offering it in flatpak or appimage!
This issue is closed.
