### ISSUE TITLE
MacOS Sonoma "Secure coding" warning

### ISSUE THREAD

**Issue by mars0i** [akiyosi/goneovim#506]
Recently I upgraded MacOS to Sonoma (and also got the latest release of Goneovim, 0.6.7), and I get this warning when I start Goneovim (not with plain nvim):

> 2023-11-15 13:33:09.075 goneovim[80521:215314] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

This does not seem to cause any problems for me with Goneovim.  For me, it's merely very, _very_ minor annoyance.

However, the warning seems to be a response to a recently reported security vulnerability in MacOS's handling of applications:
https://sector7.computest.nl/post/2022-08-process-injection-breaking-all-macos-security-layers-with-a-single-vulnerability/

The article begins with "If you have created a new macOS app with Xcode 13.2", so maybe the solution would be to upgrade Xcode for the next release?  (On Sonoma, the Xcode version that downloaded was 15.0.)  Or maybe it's Go or Qt or some other library that was compiled with Xcode 13.2 (or earlier?).  I don't know whether that makes sense.

I'm also not sure whether I could or should do something to "enable secure coding" without a new release.  Maybe it's something I could do on my own machine?

Thanks!

**Comment by akiyosi** [comment]
@mars0i 
Hi :D 
Thanks for the issue report.
I have looked into this issue and have created a fix.
On my macOS sonoma environment, the fix no longer produces the warning message you mentioned.
Could you try yours with the binary generated by the CI job here?

https://github.com/akiyosi/goneovim/actions/runs/6912645549

If there are no problems, I will merge it into master.

**Comment by mars0i** [comment]
Hi Akiyosi-

That seems to work--the message is gone.  Thank you!  I'll use it for a day or so and report back if there are any problems.

**Comment by bfulop** [comment]
I can also confirm that the build linked in the above message fixed the warning issue on my machine! Thank you!

**Comment by mars0i** [comment]
Hi @akiyosi.  I had no problems with the new commit.  I've been running it on both Sonoma and Ventura.  (The warning doesn't appear on Ventura, but it's good to know that it works there, too.)
Thank you!

**Comment by akiyosi** [comment]
@mars0i 
Thanks for the confirmation and report!
I have merged these changes into master. I would like to close this issue.

**Comment by mars0i** [comment]
Thanks!  I agree that it can be closed.
