### ISSUE TITLE
[Feature request] Disable/remove item from sidebar

### ISSUE THREAD

**Issue by Anrock** [akiyosi/goneovim#52]
Hi, i'm using plug instead of dein. Is there any configuration option to remove dein item from sidebar?

**Comment by akiyosi** [comment]
Hi,

You can not disable items in the ActivityBar, but you can disable the ActivityBar itself.
e.g.

setting.toml
```
[ActivityBar]
Visible = false
```

**Comment by Anrock** [comment]
Yeah, i know. But i like workspaces item.

**Comment by smolck** [comment]
Is this still a relevant issue now that there is no longer an ActivityBar in GoNeovim 0.4.0?
