### ISSUE TITLE
When running command in mini buffer, bottom bar disappears.

### ISSUE THREAD

**Issue by carlmueller** [akiyosi/goneovim#521]
OS:  macOS Sonoma 14.3.1
Goneovim:  0.6.8

When I run a command in the minibuffer at the bottom of the window, for example :!qq the output covers several lines and the bar above the minibuffer disappears.  I'm attaching a screenshot.  On the left is goneovim, and on the right is neovim-qt. 

It would be better if the bar did not disappear.

<img width="1470" alt="Screenshot 2024-02-15 at 5 08 22 PM" src="https://github.com/akiyosi/goneovim/assets/67909756/71b83e23-40e0-4ab4-ad4d-7f30ee9ecfc3">

**Comment by akiyosi** [comment]
@carlmueller 
Hi, Thanks for this issue report :)
The following fix adds the functionality to draw separators in the message window. 
By appending the following to the config file, you can display separators in the message window.

```
[Message]
ShowMessageSeparators = true
```

**Comment by akiyosi** [comment]
@carlmueller 
Sorry, forgot to post the link to the fix.
https://github.com/akiyosi/goneovim/actions/runs/7969453491
