### ISSUE TITLE
goneovim should open in home directory

### ISSUE THREAD

**Issue by carlmueller** [akiyosi/goneovim#522]
OS: macOS Sonoma 14.3.1
Goneovim: 0.6.8, from Homebrew

1.  Open goneovim by clicking on the icon
2.  Type :e <Tab>
3.  This opens a list of directories and files in the root directory /
4.  It should open a list from the home directory ~/

**Comment by akiyosi** [comment]
@carlmueller 
Hi,
As a result of the discussions in #43, #325, and #337, the current working directory (CWD) of goneovim is now set to / by default. However, by including the following in init.lua, users can set the current directory to whatever they prefer. 
Does this meet your expectations?

```lua
if vim.g.goneovim then
  vim.cmd('cd ~')
end
```

**Comment by carlmueller** [comment]
Yes, thanks.
