### ISSUE TITLE
A smooth scrolling wish list

### ISSUE THREAD

**Issue by bfulop** [akiyosi/goneovim#531]
Hello Akiyosi!

I saw you were working on the smoothing scrolling revamp with https://github.com/akiyosi/goneovim/pull/530

I currently have the smooth scrolling turned off in Goneovim and using [mini.animate](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-animate.md) instead.

Here's what was bothering me about the built-in smooth scrolling implementation:

When jumping to a part of the buffer that is not visible, Goneovim would jump then do a scroll simulation starting from what looks like a blank buffer.  
It would be nicer if it worked like other smooth scroll plugins: Goneovim would scroll through the **whole document** to arrive to the jump position.

I only need smooth scrolling when jumping within the same document. 
I've found it distracting when Goneovim also did the scroll "simulation" for any update on the screen, e.g. when switching buffers or opening the Telescope pickers. For these cases I would prefer the scroll to be turned off.

These are not major points for me, just wanted to share with you my feedback.

**Comment by akiyosi** [comment]
Since the PR for improving the smooth scroll feature has been merged, this Issue is closed for now.
