### ISSUE TITLE
can't load shared library libdiff.so.5 on ubuntu

### ISSUE THREAD

**Issue by xavier2910** [akiyosi/goneovim#532]
I downloaded goneovim 0.6.8, but when I tried to run it, I got this error message: `.local/bin/goneovim-v0.6.8-linux/goneovim: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory`
This so file is not in the ubuntu package repository for 23.10 (mantic), and it appears was only available as recently as 22.04.

**Comment by akiyosi** [comment]
Hi :)
Thanks for the information. I will upgrade to a new build environment soon.
As a work-around, the following is a way to place a symbolic link to a compatible library.

```
ln -s /path/to/libtiff.so.X.Y.Z /path/to/libtiff.so.5
```

**Comment by xavier2910** [comment]
Thanks for your support! I added a link to libtiff.so.6, and it appears to be working now.
