### ISSUE TITLE
JIS配列のmacOSで \ を入力できない

### ISSUE THREAD

**Issue by shiena** [akiyosi/goneovim#534]
OS: macOS 14.4.1
キーボード: JIS配列

インサートモードで Option + ¥ を入力すると \ が入力されずノーマルモードへ戻ってしまいます。
neovim-qtも同じ挙動で、neovideは \ を入力できているのでqtの仕様かもしれません。
現状は ¥ を使わないので以下の設定で回避しています。

```vim
if has('mac') && exists('g:gonvim_running')
	noremap! <Bslash> <Char-165>
	noremap! <Char-165> <Bslash>
	tnoremap <Bslash> <Char-165>
	tnoremap <Char-165> <Bslash>
endif
```

**Comment by akiyosi** [comment]
イシュー報告ありがとうございます。
https://github.com/akiyosi/goneovim/commit/e339a3a8e01957b0221f587983f7626565b4ef5c にて修正してみました。
ご確認いただけますと幸いです。

ちなみに、neovim-qt側で同じ挙動なのは、goneovimのkey input処理をNeovim-qtの実装を参考に実装しているため、同様の問題がNeovim-qt側にも存在している構造となっているのだと思われます。

**Comment by shiena** [comment]
@akiyosi 修正ありがとうございます。
Option + ¥ で \ 、上記remapでは ¥ を入力できるようになりました。
