### ISSUE TITLE
Option to disable "diff file dropped" popup

### ISSUE THREAD

**Issue by idbrii** [akiyosi/goneovim#545]
When I drag a file onto goneovim (v0.6.3), it shows this popup:

![image](https://github.com/user-attachments/assets/79d7f44a-4e0e-4518-bdc1-1493b2e68821)

How can I make it always edit the file instead of asking to diff?

I did `:help goneovim` and searched for 'drop' and 'drag' and 'diff' but didn't find any relevant settings. Is there an option to disable this popup?

While, yes, I'm using my mouse to drag and drop, I don't want to mouse down to this popup to dismiss it. The popup can't be closed with Esc.

----

NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068

**Comment by idbrii** [comment]
I tested the Windows build and it works great. I also tested turning it back on:
```
[Editor]
ShowDiffDialogOnDrop = true
```
All works well.

It seems the default value of ShowDiffDialogOnDrop is false which changes existing goneovim behaviour. That seems preferable to me, but may not be intentional?

Regardless, thanks for the quick fix!

**Comment by akiyosi** [comment]
Thanks for confirming.
Yes, that default is intentional.
