### ISSUE TITLE
compatibility issue with plugin yankring

### ISSUE THREAD

**Issue by bon-ami** [akiyosi/goneovim#552]
vim-scripts/YankRing.vim is a plugin to manage clipboard within neovim. it works correctly with neovim and some GUI's like fvim, neoray and neovide.
Windows 10. Neovim 0.10.1. goneovim 0.6.8.
I think maybe b/c of goneovim's clipboard feature. does not help with "Clipboard = false" in setting.toml.
this error will lead to errors in other plugins, such as deoplete, which works fine without yankring.
![goneovim_yankring](https://github.com/user-attachments/assets/7871dbc0-4e80-4594-bcf8-b1d3f5fd01e9)
commenting out these two links in my init.vim does not help,
```
set clipboard=unnamed "win32yank available
set clipboard+=unnamedplus
```
part of the code of the plugin,
```
function! s:YRCheckClipboard()
    if g:yankring_clipboard_monitor == 1
        " If the clipboard has changed record it inside the yankring
        " echomsg "YRCheckClipboard[".len(@*)."][".@*.']['.s:yr_prev_clipboard_star.']'
        if has('unnamedplus') && &clipboard =~ '\<unnamedplus\>'
            if !empty(@+) && @+ != s:yr_prev_clipboard_plus
                let elem    = s:YRMRUElemFormat(
                            \   getreg('+')
                            \ , getregtype('+')
                            \ )
                let found   = s:YRMRUHas('s:yr_history_list', elem)

                " Only add the item to the "top" of the ring if it is
                " not in the ring already.
                if found == -1
                    call YRRecord3("+")
                endif
                let s:yr_prev_clipboard_plus = @+
            endif
        else
            if !empty(@*) && @* != s:yr_prev_clipboard_star
                let elem    = s:YRMRUElemFormat(
                            \   getreg('*')
                            \ , getregtype('*')
                            \ )
                let found   = s:YRMRUHas('s:yr_history_list', elem)

                " Only add the item to the "top" of the ring if it is
                " not in the ring already.
                if found == -1
                    call YRRecord3("*")
                endif
                let s:yr_prev_clipboard_star = @*
            endif
        endif
    endif
endfunction
```

**Comment by akiyosi** [comment]
@bon-ami 
Thank you for reporting the issue.  
I have fixed the initialization process code, which I believe is related to the problem you reported.  
You can obtain the updated binary from the link below, so could you please try it out?

https://github.com/akiyosi/goneovim/actions/runs/10966376589

**Comment by bon-ami** [comment]
> @bon-ami Thank you for reporting the issue. I have fixed the initialization process code, which I believe is related to the problem you reported. You can obtain the updated binary from the link below, so could you please try it out?
> 
> https://github.com/akiyosi/goneovim/actions/runs/10966376589

I confirm it's solved. Thanks.
