### ISSUE TITLE
Invisible colors on some colorschemes

### ISSUE THREAD

**Issue by damanis** [akiyosi/goneovim#554]
**Reproduce scenario**:
- install some theme, e.g. [tokyonight](https://github.com/folke/tokyonight.nvim?tab=readme-ov-file)
- create test.js file
- enter `// View` in the file
**Problem**:
Text `View` is not visible
**Neovim version**: `NVIM v0.11.0-dev-903+gab98c5b5a`
**Goneovim**: build of `e882616`

I know, it seems like colorscheme problem, but neovide and nvim-qt have no problem, text shown properly.

**Comment by akiyosi** [comment]
@damanis 
Thanks for the report!
I will determine that this is not a color scheme issue, but a goneovim issue.
By the way, does this problem occur in previous builds?

I just checked the same conditions at hand and could not reproduce it. There may be some other condition.
<img width="577" alt="Screenshot 2024-10-07 at 23 20 34" src="https://github.com/user-attachments/assets/b20f33b3-1704-4586-809d-340eb6a3742e">

**Comment by damanis** [comment]
@akiyosi 
I run with `--noconfig` -- issue not reproduced.
Now I found that the issue caused by two configuration options:
```
FontFamily = "GoMono Nerd Font"
CachedDrawing = true
```
Set cached drawing to `false` or change font solves the problem.

P.S.
This font has best rendering in all applications I use (all use Go font) , but, seems, it does no compatible with CachedDrawing.
What font you use on screenshot? Could you provide config for it in Goneovim? I tried different fonts, but always get ugly rendering, excluding Go fonts.

**Comment by akiyosi** [comment]
@damanis 
I have identified and corrected the cause of this issue.
Could you please try the fixed version below?

https://github.com/akiyosi/goneovim/actions/runs/11238062020

**Comment by damanis** [comment]
@akiyosi 
The fixed version works properly. Checked configuration:
```
FontFamily = "GoMono Nerd Font"
CachedDrawing = true
```

**Comment by akiyosi** [comment]
@damanis 
Thank you for your confirmation.

Yes, Goneovim internally writes text to a rectangular image of the minimum required size, caches it and draws it to the screen at the same time, but we noticed a problem where the text is not displayed if the rectangle size is not large enough.
