### ISSUE TITLE
Broken/ugly font rendering in latest versions

### ISSUE THREAD

**Issue by pjg** [akiyosi/goneovim#556]
Latest version (724825a9013b139d as of writing this):

![Screenshot 2024-10-26 at 09 52 05](https://github.com/user-attachments/assets/598836f1-751e-434c-8a00-02e056566b1c)

One of the last versions that works well (2a5da0a51726ff9c):

![image](https://github.com/user-attachments/assets/73264eea-f891-422c-99b0-d61e5267930b)

My config: https://github.com/pjg/dotfiles/blob/main/.vimrc

**Comment by akiyosi** [comment]
@pjg 
Thanks for the report.
What OS is this happening on, Windows?

**Comment by pjg** [comment]
MacOS Sonoma v14.7 on M1 macbook.

**Comment by akiyosi** [comment]
@pjg 
Ah, I think I may have found the cause...

**Comment by akiyosi** [comment]
@pjg 
I have fixed this problem and created a new release.
https://github.com/akiyosi/goneovim/releases/tag/v0.6.10

**Comment by pjg** [comment]
The fix works! Thank you ❤️
