### ISSUE TITLE
Plan to remove Dein.vim GUI in v0.4.0

### ISSUE THREAD

**Issue by akiyosi** [akiyosi/goneovim#60]
I added Dein.vim GUI experimentally at 0.3.0, but I'm planning to remove it because the design is not good and it is not used so much.

**Comment by smolck** [comment]
@akiyosi Will you be keeping the sidebar as it is (only without the dein.vim part), changing it in some form, or removing it entirely?

**Comment by akiyosi** [comment]
Hi,
I will remove activitybar and dein.vim GUI feature. so gonvim v0.4.0 only have file explorer feature in sidebar.
