### ISSUE TITLE
No Windows release for v0.4

### ISSUE THREAD

**Issue by AgentCosmic** [akiyosi/goneovim#67]
Hi, I noticed there's no Windows build for v0.4
Hope you can provide one cos I've been waiting for this release. Thanks!

**Comment by akiyosi** [comment]
I'm sorry,
Windows currently requires special build procedures and is currently being built.

**Comment by pulcinello** [comment]
@akiyosi Thanks for your hard working. I've just tried this brand-new release on linux, and I can say it's the best neovim GUI I've used ever. Can't wait to use it on my Windows machine.

**Comment by akiyosi** [comment]
windows binary was added now.

**Comment by akiyosi** [comment]
Replaced windows binaries. Because the behavior was strange...
