### ISSUE TITLE
Only show `[LC] ...` part on popupmenu completions

### ISSUE THREAD

**Issue by smolck** [akiyosi/goneovim#69]
Currently, when showing completions for Rust with the external popupmenu, I get this sort of thing happening, with the popupmenu showing only one item:

![image](https://user-images.githubusercontent.com/46855713/68076391-eb315c80-fd81-11e9-8637-b5ee1195a520.png)

But in normal Neovim (in the terminal) it looks like this, with only the `[LC] ...` part showing and so I can see more items in the popupmenu:

![image](https://user-images.githubusercontent.com/46855713/68076399-fb493c00-fd81-11e9-80a2-22b3d52617d0.png)

One solution would be to only show the extra text on hover, like in [GNvim](https://github.com/vhakulinen/gnvim) after pressing `<C-S>` while hovering on a completion item:

![image](https://user-images.githubusercontent.com/46855713/68076444-65fa7780-fd82-11e9-8e8d-106120958610.png)

EDIT: Note that this problem only happens with (potentially long) documentation on the corresponding completions. In some cases there are no problems. It's only for things like the Rust standard library which is well documented and thus has longer docs for each function.

**Comment by akiyosi** [comment]
@smolck 
Thank you for the report.
It seems that I couldn't consider the UI display of the long explanation by LSP.
I will improve this.

**Comment by smolck** [comment]
No problem, and thanks! If you want I can create a PR for this, seems to be a fairly simple change to popupmenu.go ;)

**Comment by akiyosi** [comment]
Thank you😀
I'm going to VimConf 2019 today so it will take some time to fix.
I would be happy if you would PR it.

**Comment by smolck** [comment]
No problem! I’ll see if I can get a PR done tomorrow. Have a great VimConf! :]
