### ISSUE TITLE
Undercurl not supported

### ISSUE THREAD

**Issue by AgentCosmic** [akiyosi/goneovim#75]
There's a syntax option for undercurl (wavy underline) that only renders as an underline.

**Comment by akiyosi** [comment]
Hi😃

Goneovim supports `undercurl`.
What colorscheme / settings are you use to display `undercurl` ?

If you want to check `undercurl` easily, try the following:

```
{write some wrong/typo text into goneovim}
:highlight SpellBad gui=undercurl
:set spell
```

**Comment by AgentCosmic** [comment]
Sorry, this is my mistake. I migrated the colorscheme to neovim wrongly.
