### ISSUE TITLE
How to maximize window on startup?

### ISSUE THREAD

**Issue by AgentCosmic** [akiyosi/goneovim#76]
Is there an option or command to maximize the window on startup?

**Comment by akiyosi** [comment]
hi,
Write the following in ~/.goneovim/setting.toml

```
[Editor]
StartFullscreen = true
```

**Comment by AgentCosmic** [comment]
Hi,
This starts in full screen which hides the taskbar and doesn't allow me to tile the window in Windows.
BTW, is it possible to disable the "Do you want to diff the file..." prompt when I dragged a new file into goneovim?

**Comment by akiyosi** [comment]
> This starts in full screen which hides the taskbar and doesn't allow me to tile the window in Windows.

Umm, well, you would setting the width, height which equals to display size into `~/.goneovim/setting.toml` 

See [wiki](https://github.com/akiyosi/goneovim/wiki/Usage#configurattion)

> BTW, is it possible to disable the "Do you want to diff the file..." prompt when I dragged a new file into goneovim?

Currently it is not possible.

**Comment by AgentCosmic** [comment]
I tried setting the width and height but the window doesn't recenter so half the window would be off screen and I have to drag it to the center.

**Comment by akiyosi** [comment]
OK,
I'm looking for an implementation that makes the taskbar visible with `StartFullscreen`.

**Comment by akiyosi** [comment]
Hi
You can use `StartMaximizedWindow` setting or `--maximized` CLI option with goneovim v0.4.1.
