### ISSUE TITLE
Popup UI is blocking the line I'm editing

### ISSUE THREAD

**Issue by AgentCosmic** [akiyosi/goneovim#77]
My cursor is under the popup where I circled in red. Is this a plugin issue or goneovim issue? Also sometimes the completion menu will fly away to a corner of the screen.

![image](https://user-images.githubusercontent.com/1035714/69113902-6c495d00-0abf-11ea-9ea8-36f4f34cb011.png)

**Comment by akiyosi** [comment]
Thank you for your report.
I fixed it. (It is goneovim bug)

I will plan to release v0.4.1 in this weekend.
