### ISSUE TITLE
Popup men position is buggy

### ISSUE THREAD

**Issue by AgentCosmic** [akiyosi/goneovim#81]
Sometimes the popup menu flies to a different position. Here's an example:

![image](https://user-images.githubusercontent.com/1035714/69708542-c6d55f80-1136-11ea-8e4d-96a04f992b08.png)
My cursor is circled in red.

**Comment by akiyosi** [comment]
hi,

I have also experienced this problem only once.
I don't know how to reproduce.

Does this problem often occur in your environment?
If so I will try to reproduce in your [vimrc](https://github.com/AgentCosmic/vim/blob/master/_vimrc).

**Comment by AgentCosmic** [comment]
Hi,

Thanks for all the help. I really appreciate it. You can use my setup for [neovim here](https://github.com/AgentCosmic/neovim). Take note of the custom paths I used.

I mostly code in vue and go. Maybe that might help to trigger the issue more often. Also the autocomplete for the command line almost always have issues.

![image](https://user-images.githubusercontent.com/1035714/69769084-3e9a9d00-11be-11ea-8012-aa1e78823f5c.png)

**Comment by akiyosi** [comment]
I look into your screenshot and think that the popup menu is a custom popupmenu using the float window of the completion plugin (probably LanguageClient-neovim ?).
If so, there are the following possibilities in the issue:

1. Neovim float window problem (especially neovim ui: `win_float_pos`)
1. LanguageClient-neovim float window popup menu issue
1. goneovim float window drawing issue


I intend to investigate the problem from the above viewpoint.
If you want to work around this problem temporarily, you might want to enable goneovim's ext_popupmenu.
Add the following to `~/.goneovim/setting.toml`.

```
[Editor]
...
ExtPopupmenu = true
...
```

**Comment by AgentCosmic** [comment]
I tried using the same setup with nvm-qt. Here's a side by side on a fresh start without coc:

![image](https://user-images.githubusercontent.com/1035714/69899100-8ecf5600-139c-11ea-916b-a0f141a0ed5f.png)

Does this mean it's not a plugin issue?

**Comment by akiyosi** [comment]
hi

I investigated this issue and found it to be a Goneovim issue and fixed it https://github.com/akiyosi/goneovim/commit/f0899ef485dbff2b587a9c3d2efe5511d0bb5ae9.
I will release a modified version as early as 0.4.2 tomorrow.
