### ISSUE TITLE
no GonvimMarkdown

### ISSUE THREAD

**Issue by bon-ami** [akiyosi/goneovim#84]
when I type :gonvim and TAB to try it, it is not in the list, while other commands for File Explorer, workspace, minimap, etc. work.
neovim 0.4.3
goneovim 0.4.1
Windows 10

**Comment by akiyosi** [comment]
Hi
Sorry I'm late.
The markdown preview feature for Windows was not supported due to library specifications.

The library has recently started experimental support, so it will be supported in the next version.
