### ISSUE TITLE
Startify doesn't run on start-up

### ISSUE THREAD

**Issue by tssm** [akiyosi/goneovim#89]
For some reason [Startify](https://github.com/mhinz/vim-startify) doesn't run when goneovim is launched. It works as expected in pure Neovim as well with a couple of other GUIs (VimR and FVim). I guess goneovim pipes something into `nvim` when it starts to make the workspaces feature work and that prevents Startify from running. I tried to debug it myself but with my nil knowledge of Go I could't get far

**Comment by akiyosi** [comment]
Hi 😃
Thank you for your report.

I fixed this issue in https://github.com/akiyosi/goneovim/commit/35a692b10212e8324934e2db5dbc8c437a8cf7a7
I will plan to include this fix for v0.4.3.

**Comment by tssm** [comment]
Thanks to you for the quick fix!
