### ISSUE TITLE
A loop of of getchar(1) causes it to hang

### ISSUE THREAD

**Issue by eyalk5** [akiyosi/goneovim#90]
Hi, 
The issue in goneovim 0.4.2, MacOS high sierra ,nvim 0.5.0-295 . 
It seems that it is the same issue that happened in neovim-qt . 
That is, LeaderF hangs suddenly. But upon pressing on several keys in short periods, it is more likely. 
I have tried to solve it using sleep, which works for neovim-qt but not for goneovim. 

See related issues(and pull request) :

https://github.com/equalsraf/neovim-qt/issues/605
https://github.com/Yggdroot/LeaderF/issues/375

**Comment by akiyosi** [comment]
Hi :D
Thank you for your report.
I am investigating this event but have not yet determined the cause.  I will continue to investigate.

I want to check one point. Is the trigger that you reported a problem "key hang while running LLL"?

**Comment by eyalk5** [comment]
yes. The entire gonevim hangs when pressing keys on LeaderF.

**Comment by akiyosi** [comment]
This problem has been fixed in v0.4.4
Is it possible to confirm the problem?

**Comment by eyalk5** [comment]
Unfortunately no. Leaderf is not responsive specifically on goneovim. 
See: 
https://github.com/Yggdroot/LeaderF/issues/501

**Comment by eyalk5** [comment]
Well, I could verify it is OK. I noticed that bug 501 only happens when preview mode is ON.
