### ISSUE TITLE
Pre-Built Binaries Windows - No reaction

### ISSUE THREAD

**Issue by the42** [akiyosi/goneovim#92]
At my workplace I am stuck on Windows 64 bit. I downloaded the pre-built binary from
https://github.com/akiyosi/goneovim/releases/download/v0.4.3/Goneovim-0.4.3-win64.zip

and extracted into C:\Users\<USER>\AppData\Local\Gon

Neovim 0.5.0-297 is on the path.

I have to start Goneovim like 10 times (doing this from the command line) until the window opens. Before it finaly opens, it just quickly displays a window which get's immediately closed afterwards. No error message then from goneovim.exe on the command line.

This is very anoying to use an otherwise great Neovim GUI!

**Comment by akiyosi** [comment]
Hi :D 

Goneovim will start neovim if it exists under PATH. What is the Windows OS in your environment?

If the problem persists, unpack the official Windows binary of Neovim(+neovim-qt) and overwrite the goneovim package in it.

e.g. 
1. Download [nvim-win64.zip](https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip) and extract

2. Download [Goneovim-0.4.3-win64](https://github.com/akiyosi/goneovim/releases/download/v0.4.3/Goneovim-0.4.3-win64.zip)

3. Extract Goneovim and copy the files into `Neovim\bin\`

**Comment by akiyosi** [comment]
Hi

I have confirmed the problem that your pointed out in a survey of another Windows environment. This issue will be fixed in a future release.

**Comment by akiyosi** [comment]
Fixed at v0.4.4
