### ISSUE TITLE
Minimap does not sync

### ISSUE THREAD

**Issue by the42** [akiyosi/goneovim#93]
When using the :GonvimMinimap Command, the minimap does not sync with the content scrolling nor do I have a mean to quickly jump in the minimap when editing a large file.

GoonvimVersion 0.4.3

**Comment by akiyosi** [comment]
Hi

Are you using Neovim 0.5.0?
Currently, the minimap feature of Goneovim-0.4.3 does not support neovim0.5.0.

**Comment by the42** [comment]
Hello,
Neovim is version v0.5.0-297 so unfortunately yes.

**Comment by akiyosi** [comment]
Minimap support for Neovim 0.5.0 comes from the following commits: 
https://github.com/akiyosi/goneovim/commit/52139f1428c103d446b159408380d9eefaf64074

The next release will include fixes.

**Comment by akiyosi** [comment]
Fixed at v0.4.4
