### ISSUE TITLE
Looking up spelling suggestions causes hang

### ISSUE THREAD

**Issue by ahshah** [akiyosi/goneovim#94]
On Mac OSX, building from master (e23f6b)
+ Open up a new instance
+ :nmap ss :setlocal spell spelllang=en_us
+ Create a spelling mistake in a new, empty buffer.
+ z=

Expected: Should show a list of suggestions
Actual: Mac OS beachball of doom (UI becomes non responsive, mouse cursor turns to wait symbol, CPU is oddly, unused, likely seems the UI is deadlocked)
Never recovers.

**Comment by ahshah** [comment]
Using nvim 0.4.3 under the hood

**Comment by akiyosi** [comment]
Hi
Thank you for your report :D 

I'm trying to reproduce, but I can't.
Can you reproduce the problem on an instance launched on `goneovim -u NONE`?

Also please tell me the contents of `~/.goneovim/setting.toml`

**Comment by ahshah** [comment]
Hi,
No problem. Thank you for looking into it. 
I can reproduce the problem vis goneovim -u NONE

Here is my setting.toml 

`$ cat ~/.goneovim/setting.toml
[Editor]
# Editor minimum window width (>= 800)
Width = 800
# Editor minimum window height (>= 600)
Height = 1000

# Start maximized window
StartMaximizedWindow = false

# Start fullscreen
StartFullscreen = false


# Neovim external UI features
ExtCmdline = false
ExtPopupmenu = true
ExtTabline  = false
ExtMessages = true

# Drawing window border instead of vertical split, statusline
DrawBorder = true

# Copy yanked text to clipboard
Clipboard = true

# Disable IME in Normal mode
DisableImeInNormal = false

# Transparent window alpha
# Note: This setting also implicitly enables the Drawborder setting
Transparent = 1.0

# Draw indent guide
IndentGuide = true`

**Comment by akiyosi** [comment]
Thanks.

Neovim seems to hang when ext_messages is true.  I will create an issue in neovim repository.

**Comment by glacambre** [comment]
@akiyosi This issue is now fixed on neovim's master branch :).

**Comment by akiyosi** [comment]
@glacambre 
Thanks for the info :D
I have confirmed that this problem has been fixed.
Closed.
