### ISSUE TITLE
First time user, initial thoughts

### ISSUE THREAD

**Issue by joereynolds** [akiyosi/goneovim#95]
Hi,

I want to start using goneovim everyday if possible, I like its workspace management, features and overall feel. There are a few issues I've had using it in my first hour or so though:

- The popup for notices is usually in the top right, but if the message is too long, it is displayed at the bottom. This is very inconsistent and makes me unsure where to look. I think it'd be a better idea to wrap long messages but keep this popup in the top right

- The wiki is good but the documentation for each option is a bit sparse, I think we need explanations and even screenshots for each option. I don't know what `ExtTabline` or `DisableImeInNormal` mean for example

- Again, the output of `:` is inconsistent. If I do `:ls` the prompt is at the bottom. But, if it's a shell command and I do `:!ls` then all of the text is in the top right again. I think there should be one (configurable) place to put all of it

- I'm having some issues with the popups from the LSP (coc in my case) obscuring eachother. This doesn't happen in the terminal neovim (screenshot below)

![image](https://user-images.githubusercontent.com/9536682/73840149-7271ee80-480f-11ea-9499-907245a841bf.png)

- In general I preferred the popup notices in the original gonvim repository. They were small and underneath your cursor, you knew where to look

- Using the default `setting.toml` from the wiki page, I am having an issue where I cannot see my tabs. They are there, but not visible

- If you have `set inccommand=split` in your `init.vim` it gets displayed over everything and results in multiple windows clashing with each other. Once you exit the command, the window is still there too, you have to exit goneovim to fix it

![image](https://user-images.githubusercontent.com/9536682/73840339-df858400-480f-11ea-94e6-115b442abe79.png)

- The scrolling on the markdown viewer presented by `:GonvimMarkdown` is backwards. I think this should respect the OS's choice for scrolling. I'm not sure if you've put custom scrolling in here but it feels like you have

- There are some undocumented options for starting `goneovim`. I was wondering how to start it without using my `init.vim` but it wasn't said anywhere, I later found in one of the issues that you can do `goneovim -u NONE`. I think this sort of thing should be documented under the `--help` flag

I know this is a lot of criticism but it's because I like the potential of this project. If I can get this working how I want, I will use it daily. If there's any more information you need, please let me know!

### Environment details

```
os: Ubuntu 18.04
neovim: NVIM v0.5.0-175-g525bb1b55
window manager: i3
[my init.vim](https://github.com/joereynolds/configs/blob/master/roles/common/files/nvim/init.vim)
```

Thank you so much for creating one of the better neovim ui's, I look forward to using it even more :)

**Comment by akiyosi** [comment]
Thanks for your feedback 😀
I will be grateful that you had you for taking the time to write this issue.

> The popup for notices is usually in the top right, but if the message is too long, it is displayed at the bottom. This is very inconsistent and makes me unsure where to look. I think it'd be a better idea to wrap long messages but keep this popup in the top right

There is a need for ongoing discussion on how to display message popups when ExtMessages is enabled.
If, as you say, the message is displayed in the same position both long and short text, I think that it seems better to display it in the traditional way of displaying messages in vim (ie at the bottom of the window). Or should we consider display resolution in addition to text length?

There is some discussion on ExtMassages in the gnvim repository.
https://github.com/vhakulinen/gnvim/pull/57


> The wiki is good but the documentation for each option is a bit sparse, I think we need explanations and even screenshots for each option. I don't know what ExtTabline or DisableImeInNormal mean for example

Thank you. I'll add documentation little by little.


> I'm having some issues with the popups from the LSP (coc in my case) obscuring eachother. This doesn't happen in the terminal neovim (screenshot below)
> In general I preferred the popup notices in the original gonvim repository. They were small and underneath your cursor, you knew where to look

Is this a screenshot when ExtPopupmenu is enabled? If so, it looks like display is broken. It might be a bug.
I have also added some display options when ExtPopupmenu is enabled (See https://github.com/akiyosi/goneovim/pull/73), but the wiki doesn't provide enough explanation for this as well.
I may need additional documentation and bug fixes.


> Using the default setting.toml from the wiki page, I am having an issue where I cannot see my tabs. They are there, but not visible

I have confirmed this problem but have not identified a clear cause at this time. I will continue to investigate.


> If you have set inccommand=split in your init.vim it gets displayed over everything and results in multiple windows clashing with each other. Once you exit the command, the window is still there too, you have to exit goneovim to fix it

This is a neovim bug. 
Related issue: https://github.com/neovim/neovim/issues/11529


> The scrolling on the markdown viewer presented by :GonvimMarkdown is backwards. I think this should respect the OS's choice for scrolling. I'm not sure if you've put custom scrolling in here but it feels like you have

OK, I will improve this.


> There are some undocumented options for starting goneovim. I was wondering how to start it without using my init.vim but it wasn't said anywhere, I later found in one of the issues that you can do goneovim -u NONE. I think this sort of thing should be documented under the --help flag

In the current I/F specification, all options except for the goneovim's own to be interpreted as nvim options.
It makes it difficult to display all options in `--help`, but I will improve this to mention the documentation.

**Comment by joereynolds** [comment]
> Is this a screenshot when ExtPopupmenu is enabled? If so, it looks like display is broken. It might be a bug.

Yep `ExtPopupmenu` is set to true.


> If, as you say, the message is displayed in the same position both long and short text, I think that it seems better to display it in the traditional way of displaying messages in vim (ie at the bottom of the window). 

Sounds good. I think the most important thing is consistency

Thanks for the reply!

**Comment by akiyosi** [comment]
Hi
The popup menu displayed of your screenshot seems to be a floating window pop-up that coc displays on its own. If you want to disable this, add the following settings to coc-setting.json.

``` json
{
	"suggest.floatEnable": false
}
```

If you want to prioritize coc's completion menu, you have to disable Goneovim's ExtPopupmenu. I’m no plan at the moment on how to make them compatible.

**Comment by joereynolds** [comment]
Thanks for the help @akiyosi !

**Comment by tssm** [comment]
I would like to add that the floating messages remain open until I open the command line with `:`, which is annoying. That's the default Vim behaviour, but it would be great if they disappeared after a certain time or I press any key, after all I can read them again with `:messages`

**Comment by akiyosi** [comment]
@tssm 
Hi, thaks for comment.
I would plan to add that option.
What is a good option name?

``` toml
[messages]
hideWhenOpenCommandline = true
```

**Comment by tssm** [comment]
I think that name is OK although English is not my first language

**Comment by PitcherTear22** [comment]
Floating messages for errors/warnings on a particular line should dissapear when the cursor (text/mouse) is on another line tho

**Comment by digital-carver** [comment]
> The scrolling on the markdown viewer presented by :GonvimMarkdown is backwards. I think this should respect the OS's choice for scrolling. I'm not sure if you've put custom scrolling in here but it feels like you have

I can confirm this is still true. Scrolling down goes up the file, scrolling up goes downwards (it works fine in every other application, so it's specific to GoNeoVim). And the scroll is very jittery too. 

Also, the viewer seems unable to scroll to show the last few lines of the file, when using mouse wheel. I have to use the scrollbar on the right if I want to see those lines. 

(Btw, thank you very much for this great enhancement to Neovim!)

**Comment by akiyosi** [comment]
@digital-carver 
Thanks for your comment!
I have added an option `ReversingScrollDirection ` in Goneovim v0.4.12 to reverse the scroll direction. See https://github.com/akiyosi/goneovim/wiki/Usage#configuration
I'm hoping this option will solve the scroll direction problem. 

Also, I will look into the second problem you pointed out; the inability to scroll to the end of the page using the mouse wheel.
