### ISSUE TITLE
Sometimes when goneovim is being closed an orphan nvim instance keeps running (and may the CPU a lot)

### ISSUE THREAD

**Issue by tssm** [akiyosi/goneovim#96]
This is above all a question. In macOS Catalina, when I launch Goneovim I see two running instances of nvim on the Activity Monitor. Of course I checked and double checked that they appear only when I use Goneovim. Is this intended?

Normally, when I close Goneovim both nvim process are closed too, but in some occasions one of them keeps running using a 99% of my CPU and I have to "Force quit" it. In one occasion I had two super hungry nvim process.

I thought this my be related to one of my plugins, but the double nvim happens even if I pass `-u NONE` to Neovim. I haven't isolated the 99% of CPU thing, but it my be related to my workflow: I think I trigger it while developing a plug-in, open and closing Goneovim several times.

**Comment by akiyosi** [comment]
Hi
Thank you for this report.

Yes, launching two nvim processes is the intended behavior, one of which is for displaying the minimap.
I have confirmed that there is a bug that one process remains for some reason. However, I have not been able to investigate enough at this time.
I plan to fix it in the next release.

**Comment by tssm** [comment]
It would be cool to disable the minimap from `~/.goneovim/settings.toml` so the second instance is not launched, but it's a minor detail.

I'll try to investigate why sometimes the second process is not properly closed and I'll let you know if I can replicate it

**Comment by tssm** [comment]
OK, apparently it occurs if I open Goneovim and almost immediately close it, which is something I do a lot 😅 It also causes the 99% CPU thing

**Comment by akiyosi** [comment]
Hi, thanks for your investigate.

> it occurs if I open Goneovim and almost immediately close it,

I see. Currently, the minimap nvim process starts after 1.5 seconds and may be relevant.

**Comment by tssm** [comment]
Aha, yes, I can see nvim process starting a bit after I closed Goneovim. What I don't understand is the 99% CPU part 😅

**Comment by akiyosi** [comment]
Is it due to the death of the parent process🤔
Either way, I will improve this problem in the next release.
