### ISSUE TITLE
nvim_win_get_position/ nvim_open_win maybe problematic

### ISSUE THREAD

**Issue by eyalk5** [akiyosi/goneovim#98]
see https://github.com/Yggdroot/LeaderF/issues/501

**Comment by eyalk5** [comment]
nvim_win_get_position returns ['0', '0'].
That is why the heigth is set to -1, resulting in 
{'relative': 'editor', 'anchor': 'SW', 'height': -1, 'width': 70, 'row': -1, 'col': 0}
as a paramter to open_win.

**Comment by akiyosi** [comment]
Hi
Thanks for this report.

I'm not sure, but is the problem that the `echo nvim_win_get_position(win_getid('%'))` result is always `[0, 0]` on the float window? Indeed, I have confirmed that the above result is `[0, 0]` on the float window displayed by `Yggdroot/LeaderF`. Also, neovim-qt may return a normal position such as `[14, 26]`. I think this problem may seems to be a problem on nvim core. 
I will continue to investigate.

**Comment by akiyosi** [comment]
I reported an issue: https://github.com/neovim/neovim/issues/11935

**Comment by eyalk5** [comment]
So, what is the verdict? is leaderF implementation should change?

**Comment by akiyosi** [comment]
Yes, according to neovim/neovim#11935, leaderF implementation will need to change.
According to https://github.com/neovim/neovim/issues/11935, I think the following line needs to be changed to `nvim_win_get_config()`:

https://github.com/Yggdroot/LeaderF/blob/d6a6b63eedf2b91c2f5c620b6ea1a5090fc7fee7/autoload/leaderf/python/leaderf/manager.py#L429-L430

**Comment by akiyosi** [comment]
this issue fixed with https://github.com/Yggdroot/LeaderF/commit/eb91151972c55f4a6b695387c0bee3fb6d3a7698 and https://github.com/akiyosi/goneovim/commit/8cad126573b3503d42d0b7a69680a8fd13fec08b

**Comment by akiyosi** [comment]
This has been fixed in v0.4.5.
please confirm.

**Comment by eyalk5** [comment]
This is working up to wrong position. But their bug anyway. Thanks.

**Comment by akiyosi** [comment]
Is it still displayed in the wrong position?
